# Generated by Django 4.0.6 on 2022-07-25 15:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import inventory.models.attachment
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.CharField(
                        max_length=200,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "listing_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Listing price",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True, max_length=1000, null=True, verbose_name="Remarks"
                    ),
                ),
                (
                    "local_status",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("placeholder", "Placeholder"),
                            ("to_be_delivered", "To be delivered"),
                            ("under_review", "Under review"),
                            ("maintenance_in_house", "Maintenance in house"),
                            ("maintenance_external", "Maintenance external"),
                            ("available", "Available"),
                            ("issued_unprocessed", "Issued unprocessed"),
                            ("issued_rent", "Issued rent"),
                            ("issued_loan", "Issued loan"),
                            ("amortized", "Amortized"),
                            ("sold", "Sold"),
                        ],
                        default="Unknown",
                        max_length=40,
                        verbose_name="Local status",
                    ),
                ),
            ],
            options={
                "verbose_name": "asset",
                "verbose_name_plural": "assets",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="AssetCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "name_singular",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile("^[-\\w]+\\Z"),
                                "Enter a valid “slug” consisting of Unicode letters, numbers, underscores, or hyphens.",
                                "invalid",
                            )
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="AssetLocationGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "location group",
                "verbose_name_plural": "location groups",
            },
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Collection Name"
                    ),
                ),
                ("commerce", models.BooleanField()),
            ],
            options={
                "verbose_name": "Collectie",
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        upload_to=inventory.models.attachment.attachments_directory_path,
                        verbose_name="Attachment",
                    ),
                ),
                (
                    "upload_date",
                    models.DateField(auto_now_add=True, verbose_name="Upload date"),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True, max_length=1000, verbose_name="Remarks"
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.asset",
                        verbose_name="Asset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bijlage",
            },
        ),
        migrations.CreateModel(
            name="AssetSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("categories", models.ManyToManyField(to="inventory.assetcategory")),
            ],
            options={
                "verbose_name": "size",
                "verbose_name_plural": "sizes",
            },
        ),
        migrations.CreateModel(
            name="AssetOnRecurringSalesInvoiceDocumentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_sales_invoice_document_line_assets",
                        to="inventory.asset",
                    ),
                ),
                (
                    "document_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="accounting.recurringsalesinvoicedocumentline",
                    ),
                ),
            ],
            options={
                "unique_together": {("asset", "document_line")},
            },
        ),
        migrations.CreateModel(
            name="AssetOnJournalDocumentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_document_line_assets",
                        to="inventory.asset",
                    ),
                ),
                (
                    "document_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="accounting.journaldocumentline",
                    ),
                ),
            ],
            options={
                "unique_together": {("asset", "document_line")},
            },
        ),
        migrations.CreateModel(
            name="AssetOnEstimateDocumentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estimate_document_line_assets",
                        to="inventory.asset",
                    ),
                ),
                (
                    "document_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="accounting.estimatedocumentline",
                    ),
                ),
            ],
            options={
                "unique_together": {("asset", "document_line")},
            },
        ),
        migrations.CreateModel(
            name="AssetLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "location_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.assetlocationgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "location",
                "verbose_name_plural": "locations",
            },
        ),
        migrations.AddField(
            model_name="asset",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.assetcategory",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.collection",
                verbose_name="Collection",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="estimate_document_lines",
            field=models.ManyToManyField(
                through="inventory.AssetOnEstimateDocumentLine",
                to="accounting.estimatedocumentline",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="journal_document_lines",
            field=models.ManyToManyField(
                through="inventory.AssetOnJournalDocumentLine",
                to="accounting.journaldocumentline",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.assetlocation",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="recurring_sales_invoice_document_lines",
            field=models.ManyToManyField(
                through="inventory.AssetOnRecurringSalesInvoiceDocumentLine",
                to="accounting.recurringsalesinvoicedocumentline",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.assetsize",
            ),
        ),
        migrations.CreateModel(
            name="AssetSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_subscriptions",
                        to="inventory.asset",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="accounting.subscription",
                    ),
                ),
            ],
            options={
                "unique_together": {("asset", "subscription")},
            },
        ),
    ]
