# Generated by Django 4.1.7 on 2023-05-03 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AssetCategory",
            new_name="Category",
        ),
        migrations.RenameModel(
            old_name="AssetLocation",
            new_name="Location",
        ),
        migrations.RenameModel(
            old_name="AssetLocationGroup",
            new_name="LocationGroup",
        ),
        migrations.RenameModel(
            old_name="AssetSize",
            new_name="Size",
        ),
    ]
