# Generated by Django 4.0.6 on 2022-07-29 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attachment",
            name="remarks",
        ),
    ]
