# Generated by Django 4.1.7 on 2023-05-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_rename_assetcategory_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="name"),
        ),
    ]
