# Generated by Django 4.0.6 on 2022-07-29 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_remove_attachment_remarks"),
    ]

    operations = [
        migrations.CreateModel(
            name="Remark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remark", models.TextField(verbose_name="Remark")),
                ("date", models.DateField(auto_now_add=True, verbose_name="date")),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.asset",
                        verbose_name="Asset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Remark",
            },
        ),
    ]
