# Generated by Django 5.1.6 on 2025-07-20 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_alter_attachment_attachment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of this property (e.g., 'Color', 'Weight', 'Material')",
                        max_length=100,
                        verbose_name="property name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly version with category prefix (e.g., 'electronics-color', 'furniture-weight')",
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("number", "Number"),
                            ("dropdown", "Dropdown"),
                        ],
                        default="string",
                        max_length=20,
                        verbose_name="property type",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Unit for numeric properties (e.g., 'kg', 'cm', 'V')",
                        max_length=20,
                        verbose_name="unit",
                    ),
                ),
                (
                    "dropdown_options",
                    models.TextField(
                        blank=True,
                        help_text='JSON array of options for dropdown properties (e.g., ["Red", "Blue", "Green"])',
                        verbose_name="dropdown options",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in which properties are displayed",
                        verbose_name="display order",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="inventory.category",
                        verbose_name="category",
                    ),
                ),
            ],
            options={
                "verbose_name": "asset property",
                "verbose_name_plural": "asset properties",
                "ordering": ["category", "order", "name"],
                "unique_together": {("category", "name")},
            },
        ),
        migrations.CreateModel(
            name="AssetPropertyValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        help_text="The value of this property for this asset",
                        verbose_name="value",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_values",
                        to="inventory.asset",
                        verbose_name="asset",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="inventory.assetproperty",
                        verbose_name="property",
                    ),
                ),
            ],
            options={
                "verbose_name": "asset property value",
                "verbose_name_plural": "asset property values",
                "unique_together": {("asset", "property")},
            },
        ),
    ]
