# Generated by Django 5.1.6 on 2025-07-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_assetproperty_assetpropertyvalue"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assetproperty",
            options={
                "ordering": ["name", "order"],
                "verbose_name": "asset property",
                "verbose_name_plural": "asset properties",
            },
        ),
        migrations.AlterUniqueTogether(
            name="assetproperty",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="assetproperty",
            name="categories",
            field=models.ManyToManyField(
                help_text="Categories this property applies to",
                related_name="properties",
                to="inventory.category",
                verbose_name="categories",
            ),
        ),
        migrations.AlterField(
            model_name="assetproperty",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly version of property name (e.g., 'color', 'weight')",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="slug",
            ),
        ),
        migrations.RemoveField(
            model_name="assetproperty",
            name="category",
        ),
    ]
