# Generated by Django 4.1.7 on 2023-04-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_alter_asset_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="raw_data",
            field=models.JSONField(blank=True, null=True, verbose_name="raw data"),
        ),
    ]
