# Generated by Django 4.1.7 on 2023-05-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_asset_raw_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remark",
            name="date",
            field=models.DateField(auto_now_add=True, null=True, verbose_name="date"),
        ),
    ]
