# Generated by Django 5.1.6 on 2025-07-20 21:43

from django.db import migrations
from django.utils.text import slugify


def update_property_slugs(apps, schema_editor):
    """Update existing property slugs to remove category prefixes."""
    AssetProperty = apps.get_model("inventory", "AssetProperty")

    for prop in AssetProperty.objects.all():
        # Generate new slug from just the property name
        new_slug = slugify(prop.name)

        # Ensure uniqueness
        counter = 1
        original_slug = new_slug
        while AssetProperty.objects.filter(slug=new_slug).exclude(id=prop.id).exists():
            new_slug = f"{original_slug}-{counter}"
            counter += 1

        prop.slug = new_slug
        prop.save()


def reverse_update_property_slugs(apps, schema_editor):
    """Reverse operation - not implemented as old slugs can't be reconstructed."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_alter_assetproperty_options_and_more"),
    ]

    operations = [
        migrations.RunPython(update_property_slugs, reverse_update_property_slugs),
    ]
