# Generated by Django 5.1.6 on 2025-08-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_auto_20250720_2343"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attachment",
            options={
                "ordering": ["order", "upload_date"],
                "verbose_name": "attachment",
                "verbose_name_plural": "attachments",
            },
        ),
        migrations.AddField(
            model_name="attachment",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Order in which attachments are displayed",
                verbose_name="order",
            ),
        ),
    ]
