# Generated by Django 5.1.6 on 2025-09-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_alter_attachment_options_attachment_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="disposal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("out_of_use", "out of use"),
                    ("sold", "sold"),
                    ("private_withdrawal", "private withdrawal"),
                    ("divested", "divested"),
                ],
                help_text="Asset disposal reason from Moneybird data",
                max_length=20,
                null=True,
                verbose_name="disposal status",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="is_margin_asset",
            field=models.BooleanField(
                default=False,
                help_text="From a tax perspective, is this property a used good to which the margin scheme applies (purchased from a consumer or purchased under the margin scheme)?",
                verbose_name="is margin",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="moneybird_asset_id",
            field=models.IntegerField(
                blank=True,
                help_text="ID of the corresponding asset in Moneybird",
                null=True,
                unique=True,
                verbose_name="Moneybird asset ID",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="moneybird_data",
            field=models.JSONField(
                blank=True,
                help_text="Cached data from Moneybird API",
                null=True,
                verbose_name="Moneybird data",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="purchase_value_asset",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Purchase value of the asset",
                max_digits=10,
                null=True,
                verbose_name="purchase value",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="start_date",
            field=models.DateField(
                blank=True,
                help_text="Date when the asset was put into service",
                null=True,
                verbose_name="start date",
            ),
        ),
    ]
