# Generated by Django 5.1.6 on 2025-09-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_asset_disposal_asset_is_margin_asset_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="estimate_document_lines",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="journal_document_lines",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="recurring_sales_invoice_document_lines",
        ),
        migrations.AddField(
            model_name="asset",
            name="current_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Current value of the asset from Moneybird",
                max_digits=10,
                null=True,
                verbose_name="current value",
            ),
        ),
    ]
