# Generated by Django 5.1.6 on 2025-09-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_remove_asset_estimate_document_lines_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="moneybird_asset_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="ID of the corresponding asset in Moneybird",
                null=True,
                unique=True,
                verbose_name="Moneybird asset ID",
            ),
        ),
    ]
