# Generated by Django 5.1.6 on 2025-09-07 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_alter_asset_moneybird_asset_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        help_text="The status the asset changed to",
                        max_length=40,
                        verbose_name="new status",
                    ),
                ),
                (
                    "status_date",
                    models.DateField(
                        help_text="The date when this status change occurred",
                        verbose_name="status date",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this status change was recorded in the system",
                        verbose_name="created at",
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True,
                        help_text="Optional comments about this status change",
                        verbose_name="comments",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_changes",
                        to="inventory.asset",
                        verbose_name="asset",
                    ),
                ),
                (
                    "previous_status_change",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to the previous status change for this asset",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="next_status_change",
                        to="inventory.statuschange",
                        verbose_name="previous status change",
                    ),
                ),
            ],
            options={
                "verbose_name": "status change",
                "verbose_name_plural": "status changes",
                "ordering": ["-status_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["asset", "-status_date", "-created_at"],
                        name="inventory_s_asset_i_bcebb6_idx",
                    )
                ],
            },
        ),
    ]
