# Generated by Django 5.1.6 on 2025-09-07 21:06

from django.db import migrations
from django.utils import timezone


def create_initial_status_changes(apps, schema_editor):
    """Create initial StatusChange records for all existing assets."""
    Asset = apps.get_model("inventory", "Asset")
    StatusChange = apps.get_model("inventory", "StatusChange")

    # Get all assets with their current local_status
    for asset in Asset.objects.all():
        # Create an initial status change using the asset's creation date as the status_date
        # and the current local_status as the new_status
        StatusChange.objects.create(
            asset=asset,
            new_status=asset.local_status,
            status_date=asset.created_at.date(),
            comments="Initial status",
            # previous_status_change is None for initial status
        )


def reverse_initial_status_changes(apps, schema_editor):
    """Remove all initial status changes (for migration rollback)."""
    StatusChange = apps.get_model("inventory", "StatusChange")

    # Delete all status changes with the initial comment
    StatusChange.objects.filter(comments="Initial status").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_add_status_change_model"),
    ]

    operations = [
        migrations.RunPython(
            create_initial_status_changes,
            reverse_initial_status_changes,
        ),
    ]
