# Generated by Django 5.1.6 on 2025-09-07 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0015_alter_statuschange_new_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="statuschange",
            options={
                "ordering": ["status_date", "created_at"],
                "verbose_name": "status change",
                "verbose_name_plural": "status changes",
            },
        ),
    ]
