# Generated by Django 5.1.6 on 2025-09-07 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_alter_contact_bank_account_alter_contact_sepa_iban"),
        ("inventory", "0016_alter_statuschange_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="statuschange",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                help_text="Moneybird contact associated with this status change",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="status_changes",
                to="accounting.contact",
                verbose_name="contact",
            ),
        ),
    ]
