# Generated by Django 5.1.6 on 2025-09-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0017_statuschange_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statuschange",
            name="new_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("unknown", "unknown"),
                    ("placeholder", "placeholder"),
                    ("to_be_delivered", "to be delivered"),
                    ("under_review", "under review"),
                    ("maintenance_in_house", "maintenance in house"),
                    ("maintenance_external", "maintenance external"),
                    ("available", "available"),
                    ("issued_unprocessed", "issued unprocessed"),
                    ("issued_rent", "issued rent"),
                    ("issued_loan", "issued loan"),
                    ("amortized", "amortized"),
                    ("sold", "sold"),
                ],
                help_text="The status the asset changed to, or null for no status change",
                max_length=40,
                null=True,
                verbose_name="new status",
            ),
        ),
    ]
