# Generated by Django 5.1.6 on 2025-09-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0018_alter_statuschange_new_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="disposal",
            field=models.CharField(
                blank=True,
                choices=[("out_of_use", "out of use"), ("divested", "divested")],
                help_text="Asset disposal reason from Moneybird data",
                max_length=20,
                null=True,
                verbose_name="disposal status",
            ),
        ),
    ]
