# Generated by Django 5.1.6 on 2025-09-20 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0019_remove_sold_private_withdrawal_disposal_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statuschange",
            name="previous_status_change",
        ),
    ]
