# Generated by Django 5.1.6 on 2025-10-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0020_remove_previous_status_change_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusType",
            fields=[
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique identifier used in code (e.g., 'available', 'issued_rent')",
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                        verbose_name="slug",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this status",
                        max_length=100,
                        verbose_name="name",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="primary",
                        help_text="Bootstrap color class (e.g., 'success', 'warning', 'danger')",
                        max_length=20,
                        verbose_name="color",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this status means the asset is archived/no longer active",
                        verbose_name="is archived",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Display order in lists and dropdowns",
                        verbose_name="order",
                    ),
                ),
            ],
            options={
                "verbose_name": "status type",
                "verbose_name_plural": "status types",
                "ordering": ["order", "name"],
            },
        ),
    ]
