# Generated by Django 5.1.6 on 2025-10-12 09:49

from django.db import migrations


def populate_status_types(apps, schema_editor):
    """Populate StatusType table with the current AssetStates."""
    StatusType = apps.get_model("inventory", "StatusType")

    # Define all status types with their properties
    # Format: (slug, name, color, is_archived, order)
    status_types = [
        ("unknown", "Unknown", "danger", False, 0),
        ("placeholder", "Placeholder", "light", False, 1),
        ("to_be_delivered", "To be delivered", "secondary", False, 2),
        ("under_review", "Under review", "info", False, 3),
        ("maintenance_in_house", "Maintenance in house", "info", False, 4),
        ("maintenance_external", "Maintenance external", "info", False, 5),
        ("available", "Available", "success", False, 6),
        ("issued_unprocessed", "Issued unprocessed", "warning", False, 7),
        ("issued_rent", "Issued rent", "warning", False, 8),
        ("issued_loan", "Issued loan", "warning", False, 9),
        ("amortized", "Amortized", "dark", True, 10),
        ("sold", "Sold", "secondary", True, 11),
    ]

    for slug, name, color, is_archived, order in status_types:
        StatusType.objects.create(
            slug=slug,
            name=name,
            color=color,
            is_archived=is_archived,
            order=order,
        )


def reverse_populate(apps, schema_editor):
    """Remove all status types."""
    StatusType = apps.get_model("inventory", "StatusType")
    StatusType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0021_create_status_type"),
    ]

    operations = [
        migrations.RunPython(populate_status_types, reverse_populate),
    ]
