# Generated by Django 5.1.6 on 2025-10-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0022_populate_status_types"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statustype",
            name="color",
        ),
        migrations.AddField(
            model_name="statustype",
            name="background_color",
            field=models.CharField(
                default="#0d6efd",
                help_text="Hex color code for background (e.g., '#198754' for green)",
                max_length=7,
                verbose_name="background color",
            ),
        ),
        migrations.AddField(
            model_name="statustype",
            name="text_color",
            field=models.CharField(
                default="#ffffff",
                help_text="Hex color code for text (e.g., '#ffffff' for white)",
                max_length=7,
                verbose_name="text color",
            ),
        ),
    ]
