# Generated by Django 5.1.6 on 2025-10-12 09:58

from django.db import migrations


def update_status_colors(apps, schema_editor):
    """Update status types with actual hex color values based on Bootstrap 5 colors."""
    StatusType = apps.get_model("inventory", "StatusType")

    # Bootstrap 5 color mappings to hex values
    # Format: (slug, background_color, text_color)
    color_mappings = [
        ("unknown", "#dc3545", "#ffffff"),  # danger (red)
        ("placeholder", "#f8f9fa", "#212529"),  # light (light gray with dark text)
        ("to_be_delivered", "#6c757d", "#ffffff"),  # secondary (gray)
        ("under_review", "#0dcaf0", "#000000"),  # info (cyan)
        ("maintenance_in_house", "#0dcaf0", "#000000"),  # info (cyan)
        ("maintenance_external", "#0dcaf0", "#000000"),  # info (cyan)
        ("available", "#198754", "#ffffff"),  # success (green)
        ("issued_unprocessed", "#ffc107", "#000000"),  # warning (yellow with dark text)
        ("issued_rent", "#ffc107", "#000000"),  # warning (yellow with dark text)
        ("issued_loan", "#ffc107", "#000000"),  # warning (yellow with dark text)
        ("amortized", "#212529", "#ffffff"),  # dark (dark gray/black)
        ("sold", "#6c757d", "#ffffff"),  # secondary (gray)
    ]

    for slug, bg_color, text_color in color_mappings:
        try:
            status = StatusType.objects.get(slug=slug)
            status.background_color = bg_color
            status.text_color = text_color
            status.save()
        except StatusType.DoesNotExist:
            pass


def reverse_update(apps, schema_editor):
    """Reset colors to defaults (this is just a placeholder)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0023_change_status_type_to_hex_colors"),
    ]

    operations = [
        migrations.RunPython(update_status_colors, reverse_update),
    ]
