# Generated by Django 6.0 on 2025-12-31 12:01

import django.db.models.deletion
from django.db import migrations, models


def convert_location_groups_to_parents(apps, schema_editor):
    """Convert LocationGroups to parent Locations."""
    Location = apps.get_model("inventory", "Location")
    LocationGroup = apps.get_model("inventory", "LocationGroup")

    # Create a mapping of location_group_id to parent Location
    group_to_parent = {}

    # Get all existing location groups
    all_groups = list(LocationGroup.objects.all())
    if not all_groups:
        return  # No groups to convert

    # Use the first group as a temporary placeholder for new parent locations
    temp_group = all_groups[0]

    # For each LocationGroup, create a parent Location
    for group in all_groups:
        parent_location = Location.objects.create(
            name=group.name,
            order=group.order,
            display_as_root=True,
            location_group=temp_group,  # Temporary assignment
        )
        group_to_parent[group.id] = parent_location

    # Update all existing Locations to point to their parent
    for location in Location.objects.exclude(
        id__in=[p.id for p in group_to_parent.values()]
    ):
        if location.location_group_id and location.location_group_id in group_to_parent:
            location.parent = group_to_parent[location.location_group_id]
            location.save(update_fields=["parent"])


def reverse_convert(apps, schema_editor):
    """Reverse the conversion - not fully reversible but best effort."""
    Location = apps.get_model("inventory", "Location")
    LocationGroup = apps.get_model("inventory", "LocationGroup")

    # Find all locations that are display_as_root (these were groups)
    for location in Location.objects.filter(display_as_root=True):
        # Create a LocationGroup
        group = LocationGroup.objects.create(
            name=location.name,
            order=location.order or 0,
        )
        # Update all children to point to this group
        location.children.all().update(location_group=group)
        # Delete the parent location
        location.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0024_update_status_colors_to_hex"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="assetonjournaldocumentline",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="assetonjournaldocumentline",
            name="asset",
        ),
        migrations.RemoveField(
            model_name="assetonjournaldocumentline",
            name="document_line",
        ),
        migrations.AlterUniqueTogether(
            name="assetonrecurringsalesinvoicedocumentline",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="assetonrecurringsalesinvoicedocumentline",
            name="asset",
        ),
        migrations.RemoveField(
            model_name="assetonrecurringsalesinvoicedocumentline",
            name="document_line",
        ),
        migrations.AlterModelOptions(
            name="location",
            options={
                "ordering": ["order", "pk"],
                "verbose_name": "location",
                "verbose_name_plural": "locations",
            },
        ),
        migrations.AddField(
            model_name="location",
            name="display_as_root",
            field=models.BooleanField(
                default=False,
                help_text="Display this location as a root location (don't show parents in name)",
                verbose_name="display as root",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="inventory.location",
                verbose_name="parent location",
            ),
        ),
        migrations.RunPython(convert_location_groups_to_parents, reverse_convert),
        migrations.RemoveField(
            model_name="location",
            name="location_group",
        ),
        migrations.DeleteModel(
            name="AssetOnEstimateDocumentLine",
        ),
        migrations.DeleteModel(
            name="AssetOnJournalDocumentLine",
        ),
        migrations.DeleteModel(
            name="AssetOnRecurringSalesInvoiceDocumentLine",
        ),
        migrations.DeleteModel(
            name="LocationGroup",
        ),
    ]
