version: "3"

services:
  nginx:
    container_name: nginx
    image: nginxproxy/nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-proxy-html:/usr/share/nginx/html/
      - nginx-proxy-certs:/etc/nginx/certs/:ro
      - nginx-proxy-vhost.d:/etc/nginx/vhost.d/
      - ./landolfio.nginx.conf:/etc/nginx/conf.d/landolfio.vofdoesburg.nl.conf:ro
    environment:
      ENABLE_IPV6: 'true'
      TRUST_DOWNSTREAM_PROXY: 'false'
    networks:
      - web

  letsencrypt:
    container_name: letsencrypt
    image: nginxproxy/acme-companion
    restart: unless-stopped
    depends_on:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-proxy-html:/usr/share/nginx/html/
      - nginx-proxy-vhost.d:/etc/nginx/vhost.d/
      - nginx-proxy-certs:/etc/nginx/certs/
      - nginx-proxy-acme:/etc/acme.sh
    environment:
      NGINX_PROXY_CONTAINER: nginx
      DEFAULT_EMAIL: notifications+landolfio@good-job.nl
    networks:
      - web

  database:
    image: postgres:14
    restart: unless-stopped
    networks:
      - db
    environment:
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data/

  web:
    image: ghcr.io/jobdoesburg/landolfio:latest
    restart: unless-stopped
    networks:
      - web
      - db
    depends_on:
      - nginx
      - letsencrypt
      - database
    volumes:
      - ./static/:/static/
      - django-media:/media/
    environment:
      - VIRTUAL_HOST=landolfio.vofdoesburg.nl
      - VIRTUAL_PORT=80
      - VIRTUAL_PROTO=http
      - LETSENCRYPT_HOST=landolfio.vofdoesburg.nl
      - LANDOLFIO_SECRET_KEY
      - LANDOLFIO_ALLOWED_HOSTS
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT
      - MONEYBIRD_ADMINISTRATION_ID
      - MONEYBIRD_API_KEY
      - MONEYBIRD_WEBHOOK_ID
      - MONEYBIRD_WEBHOOK_TOKEN
      - NINOX_API_TOKEN
      - NINOX_TEAM_ID
      - NINOX_DATABASE_ID
      - SENTRY_DSN
      - DJANGO_LOG_LEVEL
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_STORAGE_BUCKET_NAME
      - AWS_S3_REGION_NAME
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_USE_TLS
      - SMTP_USE_SSL
      - SMTP_USER
      - SMTP_PASSWORD
      - SMTP_FROM
      - SMTP_FROM_EMAIL
      - NOTIFICATION_EMAIL
      - PUBLIC_CONTACT_EMAIL

volumes:
  nginx-proxy-html:
  nginx-proxy-vhost.d:
  nginx-proxy-certs:
  nginx-proxy-acme:
  django-media:

networks:
  web:
    external: true
  db:
