# Generated by Django 4.1.5 on 2023-02-03 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewCustomer",
            fields=[
                (
                    "ticket_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tickets.ticket",
                    ),
                ),
                (
                    "wants_sepa_mandate",
                    models.BooleanField(
                        default=True, verbose_name="Wants SEPA mandate"
                    ),
                ),
                (
                    "sepa_mandate_sent",
                    models.BooleanField(
                        default=False, verbose_name="SEPA mandate request was sent"
                    ),
                ),
            ],
            options={
                "verbose_name": "new customer",
                "verbose_name_plural": "new customers",
            },
            bases=("tickets.ticket",),
        ),
    ]
