# Generated by Django 4.0.6 on 2022-07-23 19:38

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import localflavor.generic.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0009_alter_asset_collection_alter_asset_listing_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(
                        blank=True, verbose_name="Moneybird ID"
                    ),
                ),
                (
                    "moneybird_version",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Moneybird version"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="company name",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="voornaam"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="achternaam"
                    ),
                ),
                ("address_1", models.CharField(blank=True, max_length=255, null=True)),
                ("address_2", models.CharField(blank=True, max_length=255, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=10, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "country",
                    django_countries.fields.CountryField(default="NL", max_length=2),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("customer_id", models.CharField(blank=True, max_length=20, null=True)),
                ("tax_number", models.CharField(blank=True, max_length=14, null=True)),
                (
                    "chamber_of_commerce",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
                (
                    "bank_account",
                    localflavor.generic.models.IBANField(
                        blank=True,
                        include_countries=(
                            "AT",
                            "BE",
                            "BG",
                            "CH",
                            "CY",
                            "CZ",
                            "DE",
                            "DK",
                            "EE",
                            "ES",
                            "FI",
                            "FR",
                            "GB",
                            "GI",
                            "GR",
                            "HR",
                            "HU",
                            "IE",
                            "IS",
                            "IT",
                            "LI",
                            "LT",
                            "LU",
                            "LV",
                            "MC",
                            "MT",
                            "NL",
                            "NO",
                            "PL",
                            "PT",
                            "RO",
                            "SE",
                            "SI",
                            "SK",
                            "SM",
                        ),
                        max_length=34,
                        null=True,
                        use_nordea_extensions=False,
                    ),
                ),
                ("attention", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="email"
                    ),
                ),
                (
                    "email_ubl",
                    models.BooleanField(default=False, verbose_name="email ubl"),
                ),
                (
                    "send_invoices_to_attention",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "send_invoices_to_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "send_estimates_to_attention",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "send_estimates_to_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "sepa_active",
                    models.BooleanField(default=False, verbose_name="sepa active"),
                ),
                (
                    "sepa_iban",
                    localflavor.generic.models.IBANField(
                        blank=True,
                        include_countries=(
                            "AT",
                            "BE",
                            "BG",
                            "CH",
                            "CY",
                            "CZ",
                            "DE",
                            "DK",
                            "EE",
                            "ES",
                            "FI",
                            "FR",
                            "GB",
                            "GI",
                            "GR",
                            "HR",
                            "HU",
                            "IE",
                            "IS",
                            "IT",
                            "LI",
                            "LT",
                            "LU",
                            "LV",
                            "MC",
                            "MT",
                            "NL",
                            "NO",
                            "PL",
                            "PT",
                            "RO",
                            "SE",
                            "SI",
                            "SK",
                            "SM",
                        ),
                        max_length=34,
                        null=True,
                        use_nordea_extensions=False,
                    ),
                ),
                (
                    "sepa_iban_account_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "sepa_bic",
                    localflavor.generic.models.BICField(
                        blank=True, max_length=11, null=True
                    ),
                ),
                (
                    "sepa_mandate_id",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("sepa_mandate_date", models.DateField(blank=True, null=True)),
                (
                    "sepa_sequence_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RCUR", "Recurring"),
                            ("FRST", "First"),
                            ("FNAL", "Final"),
                            ("OOFF", "One-off"),
                        ],
                        max_length=4,
                        null=True,
                    ),
                ),
                (
                    "tax_number_valid",
                    models.BooleanField(default=False, verbose_name="tax number valid"),
                ),
                ("sales_invoices_url", models.URLField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DocumentStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(
                        blank=True, verbose_name="Moneybird ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("default", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Document style",
                "verbose_name_plural": "Document styles",
            },
        ),
        migrations.CreateModel(
            name="Estimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(
                        blank=True, verbose_name="Moneybird ID"
                    ),
                ),
                (
                    "moneybird_version",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Moneybird version"
                    ),
                ),
                (
                    "moneybird_json",
                    models.JSONField(null=True, verbose_name="JSON MoneyBird"),
                ),
                ("date", models.DateField(null=True, verbose_name="Date")),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=19,
                        null=True,
                        verbose_name="total price",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("open", "open"),
                            ("late", "late"),
                            ("accepted", "accepted"),
                            ("rejected", "rejected"),
                            ("billed", "billed"),
                            ("archived", "archived"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="State",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estimates",
                        to="accounting.contact",
                        verbose_name="Contact",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estimate",
                "verbose_name_plural": "Estimates",
                "ordering": ("-date",),
            },
        ),
        migrations.CreateModel(
            name="GeneralJournalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(
                        blank=True, verbose_name="Moneybird ID"
                    ),
                ),
                (
                    "moneybird_version",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Moneybird version"
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="date")),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="reference"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LedgerAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(
                        blank=True, verbose_name="Moneybird ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("non_current_assets", "non current assets"),
                            ("current_assets", "current assets"),
                            ("equity", "equity"),
                            ("provisions", "provisions"),
                            ("non_current_liabilities", "non current liabilities"),
                            ("current_liabilities", "current liabilities"),
                            ("revenue", "revenue"),
                            ("direct_costs", "direct costs"),
                            ("expenses", "expenses"),
                            ("other_income_expenses", "other income expenses"),
                        ],
                        max_length=100,
                        verbose_name="Account type",
                    ),
                ),
                (
                    "is_margin",
                    models.BooleanField(
                        default=False,
                        help_text="All assets on this ledger account are margin assets.",
                    ),
                ),
                (
                    "is_sales",
                    models.BooleanField(
                        default=False,
                        help_text="Ledger account is used for selling assets.",
                    ),
                ),
                (
                    "is_purchase",
                    models.BooleanField(
                        default=False,
                        help_text="Ledger account is used for purchasing assets.",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.ledgeraccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ledger account",
                "verbose_name_plural": "Ledger accounts",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(
                        blank=True, verbose_name="Moneybird ID"
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("identifier", models.CharField(blank=True, max_length=100, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("frequency", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "frequency_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("day", "daily"),
                            ("week", "weekly"),
                            ("month", "monthly"),
                            ("quarter", "quarterly"),
                            ("year", "yearly"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="frequency type",
                    ),
                ),
                (
                    "ledger_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.ledgeraccount",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(
                        blank=True, verbose_name="Moneybird ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RecurringSalesInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(
                        blank=True, verbose_name="Moneybird ID"
                    ),
                ),
                (
                    "moneybird_version",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Moneybird version"
                    ),
                ),
                (
                    "moneybird_json",
                    models.JSONField(null=True, verbose_name="JSON MoneyBird"),
                ),
                ("auto_send", models.BooleanField(verbose_name="Auto send")),
                ("active", models.BooleanField(verbose_name="Active")),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("day", "day"),
                            ("week", "week"),
                            ("month", "month"),
                            ("quarter", "quarter"),
                            ("year", "year"),
                        ],
                        max_length=10,
                        verbose_name="frequency",
                    ),
                ),
                ("start_date", models.DateField(null=True, verbose_name="start date")),
                (
                    "invoice_date",
                    models.DateField(null=True, verbose_name="invoice date"),
                ),
                ("last_date", models.DateField(null=True, verbose_name="last date")),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=19,
                        null=True,
                        verbose_name="total price",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurring_sales_invoices",
                        to="accounting.contact",
                        verbose_name="Contact",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurring sales invoice",
                "verbose_name_plural": "Recurring sales invoices",
                "ordering": ("-start_date",),
            },
        ),
        migrations.CreateModel(
            name="TaxRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(
                        blank=True, verbose_name="Moneybird ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("sales_invoice", "Sales invoice"),
                            ("purchase_invoice", "Purchase invoice"),
                            ("general_journal_document", "General journal document"),
                        ],
                        default="sales_invoice",
                        max_length=24,
                        verbose_name="type",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(
                        blank=True, verbose_name="Moneybird ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("InvoiceWorkflow", "Invoice"),
                            ("EstimateWorkflow", "Estimate"),
                        ],
                        default="InvoiceWorkflow",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Workflow",
                "verbose_name_plural": "Workflows",
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(
                        blank=True, verbose_name="Moneybird ID"
                    ),
                ),
                (
                    "moneybird_json",
                    models.JSONField(null=True, verbose_name="JSON MoneyBird"),
                ),
                ("start_date", models.DateField(null=True, verbose_name="start date")),
                ("end_date", models.DateField(null=True, verbose_name="end date")),
                (
                    "cancelled_at",
                    models.DateField(null=True, verbose_name="cancelled at"),
                ),
                (
                    "reference",
                    models.CharField(max_length=200, verbose_name="Reference"),
                ),
                (
                    "frequency",
                    models.PositiveSmallIntegerField(
                        blank=True, default=1, null=True, verbose_name="frequency"
                    ),
                ),
                (
                    "frequency_type",
                    models.CharField(
                        choices=[
                            ("day", "day"),
                            ("week", "week"),
                            ("month", "month"),
                            ("quarter", "quarter"),
                            ("year", "year"),
                        ],
                        max_length=10,
                        verbose_name="frequency type",
                    ),
                ),
                (
                    "asset_id_field",
                    models.CharField(max_length=50, null=True, verbose_name="Asset-ID"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscriptions",
                        to="inventory.asset",
                        verbose_name="Asset",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscriptions",
                        to="accounting.contact",
                        verbose_name="Contact",
                    ),
                ),
                (
                    "document_style",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscriptions",
                        to="accounting.documentstyle",
                        verbose_name="Document style",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscription",
                        to="accounting.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "recurring_sales_invoice",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscriptions",
                        to="accounting.recurringsalesinvoice",
                        verbose_name="Recurring sales invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
                "ordering": ("-start_date",),
            },
        ),
        migrations.CreateModel(
            name="SalesInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(
                        blank=True, verbose_name="Moneybird ID"
                    ),
                ),
                (
                    "moneybird_version",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Moneybird version"
                    ),
                ),
                (
                    "invoice_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="invoice id"
                    ),
                ),
                (
                    "draft_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="draft id"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=19,
                        null=True,
                        verbose_name="total price",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("open", "open"),
                            ("scheduled", "scheduled"),
                            ("pending_payment", "pending payment"),
                            ("late", "late"),
                            ("paid", "paid"),
                            ("uncollectible", "uncollectible"),
                        ],
                        default="draft",
                        max_length=30,
                        verbose_name="state",
                    ),
                ),
                (
                    "invoice_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="invoice date"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="due date"),
                ),
                (
                    "payment_conditions",
                    models.TextField(
                        blank=True, null=True, verbose_name="payment conditions"
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        max_length=255, null=True, verbose_name="payment reference"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="reference"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="discount",
                    ),
                ),
                ("paused", models.BooleanField(default=False, verbose_name="paused")),
                ("paid_at", models.DateField(null=True, verbose_name="paid at")),
                ("sent_at", models.DateField(null=True, verbose_name="sent at")),
                (
                    "public_view_code",
                    models.CharField(
                        max_length=10, null=True, verbose_name="public view code"
                    ),
                ),
                (
                    "total_paid",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="total paid",
                    ),
                ),
                (
                    "total_unpaid",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="total unpaid",
                    ),
                ),
                ("url", models.URLField(null=True, verbose_name="url")),
                ("payment_url", models.URLField(null=True, verbose_name="payment url")),
                (
                    "contact",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_invoices",
                        to="accounting.contact",
                        verbose_name="Contact",
                    ),
                ),
                (
                    "document_style",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.documentstyle",
                        verbose_name="Document style",
                    ),
                ),
                (
                    "original_sales_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.salesinvoice",
                        verbose_name="original sales invoice",
                    ),
                ),
                (
                    "recurring_sales_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.recurringsalesinvoice",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"active": True, "type": "InvoiceWorkflow"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.workflow",
                        verbose_name="Workflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales invoice",
                "verbose_name_plural": "Sales invoices",
                "ordering": ("-invoice_date",),
            },
        ),
        migrations.CreateModel(
            name="RecurringSalesInvoiceDocumentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(
                        blank=True, verbose_name="Moneybird ID"
                    ),
                ),
                (
                    "moneybird_json",
                    models.JSONField(null=True, verbose_name="JSON MoneyBird"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "asset_id_field",
                    models.CharField(max_length=50, null=True, verbose_name="Asset-ID"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurring_sales_invoice_document_lines",
                        to="inventory.asset",
                        verbose_name="Asset",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_lines",
                        to="accounting.recurringsalesinvoice",
                        verbose_name="Document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurring sales invoice document line",
                "verbose_name_plural": "Recurring sales invoice document lines",
                "ordering": ("-document__start_date",),
            },
        ),
        migrations.AddField(
            model_name="recurringsalesinvoice",
            name="workflow",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.workflow",
                verbose_name="Workflow",
            ),
        ),
        migrations.CreateModel(
            name="PurchaseDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(
                        blank=True, verbose_name="Moneybird ID"
                    ),
                ),
                (
                    "moneybird_version",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Moneybird version"
                    ),
                ),
                (
                    "document_kind",
                    models.CharField(
                        choices=[("INK", "Purchase invoice"), ("BON", "Bon")],
                        max_length=3,
                        verbose_name="document kind",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=19,
                        null=True,
                        verbose_name="total price",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("open", "open"),
                            ("scheduled", "scheduled"),
                            ("pending_payment", "pending payment"),
                            ("late", "late"),
                            ("paid", "paid"),
                        ],
                        default="open",
                        max_length=30,
                        verbose_name="state",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="date")),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="due date"),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="reference"
                    ),
                ),
                ("paid_at", models.DateField(null=True, verbose_name="paid at")),
                (
                    "contact",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_documents",
                        to="accounting.contact",
                        verbose_name="Contact",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase document",
                "verbose_name_plural": "Purchase documents",
                "ordering": ("-date",),
            },
        ),
        migrations.AddField(
            model_name="product",
            name="tax_rate",
            field=models.ForeignKey(
                limit_choices_to={"active": True, "type": "sales_invoice"},
                on_delete=django.db.models.deletion.PROTECT,
                to="accounting.taxrate",
            ),
        ),
        migrations.CreateModel(
            name="JournalDocumentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(
                        blank=True, verbose_name="Moneybird ID"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=19, verbose_name="Total amount"
                    ),
                ),
                (
                    "asset_id_field",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Asset-ID"
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journal_document_lines",
                        to="inventory.asset",
                        verbose_name="Asset",
                    ),
                ),
                (
                    "ledger_account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.ledgeraccount",
                        verbose_name="Ledger account",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal document line",
                "verbose_name_plural": "Journal document lines",
            },
        ),
        migrations.CreateModel(
            name="EstimateDocumentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(
                        blank=True, verbose_name="Moneybird ID"
                    ),
                ),
                (
                    "moneybird_json",
                    models.JSONField(null=True, verbose_name="JSON MoneyBird"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "asset_id_field",
                    models.CharField(max_length=50, null=True, verbose_name="Asset-ID"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estimate_document_lines",
                        to="inventory.asset",
                        verbose_name="Asset",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_lines",
                        to="accounting.estimate",
                        verbose_name="Document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estimate document line",
                "verbose_name_plural": "Estimate document lines",
                "ordering": ("-document__date",),
            },
        ),
        migrations.AddField(
            model_name="estimate",
            name="workflow",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.workflow",
                verbose_name="Workflow",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="estimate_workflow",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"active": True, "type": "EstimateWorkflow"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="estimate_workflow_contacts",
                to="accounting.workflow",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="invoice_workflow",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"active": True, "type": "InvoiceWorkflow"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_workflow_contacts",
                to="accounting.workflow",
            ),
        ),
        migrations.CreateModel(
            name="SalesInvoiceDocumentLine",
            fields=[
                (
                    "journaldocumentline_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="accounting.journaldocumentline",
                    ),
                ),
                (
                    "amount",
                    models.CharField(
                        blank=True,
                        default="1 x",
                        max_length=10,
                        null=True,
                        verbose_name="Amount",
                    ),
                ),
                (
                    "amount_decimal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=19,
                        null=True,
                        verbose_name="Amount (decimal)",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=19, verbose_name="price"
                    ),
                ),
                (
                    "row_order",
                    models.PositiveSmallIntegerField(
                        null=True, verbose_name="row order"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_lines",
                        to="accounting.salesinvoice",
                        verbose_name="Document",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "tax_rate",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.taxrate",
                        verbose_name="Tax rate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales invoice document line",
                "verbose_name_plural": "Sales invoice document lines",
                "ordering": ("-document__invoice_date", "row_order"),
            },
            bases=("accounting.journaldocumentline",),
        ),
        migrations.CreateModel(
            name="PurchaseDocumentLine",
            fields=[
                (
                    "journaldocumentline_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="accounting.journaldocumentline",
                    ),
                ),
                (
                    "amount",
                    models.CharField(
                        blank=True,
                        default="1 x",
                        max_length=10,
                        null=True,
                        verbose_name="Amount",
                    ),
                ),
                (
                    "amount_decimal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=19,
                        null=True,
                        verbose_name="Amount (decimal)",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=19, verbose_name="price"
                    ),
                ),
                (
                    "row_order",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="row order"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_lines",
                        to="accounting.purchasedocument",
                        verbose_name="Document",
                    ),
                ),
                (
                    "tax_rate",
                    models.ForeignKey(
                        limit_choices_to={"active": True, "type": "purchase_invoice"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.taxrate",
                        verbose_name="Tax rate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase document line",
                "verbose_name_plural": "Purchase document lines",
                "ordering": ("-document__date", "row_order"),
            },
            bases=("accounting.journaldocumentline",),
        ),
        migrations.CreateModel(
            name="GeneralJournalDocumentLine",
            fields=[
                (
                    "journaldocumentline_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="accounting.journaldocumentline",
                    ),
                ),
                (
                    "debit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=19,
                        null=True,
                        verbose_name="Debit",
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=19,
                        null=True,
                        verbose_name="Credit",
                    ),
                ),
                (
                    "row_order",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="row order"
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.contact",
                        verbose_name="Contact",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_lines",
                        to="accounting.generaljournaldocument",
                        verbose_name="Document",
                    ),
                ),
            ],
            options={
                "verbose_name": "General journal document line",
                "verbose_name_plural": "General journal document lines",
                "ordering": ("-document__date", "row_order"),
            },
            bases=("accounting.journaldocumentline",),
        ),
    ]
