# Generated by Django 4.0.2 on 2022-03-04 00:12
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("json_MB", models.JSONField(verbose_name="JSON MoneyBird")),
                ("date", models.DateField(verbose_name="Date")),
                ("amount", models.FloatField(verbose_name="Amount")),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
            },
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("json_MB", models.JSONField(verbose_name="JSON MoneyBird")),
                ("date", models.DateField(verbose_name="Date")),
                ("amount", models.FloatField(verbose_name="Amount")),
            ],
            options={
                "verbose_name": "Receipt",
                "verbose_name_plural": "Receipts",
            },
        ),
    ]
