# Generated by Django 4.0.4 on 2022-06-09 15:07
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    replaces = [
        ("accounting", "0001_initial"),
        ("accounting", "0002_documentline_asset"),
        ("accounting", "0003_document_link_documentline_ledger"),
        ("accounting", "0004_alter_document_kind"),
        ("accounting", "0005_remove_document_link"),
        ("accounting", "0006_alter_documentline_ledger"),
        ("accounting", "0007_documentline_asset_id_field"),
        ("accounting", "0008_rename_id_mb_document_moneybird_id_and_more"),
        ("accounting", "0009_ledger_alter_documentline_ledger"),
        ("accounting", "0010_documentline_price"),
    ]

    initial = True

    dependencies = [
        ("inventory", "0002_remove_asset_old_id_alter_asset_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(verbose_name="Id MoneyBird"),
                ),
                ("moneybird_json", models.JSONField(verbose_name="JSON MoneyBird")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("PI", "Purchase Invoice"),
                            ("SI", "Sales Invoice"),
                            ("RC", "Receipt"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
            options={
                "unique_together": {("moneybird_id", "kind")},
            },
        ),
        migrations.CreateModel(
            name="Ledger",
            fields=[
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(
                        primary_key=True, serialize=False, verbose_name="Id MoneyBird"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("VOORRAAD_MARGE", "Voorraad Marge"),
                            ("VOORRAAD_NIET_MARGE", "Voorraad niet-marge"),
                            (
                                "VOORRAAD_BIJ_VERKOOP_MARGE",
                                "Voorraadwaarde bij verkoop marge",
                            ),
                            (
                                "VOORRAAD_BIJ_VERKOOP_NIET_MARGE",
                                "Voorraadwaarde bij verkoop niet-marge",
                            ),
                            ("VERKOOP_MARGE", "Verkoop marge"),
                            ("VERKOOP_NIET_MARGE", "Verkoop niet-marge"),
                            ("DIRECTE_AFSCHRIJVING", "Directe afschrijving"),
                            ("AFSCHRIJVINGEN", "Afschrijvingen"),
                            ("BORGEN", "Borgen"),
                        ],
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("moneybird_json", models.JSONField(verbose_name="JSON MoneyBird")),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounting.document",
                        verbose_name="Document",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.asset",
                        verbose_name="Asset",
                    ),
                ),
                (
                    "ledger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.ledger",
                    ),
                ),
                (
                    "asset_id_field",
                    models.CharField(max_length=50, null=True, verbose_name="Asset Id"),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
            ],
        ),
    ]
