# Generated by Django 4.0.6 on 2022-07-06 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0004_assetcategory_assetlocationgroup_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(verbose_name="MoneyBird-ID"),
                ),
                ("version", models.PositiveBigIntegerField(verbose_name="versie")),
                ("moneybird_json", models.JSONField(verbose_name="JSON MoneyBird")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Ledger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(verbose_name="MoneyBird-ID"),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "ledger_kind",
                    models.CharField(
                        choices=[
                            ("VOORRAAD_MARGE", "Voorraad Marge"),
                            ("VOORRAAD_NIET_MARGE", "Voorraad niet-marge"),
                            (
                                "VOORRAAD_BIJ_VERKOOP_MARGE",
                                "Voorraadwaarde bij verkoop marge",
                            ),
                            (
                                "VOORRAAD_BIJ_VERKOOP_NIET_MARGE",
                                "Voorraadwaarde bij verkoop niet-marge",
                            ),
                            ("VERKOOP_MARGE", "Verkoop marge"),
                            ("VERKOOP_NIET_MARGE", "Verkoop niet-marge"),
                            ("DIRECTE_AFSCHRIJVING", "Directe afschrijving"),
                            ("AFSCHRIJVINGEN", "Afschrijvingen"),
                            ("BORGEN", "Borgen"),
                        ],
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Soort",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grootboekrekening",
                "verbose_name_plural": "Grootboekrekeningen",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(verbose_name="MoneyBird-ID"),
                ),
                ("moneybird_json", models.JSONField(verbose_name="JSON MoneyBird")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(verbose_name="MoneyBird-ID"),
                ),
                ("moneybird_json", models.JSONField(verbose_name="JSON MoneyBird")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JournalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(verbose_name="MoneyBird-ID"),
                ),
                ("version", models.PositiveBigIntegerField(verbose_name="versie")),
                ("date", models.DateField()),
                ("moneybird_json", models.JSONField(verbose_name="JSON MoneyBird")),
                (
                    "document_kind",
                    models.CharField(
                        choices=[
                            ("FAC", "Sales invoice"),
                            ("INK", "Purchase invoice"),
                            ("BON", "Bon"),
                            ("MEM", "General journal document"),
                        ],
                        max_length=3,
                        verbose_name="document kind",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Documenten",
                "ordering": ("date",),
                "unique_together": {("moneybird_id", "document_kind")},
            },
        ),
        migrations.CreateModel(
            name="DocumentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(verbose_name="MoneyBird-ID"),
                ),
                ("moneybird_json", models.JSONField(verbose_name="JSON MoneyBird")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=4, max_digits=19, verbose_name="Prijs"
                    ),
                ),
                (
                    "asset_id_field",
                    models.CharField(max_length=50, null=True, verbose_name="Asset-ID"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_lines2",
                        to="inventory.asset",
                        verbose_name="Asset",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounting.journaldocument",
                        verbose_name="Document",
                    ),
                ),
                (
                    "ledger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.ledger",
                        verbose_name="Grootboekrekening",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documentregel",
                "ordering": ("document__date",),
            },
        ),
    ]
