# Generated by Django 4.0.6 on 2022-07-06 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentline",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_lines",
                to="accounting.journaldocument",
                verbose_name="Document",
            ),
        ),
    ]
