# Generated by Django 4.0.2 on 2022-03-07 12:25
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_remove_asset_invoice_remove_asset_receipt_and_more"),
        ("accounting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="asset",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.asset",
                verbose_name="Asset",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="receipt",
            name="asset",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.asset",
                verbose_name="Asset",
            ),
            preserve_default=False,
        ),
    ]
