# Generated by Django 4.0.3 on 2022-04-21 10:22
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_remove_asset_old_id_alter_asset_id"),
        ("accounting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentline",
            name="asset",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.asset",
                verbose_name="Asset",
            ),
        ),
    ]
