# Generated by Django 4.0.4 on 2022-06-13 10:02
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0001_squashed_0010_documentline_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={"verbose_name_plural": "Documenten"},
        ),
        migrations.AlterModelOptions(
            name="documentline",
            options={"verbose_name": "Documentregel"},
        ),
        migrations.AlterModelOptions(
            name="ledger",
            options={
                "verbose_name": "Grootboekrekening",
                "verbose_name_plural": "Grootboekrekeningen",
            },
        ),
        migrations.AlterField(
            model_name="document",
            name="kind",
            field=models.CharField(
                choices=[
                    ("PI", "Aankoopfactuur"),
                    ("SI", "Verkoopfactuur"),
                    ("RC", "Bon"),
                ],
                max_length=2,
                verbose_name="Soort",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="moneybird_id",
            field=models.PositiveBigIntegerField(verbose_name="MoneyBird-ID"),
        ),
        migrations.AlterField(
            model_name="documentline",
            name="asset_id_field",
            field=models.CharField(max_length=50, null=True, verbose_name="Asset-ID"),
        ),
        migrations.AlterField(
            model_name="documentline",
            name="ledger",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="accounting.ledger",
                verbose_name="Grootboekrekening",
            ),
        ),
        migrations.AlterField(
            model_name="documentline",
            name="price",
            field=models.DecimalField(
                decimal_places=4, max_digits=19, verbose_name="Prijs"
            ),
        ),
        migrations.AlterField(
            model_name="ledger",
            name="kind",
            field=models.CharField(
                choices=[
                    ("VOORRAAD_MARGE", "Voorraad Marge"),
                    ("VOORRAAD_NIET_MARGE", "Voorraad niet-marge"),
                    ("VOORRAAD_BIJ_VERKOOP_MARGE", "Voorraadwaarde bij verkoop marge"),
                    (
                        "VOORRAAD_BIJ_VERKOOP_NIET_MARGE",
                        "Voorraadwaarde bij verkoop niet-marge",
                    ),
                    ("VERKOOP_MARGE", "Verkoop marge"),
                    ("VERKOOP_NIET_MARGE", "Verkoop niet-marge"),
                    ("DIRECTE_AFSCHRIJVING", "Directe afschrijving"),
                    ("AFSCHRIJVINGEN", "Afschrijvingen"),
                    ("BORGEN", "Borgen"),
                ],
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Soort",
            ),
        ),
        migrations.AlterField(
            model_name="ledger",
            name="moneybird_id",
            field=models.PositiveBigIntegerField(
                primary_key=True, serialize=False, verbose_name="MoneyBird-ID"
            ),
        ),
    ]
