# Generated by Django 4.0.6 on 2022-07-21 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_alter_asset_collection_alter_asset_listing_price_and_more"),
        ("accounting", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(
                        blank=True,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Moneybird ID",
                    ),
                ),
                (
                    "moneybird_json",
                    models.JSONField(null=True, verbose_name="JSON MoneyBird"),
                ),
                ("start_date", models.DateField(null=True, verbose_name="start date")),
                ("end_date", models.DateField(null=True, verbose_name="end date")),
                (
                    "cancelled_at",
                    models.DateField(null=True, verbose_name="cancelled at"),
                ),
                (
                    "reference",
                    models.CharField(max_length=200, verbose_name="Reference"),
                ),
                (
                    "frequency",
                    models.PositiveSmallIntegerField(
                        blank=True, default=1, null=True, verbose_name="frequency"
                    ),
                ),
                (
                    "frequency_type",
                    models.CharField(
                        choices=[
                            ("day", "day"),
                            ("week", "week"),
                            ("month", "month"),
                            ("quarter", "quarter"),
                            ("year", "year"),
                        ],
                        max_length=10,
                        verbose_name="frequency type",
                    ),
                ),
                (
                    "asset_id_field",
                    models.CharField(max_length=50, null=True, verbose_name="Asset-ID"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscriptions",
                        to="inventory.asset",
                        verbose_name="Asset",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscriptions",
                        to="accounting.contact",
                        verbose_name="Contact",
                    ),
                ),
                (
                    "document_style",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscriptions",
                        to="accounting.documentstyle",
                        verbose_name="Document style",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscription",
                        to="accounting.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "recurring_sales_invoice",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscriptions",
                        to="accounting.recurringsalesinvoice",
                        verbose_name="Recurring sales invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
                "ordering": ("-start_date",),
            },
        ),
    ]
