# Generated by Django 4.0.6 on 2022-07-06 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_assetcategory_assetlocationgroup_and_more"),
        ("accounting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentline",
            name="asset",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="document_lines",
                to="inventory.asset",
                verbose_name="Asset",
            ),
        ),
    ]
