# Generated by Django 4.0.3 on 2022-04-11 11:55
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_asset_options_alter_assetstate_options_and_more"),
        ("accounting", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_MB", models.IntegerField(verbose_name="Id MoneyBird")),
                ("json_MB", models.JSONField(verbose_name="JSON MoneyBird")),
                (
                    "kind",
                    models.CharField(
                        choices=[("PI", "Purchase Invoice"), ("RC", "Receipt")],
                        max_length=2,
                    ),
                ),
            ],
            options={
                "unique_together": {("id_MB", "kind")},
            },
        ),
        migrations.DeleteModel(
            name="Invoice",
        ),
        migrations.DeleteModel(
            name="Receipt",
        ),
    ]
