# Generated by Django 4.0.6 on 2022-07-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_alter_contact_moneybird_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesinvoice",
            name="prices_are_incl_tax",
            field=models.BooleanField(
                default=True, verbose_name="prices are incl. tax"
            ),
        ),
    ]
