# Generated by Django 4.0.6 on 2022-07-25 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_contact__synced_with_moneybird_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="estimate_workflow",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"active": True, "type": "EstimateWorkflow"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="estimate_workflow_contacts",
                to="accounting.workflow",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="invoice_workflow",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"active": True, "type": "InvoiceWorkflow"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_workflow_contacts",
                to="accounting.workflow",
            ),
        ),
    ]
