# Generated by Django 4.0.6 on 2022-07-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_estimatedocumentline_moneybird_version"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="estimatedocumentline",
            name="moneybird_version",
        ),
        migrations.AddField(
            model_name="estimate",
            name="moneybird_version",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="Moneybird version"
            ),
        ),
    ]
