# Generated by Django 4.0.4 on 2022-04-25 13:26
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_documentline_asset"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="link",
            field=models.URLField(
                blank=True, null=True, verbose_name="Moneybird document"
            ),
        ),
    ]
