# Generated by Django 4.0.6 on 2022-07-21 12:34

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import localflavor.generic.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="address_1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="address_2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="attention",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="bank_account",
            field=localflavor.generic.models.IBANField(
                blank=True,
                include_countries=(
                    "AT",
                    "BE",
                    "BG",
                    "CH",
                    "CY",
                    "CZ",
                    "DE",
                    "DK",
                    "EE",
                    "ES",
                    "FI",
                    "FR",
                    "GB",
                    "GI",
                    "GR",
                    "HR",
                    "HU",
                    "IE",
                    "IS",
                    "IT",
                    "LI",
                    "LT",
                    "LU",
                    "LV",
                    "MC",
                    "MT",
                    "NL",
                    "NO",
                    "PL",
                    "PT",
                    "RO",
                    "SE",
                    "SI",
                    "SK",
                    "SM",
                ),
                max_length=34,
                null=True,
                use_nordea_extensions=False,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="chamber_of_commerce",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="country",
            field=django_countries.fields.CountryField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact",
            name="customer_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="email_ubl",
            field=models.BooleanField(default=False, verbose_name="email ubl"),
        ),
        migrations.AddField(
            model_name="contact",
            name="estimate_workflow",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"active": True, "type": "EstimateWorkflow"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="estimate_workflow_contacts",
                to="accounting.workflow",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="invoice_workflow",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"active": True, "type": "InvoiceWorkflow"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_workflow_contacts",
                to="accounting.workflow",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="sales_invoices_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="send_estimates_to_attention",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="send_estimates_to_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="send_invoices_to_attention",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="send_invoices_to_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="sepa_bic",
            field=localflavor.generic.models.BICField(
                blank=True, max_length=11, null=True
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="sepa_iban",
            field=localflavor.generic.models.IBANField(
                blank=True,
                include_countries=(
                    "AT",
                    "BE",
                    "BG",
                    "CH",
                    "CY",
                    "CZ",
                    "DE",
                    "DK",
                    "EE",
                    "ES",
                    "FI",
                    "FR",
                    "GB",
                    "GI",
                    "GR",
                    "HR",
                    "HU",
                    "IE",
                    "IS",
                    "IT",
                    "LI",
                    "LT",
                    "LU",
                    "LV",
                    "MC",
                    "MT",
                    "NL",
                    "NO",
                    "PL",
                    "PT",
                    "RO",
                    "SE",
                    "SI",
                    "SK",
                    "SM",
                ),
                max_length=34,
                null=True,
                use_nordea_extensions=False,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="sepa_iban_account_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="sepa_mandate_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="sepa_mandate_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="sepa_sequence_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RCUR", "Recurring"),
                    ("FRST", "First"),
                    ("FNAL", "Final"),
                    ("OOFF", "One-off"),
                ],
                max_length=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="tax_number",
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="tax_number_valid",
            field=models.BooleanField(default=False, verbose_name="tax number active"),
        ),
        migrations.AddField(
            model_name="contact",
            name="zip_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
