# Generated by Django 4.0.6 on 2022-07-25 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0003_alter_contact_estimate_workflow_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="salesinvoicedocumentline",
            options={
                "ordering": ("-document__date", "row_order"),
                "verbose_name": "Sales invoice document line",
                "verbose_name_plural": "Sales invoice document lines",
            },
        ),
        migrations.RenameField(
            model_name="salesinvoice",
            old_name="invoice_date",
            new_name="date",
        ),
    ]
