# Generated by Django 4.0.4 on 2022-05-09 10:31
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0003_document_link_documentline_ledger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="kind",
            field=models.CharField(
                choices=[
                    ("PI", "Purchase Invoice"),
                    ("SI", "Sales Invoice"),
                    ("RC", "Receipt"),
                ],
                max_length=2,
            ),
        ),
    ]
