# Generated by Django 4.0.6 on 2022-07-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0003_remove_estimatedocumentline_moneybird_version_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estimate",
            name="date",
            field=models.DateField(null=True, verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="journaldocument",
            name="date",
            field=models.DateField(null=True, verbose_name="Date"),
        ),
    ]
