# Generated by Django 4.0.2 on 2022-03-21 13:16
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_asset_options_alter_assetstate_options_and_more"),
        ("accounting", "0003_alter_invoice_options_alter_receipt_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("json_MB", models.JSONField(verbose_name="JSON MoneyBird")),
                (
                    "kind",
                    models.CharField(
                        choices=[("IV", "Invoice"), ("RC", "Receipt")], max_length=2
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
            ],
        ),
        migrations.CreateModel(
            name="DocumentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("json_MB", models.JSONField(verbose_name="JSON MoneyBird")),
                ("price", models.FloatField(verbose_name="Price")),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.asset",
                        verbose_name="Asset",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="receipt",
            name="asset",
        ),
        migrations.DeleteModel(
            name="Invoice",
        ),
        migrations.DeleteModel(
            name="Receipt",
        ),
    ]
