# Generated by Django 4.0.6 on 2022-07-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0004_alter_salesinvoicedocumentline_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="Delete from Moneybird",
            ),
        ),
        migrations.AddField(
            model_name="documentstyle",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="Delete from Moneybird",
            ),
        ),
        migrations.AddField(
            model_name="estimate",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="Delete from Moneybird",
            ),
        ),
        migrations.AddField(
            model_name="estimatedocumentline",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="Delete from Moneybird",
            ),
        ),
        migrations.AddField(
            model_name="generaljournaldocument",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="Delete from Moneybird",
            ),
        ),
        migrations.AddField(
            model_name="journaldocumentline",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="Delete from Moneybird",
            ),
        ),
        migrations.AddField(
            model_name="ledgeraccount",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="Delete from Moneybird",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="Delete from Moneybird",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="Delete from Moneybird",
            ),
        ),
        migrations.AddField(
            model_name="purchasedocument",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="Delete from Moneybird",
            ),
        ),
        migrations.AddField(
            model_name="recurringsalesinvoice",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="Delete from Moneybird",
            ),
        ),
        migrations.AddField(
            model_name="recurringsalesinvoicedocumentline",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="Delete from Moneybird",
            ),
        ),
        migrations.AddField(
            model_name="salesinvoice",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="Delete from Moneybird",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="Delete from Moneybird",
            ),
        ),
        migrations.AddField(
            model_name="taxrate",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="Delete from Moneybird",
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="Delete from Moneybird",
            ),
        ),
    ]
