# Generated by Django 4.0.4 on 2022-05-09 11:27
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0004_alter_document_kind"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="link",
        ),
        migrations.AddField(
            model_name="document",
            name="url",
            field=models.URLField(
                blank=True, null=True, verbose_name="URL to Moneybird"
            ),
        ),
    ]
