# Generated by Django 4.0.6 on 2022-07-06 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0004_alter_estimate_date_alter_journaldocument_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="estimate",
            options={
                "ordering": ("-date",),
                "verbose_name": "Estimate",
                "verbose_name_plural": "Estimates",
            },
        ),
        migrations.AlterModelOptions(
            name="estimatedocumentline",
            options={
                "ordering": ("-document__date",),
                "verbose_name": "Estimate document line",
                "verbose_name_plural": "Estimate document lines",
            },
        ),
        migrations.AlterModelOptions(
            name="journaldocument",
            options={
                "ordering": ("-date",),
                "verbose_name": "Journal document",
                "verbose_name_plural": "Journal documents",
            },
        ),
        migrations.AlterModelOptions(
            name="journaldocumentline",
            options={
                "ordering": ("-document__date",),
                "verbose_name": "Journal document line",
                "verbose_name_plural": "Journal document lines",
            },
        ),
    ]
