# Generated by Django 4.0.6 on 2022-07-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0004_purchasedocumentline_prices_are_incl_tax"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchasedocumentline",
            name="prices_are_incl_tax",
        ),
        migrations.AddField(
            model_name="purchasedocument",
            name="prices_are_incl_tax",
            field=models.BooleanField(
                default=True, verbose_name="prices are incl. tax"
            ),
        ),
    ]
