# Generated by Django 4.0.2 on 2022-03-23 11:58
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0004_document_documentline_remove_receipt_asset_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="lines",
            field=models.ManyToManyField(to="accounting.DocumentLine"),
        ),
    ]
