# Generated by Django 4.0.6 on 2022-07-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0004_alter_ledger_account_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledger",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("non_current_assets", "non current assets"),
                    ("current_assets", "current assets"),
                    ("equity", "equity"),
                    ("provisions", "provisions"),
                    ("non_current_liabilities", "non current liabilities"),
                    ("current_liabilities", "current liabilities"),
                    ("revenue", "revenue"),
                    ("direct_costs", "direct costs"),
                    ("expenses", "expenses"),
                    ("other_income_expenses", "other income expenses"),
                ],
                max_length=100,
                null=True,
                verbose_name="Account type",
            ),
        ),
    ]
