# Generated by Django 4.0.4 on 2022-05-09 12:06
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0004_alter_document_kind"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="link",
        ),
    ]
