# Generated by Django 4.0.6 on 2022-07-06 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_assetcategory_assetlocationgroup_and_more"),
        ("accounting", "0005_alter_estimate_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringSalesInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Moneybird ID"
                    ),
                ),
                (
                    "moneybird_version",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Moneybird version"
                    ),
                ),
                (
                    "moneybird_json",
                    models.JSONField(null=True, verbose_name="JSON MoneyBird"),
                ),
                ("auto_send", models.BooleanField(verbose_name="Auto send")),
                ("active", models.BooleanField(verbose_name="Active")),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("day", "day"),
                            ("week", "week"),
                            ("month", "month"),
                            ("quarter", "quarter"),
                            ("year", "year"),
                        ],
                        max_length=10,
                        verbose_name="frequency",
                    ),
                ),
                ("start_date", models.DateField(null=True, verbose_name="start date")),
                (
                    "invoice_date",
                    models.DateField(null=True, verbose_name="invoice date"),
                ),
                ("last_date", models.DateField(null=True, verbose_name="last date")),
                (
                    "contact",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurring_sales_invoices",
                        to="accounting.contact",
                        verbose_name="Contact",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurring sales invoice",
                "verbose_name_plural": "Recurring sales invoices",
                "ordering": ("-start_date",),
            },
        ),
        migrations.CreateModel(
            name="RecurringSalesInvoiceDocumentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Moneybird ID"
                    ),
                ),
                (
                    "moneybird_json",
                    models.JSONField(null=True, verbose_name="JSON MoneyBird"),
                ),
                (
                    "asset_id_field",
                    models.CharField(max_length=50, null=True, verbose_name="Asset-ID"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurring_sales_invoice_document_lines",
                        to="inventory.asset",
                        verbose_name="Asset",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_lines",
                        to="accounting.recurringsalesinvoice",
                        verbose_name="Document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurring sales invoice document line",
                "verbose_name_plural": "Recurring sales invoice document lines",
                "ordering": ("-document__start_date",),
            },
        ),
    ]
