# Generated by Django 4.0.2 on 2022-03-23 12:03
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0005_document_lines"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="date",
        ),
        migrations.RemoveField(
            model_name="document",
            name="lines",
        ),
        migrations.DeleteModel(
            name="DocumentLine",
        ),
    ]
