# Generated by Django 4.0.2 on 2022-03-23 19:09
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0006_remove_document_date_remove_document_lines_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="kind",
            field=models.CharField(
                choices=[("PI", "Purchase Invoice"), ("RC", "Receipt")], max_length=2
            ),
        ),
    ]
