# Generated by Django 4.0.6 on 2022-07-27 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0006_alter_project_options_alter_taxrate_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={},
        ),
        migrations.AlterModelOptions(
            name="taxrate",
            options={},
        ),
    ]
