# Generated by Django 4.0.6 on 2022-07-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0006_journaldocument_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="company_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="company name"
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="email"
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="voornaam"
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="achternaam"
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="sepa_active",
            field=models.BooleanField(default=False, verbose_name="sepa active"),
        ),
    ]
