# Generated by Django 4.0.6 on 2022-07-23 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0006_alter_contact_moneybird_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
        migrations.AlterField(
            model_name="product",
            name="ledger_account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.ledgeraccount",
                verbose_name="ledger account",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="tax_rate",
            field=models.ForeignKey(
                limit_choices_to={"active": True, "type": "sales_invoice"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.taxrate",
            ),
        ),
        migrations.AlterField(
            model_name="purchasedocument",
            name="reference",
            field=models.CharField(max_length=255, null=True, verbose_name="reference"),
        ),
    ]
