# Generated by Django 4.0.4 on 2022-05-18 13:18
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0006_alter_documentline_ledger"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentline",
            name="asset_id_field",
            field=models.CharField(max_length=50, null=True, verbose_name="Asset Id"),
        ),
    ]
