# Generated by Django 4.0.6 on 2022-07-06 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0006_recurringsalesinvoice_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Moneybird ID"
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Workflow",
                "verbose_name_plural": "Workflows",
            },
        ),
        migrations.AddField(
            model_name="estimate",
            name="workflow",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounting.ledger",
                verbose_name="Workflow",
            ),
        ),
        migrations.AddField(
            model_name="journaldocument",
            name="workflow",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounting.ledger",
                verbose_name="Workflow",
            ),
        ),
        migrations.AddField(
            model_name="recurringsalesinvoice",
            name="workflow",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounting.ledger",
                verbose_name="Workflow",
            ),
        ),
    ]
