# Generated by Django 3.2.12 on 2022-04-06 12:26
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0007_alter_document_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="id_MB",
            field=models.IntegerField(default=0, verbose_name="Id MoneyBird"),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="document",
            unique_together={("id_MB", "kind")},
        ),
    ]
