# Generated by Django 4.0.6 on 2022-07-06 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounting",
            "0007_workflow_estimate_workflow_journaldocument_workflow_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="estimate",
            name="workflow",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounting.workflow",
                verbose_name="Workflow",
            ),
        ),
        migrations.AlterField(
            model_name="journaldocument",
            name="workflow",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounting.workflow",
                verbose_name="Workflow",
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoice",
            name="workflow",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounting.workflow",
                verbose_name="Workflow",
            ),
        ),
    ]
