# Generated by Django 4.0.4 on 2022-05-24 19:44
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0007_documentline_asset_id_field"),
    ]

    operations = [
        migrations.RenameField(
            model_name="document",
            old_name="id_MB",
            new_name="moneybird_id",
        ),
        migrations.RenameField(
            model_name="document",
            old_name="json_MB",
            new_name="moneybird_json",
        ),
        migrations.RenameField(
            model_name="documentline",
            old_name="json_MB",
            new_name="moneybird_json",
        ),
        migrations.AlterUniqueTogether(
            name="document",
            unique_together={("moneybird_id", "kind")},
        ),
    ]
