# Generated by Django 4.0.6 on 2022-07-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0007_contact_company_name_contact_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="moneybird_id",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="Moneybird ID"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="moneybird_version",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="Moneybird version"
            ),
        ),
        migrations.AlterField(
            model_name="documentline",
            name="moneybird_id",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="Moneybird ID"
            ),
        ),
        migrations.AlterField(
            model_name="journaldocument",
            name="moneybird_id",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="Moneybird ID"
            ),
        ),
        migrations.AlterField(
            model_name="journaldocument",
            name="moneybird_version",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="Moneybird version"
            ),
        ),
        migrations.AlterField(
            model_name="ledger",
            name="moneybird_id",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="Moneybird ID"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="moneybird_id",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="Moneybird ID"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="moneybird_id",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="Moneybird ID"
            ),
        ),
    ]
