# Generated by Django 4.0.6 on 2022-07-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0008_alter_contact_moneybird_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="moneybird_id",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, unique=True, verbose_name="Moneybird ID"
            ),
        ),
        migrations.AlterField(
            model_name="documentstyle",
            name="moneybird_id",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, unique=True, verbose_name="Moneybird ID"
            ),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="moneybird_id",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, unique=True, verbose_name="Moneybird ID"
            ),
        ),
        migrations.AlterField(
            model_name="estimatedocumentline",
            name="moneybird_id",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, unique=True, verbose_name="Moneybird ID"
            ),
        ),
        migrations.AlterField(
            model_name="generaljournaldocument",
            name="moneybird_id",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, unique=True, verbose_name="Moneybird ID"
            ),
        ),
        migrations.AlterField(
            model_name="journaldocumentline",
            name="moneybird_id",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, unique=True, verbose_name="Moneybird ID"
            ),
        ),
        migrations.AlterField(
            model_name="ledgeraccount",
            name="moneybird_id",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, unique=True, verbose_name="Moneybird ID"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="moneybird_id",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, unique=True, verbose_name="Moneybird ID"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="moneybird_id",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, unique=True, verbose_name="Moneybird ID"
            ),
        ),
        migrations.AlterField(
            model_name="purchasedocument",
            name="moneybird_id",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, unique=True, verbose_name="Moneybird ID"
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoice",
            name="moneybird_id",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, unique=True, verbose_name="Moneybird ID"
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoicedocumentline",
            name="moneybird_id",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, unique=True, verbose_name="Moneybird ID"
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="moneybird_id",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, unique=True, verbose_name="Moneybird ID"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="moneybird_id",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, unique=True, verbose_name="Moneybird ID"
            ),
        ),
        migrations.AlterField(
            model_name="taxrate",
            name="moneybird_id",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, unique=True, verbose_name="Moneybird ID"
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="moneybird_id",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, unique=True, verbose_name="Moneybird ID"
            ),
        ),
    ]
