# Generated by Django 4.0.6 on 2022-07-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0008_alter_contact_moneybird_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="moneybird_json",
            field=models.JSONField(null=True, verbose_name="JSON MoneyBird"),
        ),
        migrations.AlterField(
            model_name="documentline",
            name="moneybird_json",
            field=models.JSONField(null=True, verbose_name="JSON MoneyBird"),
        ),
        migrations.AlterField(
            model_name="journaldocument",
            name="moneybird_json",
            field=models.JSONField(null=True, verbose_name="JSON MoneyBird"),
        ),
        migrations.AlterField(
            model_name="product",
            name="moneybird_json",
            field=models.JSONField(null=True, verbose_name="JSON MoneyBird"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="moneybird_json",
            field=models.JSONField(null=True, verbose_name="JSON MoneyBird"),
        ),
    ]
