# Generated by Django 4.0.4 on 2022-05-25 12:39
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0008_rename_id_mb_document_moneybird_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ledger",
            fields=[
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(
                        primary_key=True, serialize=False, verbose_name="Id MoneyBird"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("VOORRAAD_MARGE", "Voorraad Marge"),
                            ("VOORRAAD_NIET_MARGE", "Voorraad niet-marge"),
                            (
                                "VOORRAAD_BIJ_VERKOOP_MARGE",
                                "Voorraadwaarde bij verkoop marge",
                            ),
                            (
                                "VOORRAAD_BIJ_VERKOOP_NIET_MARGE",
                                "Voorraadwaarde bij verkoop niet-marge",
                            ),
                            ("VERKOOP_MARGE", "Verkoop marge"),
                            ("VERKOOP_NIET_MARGE", "Verkoop niet-marge"),
                            ("DIRECTE_AFSCHRIJVING", "Directe afschrijving"),
                            ("AFSCHRIJVINGEN", "Afschrijvingen"),
                            ("BORGEN", "Borgen"),
                        ],
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="documentline",
            name="ledger",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="accounting.ledger"
            ),
        ),
    ]
