# Generated by Django 4.0.4 on 2022-05-27 11:50
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0009_ledger_alter_documentline_ledger"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentline",
            name="price",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
            preserve_default=False,
        ),
    ]
