# Generated by Django 4.0.6 on 2022-07-23 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0010_alter_salesinvoice_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="salesinvoice",
            options={
                "ordering": ("-invoice_date", "invoice_id", "draft_id"),
                "verbose_name": "Sales invoice",
                "verbose_name_plural": "Sales invoices",
            },
        ),
    ]
