# Generated by Django 4.0.6 on 2022-07-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0011_alter_estimate_workflow_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estimate",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=19, null=True, verbose_name="total price"
            ),
        ),
        migrations.AlterField(
            model_name="journaldocument",
            name="total_paid",
            field=models.DecimalField(
                decimal_places=2, max_digits=19, null=True, verbose_name="total paid"
            ),
        ),
        migrations.AlterField(
            model_name="journaldocument",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=19, null=True, verbose_name="total price"
            ),
        ),
        migrations.AlterField(
            model_name="journaldocument",
            name="total_unpaid",
            field=models.DecimalField(
                decimal_places=2, max_digits=19, null=True, verbose_name="total unpaid"
            ),
        ),
        migrations.AlterField(
            model_name="journaldocumentline",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=19, verbose_name="Prijs"
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoice",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=19, null=True, verbose_name="total price"
            ),
        ),
    ]
