# Generated by Django 4.0.6 on 2022-07-06 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0013_alter_estimate_workflow_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journaldocumentline",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journal_document_lines",
                to="accounting.journaldocument",
                verbose_name="Document",
            ),
        ),
    ]
