# Generated by Django 4.0.6 on 2022-07-23 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0014_alter_salesinvoice_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="salesinvoice",
            options={
                "ordering": ("-draft_id", "-invoice_id"),
                "verbose_name": "Sales invoice",
                "verbose_name_plural": "Sales invoices",
            },
        ),
    ]
