# Generated by Django 4.0.6 on 2022-07-06 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_assetcategory_assetlocationgroup_and_more"),
        ("accounting", "0014_alter_journaldocumentline_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journaldocumentline",
            name="asset",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="journal_document_lines",
                to="inventory.asset",
                verbose_name="Asset",
            ),
        ),
        migrations.AlterField(
            model_name="journaldocumentline",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_lines",
                to="accounting.journaldocument",
                verbose_name="Document",
            ),
        ),
    ]
