# Generated by Django 4.0.6 on 2022-07-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0015_alter_journaldocumentline_asset_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledger",
            name="is_margin",
            field=models.BooleanField(
                default=False,
                help_text="All assets on this ledger account are margin assets.",
            ),
        ),
        migrations.AddField(
            model_name="ledger",
            name="is_sales",
            field=models.BooleanField(
                default=False, help_text="Ledger account is used for selling assets."
            ),
        ),
    ]
