# Generated by Django 4.0.6 on 2022-07-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0015_alter_salesinvoice_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesinvoicedocumentline",
            name="row_order",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="row order"
            ),
        ),
    ]
