# Generated by Django 4.0.6 on 2022-07-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0016_alter_salesinvoicedocumentline_row_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journaldocumentline",
            name="total_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=19,
                null=True,
                verbose_name="Total amount",
            ),
        ),
    ]
