# Generated by Django 4.0.6 on 2022-07-24 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_alter_asset_collection_alter_asset_listing_price_and_more"),
        ("accounting", "0017_alter_journaldocumentline_total_amount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recurringsalesinvoicedocumentline",
            options={
                "ordering": ("-document__start_date", "row_order"),
                "verbose_name": "Recurring sales invoice document line",
                "verbose_name_plural": "Recurring sales invoice document lines",
            },
        ),
        migrations.RemoveField(
            model_name="recurringsalesinvoice",
            name="moneybird_json",
        ),
        migrations.RemoveField(
            model_name="recurringsalesinvoicedocumentline",
            name="moneybird_json",
        ),
        migrations.AddField(
            model_name="recurringsalesinvoice",
            name="desired_count",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="desired count"
            ),
        ),
        migrations.AddField(
            model_name="recurringsalesinvoice",
            name="discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                verbose_name="discount",
            ),
        ),
        migrations.AddField(
            model_name="recurringsalesinvoice",
            name="document_style",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.documentstyle",
                verbose_name="Document style",
            ),
        ),
        migrations.AddField(
            model_name="recurringsalesinvoice",
            name="first_due_interval",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="first due interval"
            ),
        ),
        migrations.AddField(
            model_name="recurringsalesinvoice",
            name="frequency_type",
            field=models.CharField(
                choices=[
                    ("day", "day"),
                    ("week", "week"),
                    ("month", "month"),
                    ("quarter", "quarter"),
                    ("year", "year"),
                ],
                default=1,
                max_length=10,
                verbose_name="frequency type",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recurringsalesinvoice",
            name="has_desired_count",
            field=models.BooleanField(default=False, verbose_name="has desired count"),
        ),
        migrations.AddField(
            model_name="recurringsalesinvoice",
            name="mergeable",
            field=models.BooleanField(default=True, verbose_name="mergeable"),
        ),
        migrations.AddField(
            model_name="recurringsalesinvoice",
            name="prices_are_incl_tax",
            field=models.BooleanField(
                default=True, verbose_name="prices are incl. tax"
            ),
        ),
        migrations.AddField(
            model_name="recurringsalesinvoice",
            name="reference",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="reference"
            ),
        ),
        migrations.AddField(
            model_name="recurringsalesinvoicedocumentline",
            name="amount",
            field=models.CharField(
                blank=True,
                default="1 x",
                max_length=10,
                null=True,
                verbose_name="Amount",
            ),
        ),
        migrations.AddField(
            model_name="recurringsalesinvoicedocumentline",
            name="amount_decimal",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=19,
                null=True,
                verbose_name="Amount (decimal)",
            ),
        ),
        migrations.AddField(
            model_name="recurringsalesinvoicedocumentline",
            name="ledger_account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.ledgeraccount",
                verbose_name="Ledger account",
            ),
        ),
        migrations.AddField(
            model_name="recurringsalesinvoicedocumentline",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=19, verbose_name="price"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recurringsalesinvoicedocumentline",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.product",
                verbose_name="Product",
            ),
        ),
        migrations.AddField(
            model_name="recurringsalesinvoicedocumentline",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.project",
                verbose_name="Project",
            ),
        ),
        migrations.AddField(
            model_name="recurringsalesinvoicedocumentline",
            name="row_order",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="row order"
            ),
        ),
        migrations.AddField(
            model_name="recurringsalesinvoicedocumentline",
            name="tax_rate",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.taxrate",
                verbose_name="Tax rate",
            ),
        ),
        migrations.AddField(
            model_name="recurringsalesinvoicedocumentline",
            name="total_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=19,
                null=True,
                verbose_name="Total amount",
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoice",
            name="frequency",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoice",
            name="invoice_date",
            field=models.DateField(blank=True, null=True, verbose_name="invoice date"),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoice",
            name="workflow",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"active": True, "type": "InvoiceWorkflow"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.workflow",
                verbose_name="Workflow",
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoicedocumentline",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recurring_sales_invoice_lines",
                to="inventory.asset",
                verbose_name="Asset",
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoicedocumentline",
            name="asset_id_field",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Asset-ID"
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoicedocumentline",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
    ]
