# Generated by Django 4.0.6 on 2022-07-24 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0018_alter_recurringsalesinvoicedocumentline_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recurringsalesinvoice",
            name="document_style",
        ),
    ]
