# Generated by Django 4.0.6 on 2022-07-12 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0018_alter_journaldocumentline_ledger"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Moneybird ID"
                    ),
                ),
                (
                    "moneybird_json",
                    models.JSONField(null=True, verbose_name="JSON MoneyBird"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TaxRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Moneybird ID"
                    ),
                ),
                (
                    "moneybird_json",
                    models.JSONField(null=True, verbose_name="JSON MoneyBird"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="journaldocumentline",
            name="amount",
            field=models.CharField(
                blank=True,
                default="1 x",
                max_length=10,
                null=True,
                verbose_name="Amount",
            ),
        ),
        migrations.AddField(
            model_name="journaldocumentline",
            name="description",
            field=models.TextField(default=" ", verbose_name="Description"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="journaldocumentline",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.product",
                verbose_name="Product",
            ),
        ),
        migrations.AddField(
            model_name="journaldocumentline",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.project",
                verbose_name="Project",
            ),
        ),
        migrations.AddField(
            model_name="journaldocumentline",
            name="tax_rate",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.taxrate",
                verbose_name="Tax rate",
            ),
        ),
    ]
