# Generated by Django 4.0.6 on 2022-07-13 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_remove_asset_moneybird_state"),
        ("accounting", "0019_project_taxrate_journaldocumentline_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journaldocumentline",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="journal_document_lines",
                to="inventory.asset",
                verbose_name="Asset",
            ),
        ),
        migrations.AlterField(
            model_name="journaldocumentline",
            name="asset_id_field",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Asset-ID"
            ),
        ),
        migrations.AlterField(
            model_name="journaldocumentline",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="journaldocumentline",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.project",
                verbose_name="Project",
            ),
        ),
    ]
