# Generated by Django 4.0.6 on 2022-07-24 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0019_remove_recurringsalesinvoice_document_style"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recurringsalesinvoice",
            name="desired_count",
        ),
        migrations.RemoveField(
            model_name="recurringsalesinvoice",
            name="has_desired_count",
        ),
    ]
