# Generated by Django 4.0.6 on 2022-07-24 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0020_remove_recurringsalesinvoice_desired_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recurringsalesinvoice",
            name="mergeable",
        ),
    ]
