# Generated by Django 4.0.6 on 2022-07-13 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0020_alter_journaldocumentline_asset_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ledger",
            name="ledger_kind",
        ),
    ]
