# Generated by Django 4.0.6 on 2022-07-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0021_remove_recurringsalesinvoice_mergeable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recurringsalesinvoice",
            name="auto_send",
            field=models.BooleanField(default=True, verbose_name="Auto send"),
        ),
    ]
