# Generated by Django 4.0.6 on 2022-07-13 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_remove_asset_purchasing_value_and_more"),
        ("accounting", "0021_remove_ledger_ledger_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Moneybird ID"
                    ),
                ),
                (
                    "moneybird_json",
                    models.JSONField(null=True, verbose_name="JSON MoneyBird"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="subscription",
            name="asset",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscriptions",
                to="inventory.asset",
                verbose_name="Asset",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="asset_id_field",
            field=models.CharField(max_length=50, null=True, verbose_name="Asset-ID"),
        ),
        migrations.AddField(
            model_name="subscription",
            name="cancelled_at",
            field=models.DateField(null=True, verbose_name="cancelled at"),
        ),
        migrations.AddField(
            model_name="subscription",
            name="contact",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscriptions",
                to="accounting.contact",
                verbose_name="Contact",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="end_date",
            field=models.DateField(null=True, verbose_name="end date"),
        ),
        migrations.AddField(
            model_name="subscription",
            name="frequency",
            field=models.PositiveSmallIntegerField(
                blank=True, default=1, null=True, verbose_name="frequency"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="frequency_type",
            field=models.CharField(
                choices=[
                    ("day", "day"),
                    ("week", "week"),
                    ("month", "month"),
                    ("quarter", "quarter"),
                    ("year", "year"),
                ],
                default=1,
                max_length=10,
                verbose_name="frequency type",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscription",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscription",
                to="accounting.product",
                verbose_name="Product",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="reference",
            field=models.CharField(default=1, max_length=200, verbose_name="Reference"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscription",
            name="start_date",
            field=models.DateField(null=True, verbose_name="start date"),
        ),
        migrations.AddField(
            model_name="subscription",
            name="document_style",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscriptions",
                to="accounting.documentstyle",
                verbose_name="Document style",
            ),
        ),
    ]
