# Generated by Django 4.0.6 on 2022-07-24 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0022_alter_recurringsalesinvoice_auto_send"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recurringsalesinvoicedocumentline",
            name="tax_rate",
            field=models.ForeignKey(
                limit_choices_to={"active": True, "type": "sales_invoice"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.taxrate",
                verbose_name="Tax rate",
            ),
        ),
    ]
