# Generated by Django 4.0.6 on 2022-07-13 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0022_documentstyle_subscription_asset_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="recurring_sales_invoice",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscriptions",
                to="accounting.recurringsalesinvoice",
                verbose_name="Recurring sales invoice",
            ),
        ),
    ]
