# Generated by Django 4.0.6 on 2022-07-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0023_alter_recurringsalesinvoicedocumentline_tax_rate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="document_style",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="moneybird_json",
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoice",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
    ]
