# Generated by Django 4.0.6 on 2022-07-24 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_alter_asset_collection_alter_asset_listing_price_and_more"),
        ("accounting", "0024_remove_subscription_document_style_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="estimate",
            options={
                "ordering": ("-draft_id", "-estimate_id"),
                "verbose_name": "Estimate",
                "verbose_name_plural": "Estimates",
            },
        ),
        migrations.AlterModelOptions(
            name="estimatedocumentline",
            options={
                "ordering": ("-document__estimate_date", "row_order"),
                "verbose_name": "Estimate document line",
                "verbose_name_plural": "Estimate document lines",
            },
        ),
        migrations.RemoveField(
            model_name="estimate",
            name="date",
        ),
        migrations.RemoveField(
            model_name="estimate",
            name="moneybird_json",
        ),
        migrations.RemoveField(
            model_name="estimatedocumentline",
            name="moneybird_json",
        ),
        migrations.AddField(
            model_name="estimate",
            name="accepted_at",
            field=models.DateField(null=True, verbose_name="accepted at"),
        ),
        migrations.AddField(
            model_name="estimate",
            name="archived_at",
            field=models.DateField(null=True, verbose_name="archived at"),
        ),
        migrations.AddField(
            model_name="estimate",
            name="discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                verbose_name="discount",
            ),
        ),
        migrations.AddField(
            model_name="estimate",
            name="document_style",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.documentstyle",
                verbose_name="Document style",
            ),
        ),
        migrations.AddField(
            model_name="estimate",
            name="draft_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="draft id"
            ),
        ),
        migrations.AddField(
            model_name="estimate",
            name="due_date",
            field=models.DateField(blank=True, null=True, verbose_name="due date"),
        ),
        migrations.AddField(
            model_name="estimate",
            name="estimate_date",
            field=models.DateField(blank=True, null=True, verbose_name="estimate date"),
        ),
        migrations.AddField(
            model_name="estimate",
            name="estimate_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="estimate id"
            ),
        ),
        migrations.AddField(
            model_name="estimate",
            name="original_estimate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.estimate",
                verbose_name="original estimate",
            ),
        ),
        migrations.AddField(
            model_name="estimate",
            name="post_text",
            field=models.TextField(null=True, verbose_name="post text"),
        ),
        migrations.AddField(
            model_name="estimate",
            name="pre_text",
            field=models.TextField(null=True, verbose_name="pre text"),
        ),
        migrations.AddField(
            model_name="estimate",
            name="prices_are_incl_tax",
            field=models.BooleanField(
                default=True, verbose_name="prices are incl. tax"
            ),
        ),
        migrations.AddField(
            model_name="estimate",
            name="public_view_code",
            field=models.CharField(
                max_length=10, null=True, verbose_name="public view code"
            ),
        ),
        migrations.AddField(
            model_name="estimate",
            name="reference",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="reference"
            ),
        ),
        migrations.AddField(
            model_name="estimate",
            name="rejected_at",
            field=models.DateField(null=True, verbose_name="rejected at"),
        ),
        migrations.AddField(
            model_name="estimate",
            name="sent_at",
            field=models.DateField(null=True, verbose_name="sent at"),
        ),
        migrations.AddField(
            model_name="estimate",
            name="url",
            field=models.URLField(null=True, verbose_name="url"),
        ),
        migrations.AddField(
            model_name="estimatedocumentline",
            name="amount",
            field=models.CharField(
                blank=True,
                default="1 x",
                max_length=10,
                null=True,
                verbose_name="Amount",
            ),
        ),
        migrations.AddField(
            model_name="estimatedocumentline",
            name="amount_decimal",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=19,
                null=True,
                verbose_name="Amount (decimal)",
            ),
        ),
        migrations.AddField(
            model_name="estimatedocumentline",
            name="ledger_account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.ledgeraccount",
                verbose_name="Ledger account",
            ),
        ),
        migrations.AddField(
            model_name="estimatedocumentline",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=19, verbose_name="price"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="estimatedocumentline",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.product",
                verbose_name="Product",
            ),
        ),
        migrations.AddField(
            model_name="estimatedocumentline",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.project",
                verbose_name="Project",
            ),
        ),
        migrations.AddField(
            model_name="estimatedocumentline",
            name="row_order",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="row order"
            ),
        ),
        migrations.AddField(
            model_name="estimatedocumentline",
            name="tax_rate",
            field=models.ForeignKey(
                limit_choices_to={"active": True, "type": "sales_invoice"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.taxrate",
                verbose_name="Tax rate",
            ),
        ),
        migrations.AddField(
            model_name="estimatedocumentline",
            name="total_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=19,
                null=True,
                verbose_name="Total amount",
            ),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="workflow",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"active": True, "type": "EstimateWorkflow"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.workflow",
                verbose_name="Workflow",
            ),
        ),
        migrations.AlterField(
            model_name="estimatedocumentline",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="estimate_lines",
                to="inventory.asset",
                verbose_name="Asset",
            ),
        ),
        migrations.AlterField(
            model_name="estimatedocumentline",
            name="asset_id_field",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Asset-ID"
            ),
        ),
        migrations.AlterField(
            model_name="estimatedocumentline",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
    ]
