# Generated by Django 4.0.6 on 2022-07-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0025_alter_estimate_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estimate",
            name="accepted_at",
            field=models.DateField(blank=True, null=True, verbose_name="accepted at"),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="archived_at",
            field=models.DateField(blank=True, null=True, verbose_name="archived at"),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="post_text",
            field=models.TextField(blank=True, null=True, verbose_name="post text"),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="pre_text",
            field=models.TextField(blank=True, null=True, verbose_name="pre text"),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="rejected_at",
            field=models.DateField(blank=True, null=True, verbose_name="rejected at"),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="sent_at",
            field=models.DateField(blank=True, null=True, verbose_name="sent at"),
        ),
    ]
