# Generated by Django 4.0.6 on 2022-07-25 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0026_alter_estimate_accepted_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="estimatedocumentline",
            name="asset",
        ),
        migrations.RemoveField(
            model_name="estimatedocumentline",
            name="asset_id_field",
        ),
        migrations.RemoveField(
            model_name="journaldocumentline",
            name="asset",
        ),
        migrations.RemoveField(
            model_name="journaldocumentline",
            name="asset_id_field",
        ),
        migrations.RemoveField(
            model_name="recurringsalesinvoicedocumentline",
            name="asset",
        ),
        migrations.RemoveField(
            model_name="recurringsalesinvoicedocumentline",
            name="asset_id_field",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="asset",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="asset_id_field",
        ),
    ]
