# Generated by Django 4.1.7 on 2023-05-03 09:49

import django.db.models.deletion
import django_countries.fields
import localflavor.generic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, unique=True, verbose_name="Moneybird ID"
                    ),
                ),
                (
                    "_synced_with_moneybird",
                    models.BooleanField(
                        default=False,
                        help_text="Latest changes have been pushed to Moneybird.",
                        verbose_name="Synced with Moneybird",
                    ),
                ),
                (
                    "_delete_from_moneybird",
                    models.BooleanField(
                        default=False,
                        help_text="Delete this object from Moneybird when syncing.",
                        verbose_name="To be deleted from Moneybird",
                    ),
                ),
                (
                    "moneybird_version",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Moneybird version"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="company name",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="last name"
                    ),
                ),
                (
                    "address_1",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="address 1"
                    ),
                ),
                (
                    "address_2",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="address 2"
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="zip code"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="city"
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        default="NL", max_length=2, verbose_name="country"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="phone"
                    ),
                ),
                (
                    "customer_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="customer id",
                    ),
                ),
                (
                    "tax_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="tax number"
                    ),
                ),
                (
                    "chamber_of_commerce",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="chamber of commerce",
                    ),
                ),
                (
                    "bank_account",
                    localflavor.generic.models.IBANField(
                        blank=True,
                        include_countries=(
                            "AT",
                            "BE",
                            "BG",
                            "CH",
                            "CY",
                            "CZ",
                            "DE",
                            "DK",
                            "EE",
                            "ES",
                            "FI",
                            "FR",
                            "GB",
                            "GI",
                            "GR",
                            "HR",
                            "HU",
                            "IE",
                            "IS",
                            "IT",
                            "LI",
                            "LT",
                            "LU",
                            "LV",
                            "MC",
                            "MT",
                            "NL",
                            "NO",
                            "PL",
                            "PT",
                            "RO",
                            "SE",
                            "SI",
                            "SK",
                            "SM",
                        ),
                        max_length=34,
                        null=True,
                        use_nordea_extensions=False,
                        verbose_name="bank account",
                    ),
                ),
                (
                    "attention",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="attention"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="email"
                    ),
                ),
                (
                    "email_ubl",
                    models.BooleanField(default=False, verbose_name="email ubl"),
                ),
                (
                    "send_invoices_to_attention",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="send invoices to (attention)",
                    ),
                ),
                (
                    "send_invoices_to_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="send invoices to (email)",
                    ),
                ),
                (
                    "send_estimates_to_attention",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="send estimates to (attention)",
                    ),
                ),
                (
                    "send_estimates_to_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="send estimates to (email)",
                    ),
                ),
                (
                    "sepa_active",
                    models.BooleanField(default=False, verbose_name="SEPA active"),
                ),
                (
                    "sepa_iban",
                    localflavor.generic.models.IBANField(
                        blank=True,
                        include_countries=(
                            "AT",
                            "BE",
                            "BG",
                            "CH",
                            "CY",
                            "CZ",
                            "DE",
                            "DK",
                            "EE",
                            "ES",
                            "FI",
                            "FR",
                            "GB",
                            "GI",
                            "GR",
                            "HR",
                            "HU",
                            "IE",
                            "IS",
                            "IT",
                            "LI",
                            "LT",
                            "LU",
                            "LV",
                            "MC",
                            "MT",
                            "NL",
                            "NO",
                            "PL",
                            "PT",
                            "RO",
                            "SE",
                            "SI",
                            "SK",
                            "SM",
                        ),
                        max_length=34,
                        null=True,
                        use_nordea_extensions=False,
                        verbose_name="SEPA IBAN",
                    ),
                ),
                (
                    "sepa_iban_account_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="SEPA IBAN account name",
                    ),
                ),
                (
                    "sepa_bic",
                    localflavor.generic.models.BICField(
                        blank=True, max_length=11, null=True, verbose_name="SEPA BIC"
                    ),
                ),
                (
                    "sepa_mandate_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="SEPA mandate id",
                    ),
                ),
                (
                    "sepa_mandate_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="SEPA mandate date"
                    ),
                ),
                (
                    "sepa_sequence_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RCUR", "Recurring"),
                            ("FRST", "First"),
                            ("FNAL", "Final"),
                            ("OOFF", "One-off"),
                        ],
                        max_length=4,
                        null=True,
                        verbose_name="SEPA sequence type",
                    ),
                ),
                (
                    "tax_number_valid",
                    models.BooleanField(default=False, verbose_name="tax number valid"),
                ),
                (
                    "sales_invoices_url",
                    models.URLField(
                        blank=True,
                        max_length=2048,
                        null=True,
                        verbose_name="sales invoices url",
                    ),
                ),
            ],
            options={
                "verbose_name": "contact",
                "verbose_name_plural": "contacts",
                "ordering": ["company_name", "last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="DocumentStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, unique=True, verbose_name="Moneybird ID"
                    ),
                ),
                (
                    "_synced_with_moneybird",
                    models.BooleanField(
                        default=False,
                        help_text="Latest changes have been pushed to Moneybird.",
                        verbose_name="Synced with Moneybird",
                    ),
                ),
                (
                    "_delete_from_moneybird",
                    models.BooleanField(
                        default=False,
                        help_text="Delete this object from Moneybird when syncing.",
                        verbose_name="To be deleted from Moneybird",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("default", models.BooleanField(default=True, verbose_name="default")),
            ],
            options={
                "verbose_name": "document style",
                "verbose_name_plural": "document styles",
            },
        ),
        migrations.CreateModel(
            name="Estimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, unique=True, verbose_name="Moneybird ID"
                    ),
                ),
                (
                    "_synced_with_moneybird",
                    models.BooleanField(
                        default=False,
                        help_text="Latest changes have been pushed to Moneybird.",
                        verbose_name="Synced with Moneybird",
                    ),
                ),
                (
                    "_delete_from_moneybird",
                    models.BooleanField(
                        default=False,
                        help_text="Delete this object from Moneybird when syncing.",
                        verbose_name="To be deleted from Moneybird",
                    ),
                ),
                (
                    "moneybird_version",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Moneybird version"
                    ),
                ),
                (
                    "estimate_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="estimate id",
                    ),
                ),
                (
                    "draft_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="draft id"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("open", "open"),
                            ("late", "late"),
                            ("accepted", "accepted"),
                            ("rejected", "rejected"),
                            ("billed", "billed"),
                            ("archived", "archived"),
                            ("scheduled", "scheduled"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="state",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=19,
                        null=True,
                        verbose_name="total price",
                    ),
                ),
                (
                    "estimate_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="estimate date"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="due date"),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="reference"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="discount",
                    ),
                ),
                (
                    "sent_at",
                    models.DateField(blank=True, null=True, verbose_name="sent at"),
                ),
                (
                    "accepted_at",
                    models.DateField(blank=True, null=True, verbose_name="accepted at"),
                ),
                (
                    "rejected_at",
                    models.DateField(blank=True, null=True, verbose_name="rejected at"),
                ),
                (
                    "archived_at",
                    models.DateField(blank=True, null=True, verbose_name="archived at"),
                ),
                (
                    "public_view_code",
                    models.CharField(
                        max_length=10, null=True, verbose_name="public view code"
                    ),
                ),
                (
                    "url",
                    models.URLField(max_length=2048, null=True, verbose_name="url"),
                ),
                (
                    "pre_text",
                    models.TextField(blank=True, null=True, verbose_name="pre text"),
                ),
                (
                    "post_text",
                    models.TextField(blank=True, null=True, verbose_name="post text"),
                ),
                (
                    "prices_are_incl_tax",
                    models.BooleanField(
                        default=True, verbose_name="prices are incl. tax"
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estimates",
                        to="accounting.contact",
                        verbose_name="contact",
                    ),
                ),
                (
                    "document_style",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.documentstyle",
                        verbose_name="document style",
                    ),
                ),
                (
                    "original_estimate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.estimate",
                        verbose_name="original estimate",
                    ),
                ),
            ],
            options={
                "verbose_name": "estimate",
                "verbose_name_plural": "estimates",
                "ordering": ("-draft_id", "-estimate_date", "-estimate_id"),
            },
        ),
        migrations.CreateModel(
            name="GeneralJournalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, unique=True, verbose_name="Moneybird ID"
                    ),
                ),
                (
                    "_synced_with_moneybird",
                    models.BooleanField(
                        default=False,
                        help_text="Latest changes have been pushed to Moneybird.",
                        verbose_name="Synced with Moneybird",
                    ),
                ),
                (
                    "_delete_from_moneybird",
                    models.BooleanField(
                        default=False,
                        help_text="Delete this object from Moneybird when syncing.",
                        verbose_name="To be deleted from Moneybird",
                    ),
                ),
                (
                    "moneybird_version",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Moneybird version"
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="date")),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="reference"
                    ),
                ),
            ],
            options={
                "verbose_name": "general journal document",
                "verbose_name_plural": "general journal documents",
                "ordering": ["-date", "-moneybird_id"],
            },
        ),
        migrations.CreateModel(
            name="LedgerAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, unique=True, verbose_name="Moneybird ID"
                    ),
                ),
                (
                    "_synced_with_moneybird",
                    models.BooleanField(
                        default=False,
                        help_text="Latest changes have been pushed to Moneybird.",
                        verbose_name="Synced with Moneybird",
                    ),
                ),
                (
                    "_delete_from_moneybird",
                    models.BooleanField(
                        default=False,
                        help_text="Delete this object from Moneybird when syncing.",
                        verbose_name="To be deleted from Moneybird",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("non_current_assets", "non current assets"),
                            ("current_assets", "current assets"),
                            ("equity", "equity"),
                            ("provisions", "provisions"),
                            ("non_current_liabilities", "non current liabilities"),
                            ("current_liabilities", "current liabilities"),
                            ("revenue", "revenue"),
                            ("direct_costs", "direct costs"),
                            ("expenses", "expenses"),
                            ("other_income_expenses", "other income expenses"),
                        ],
                        max_length=100,
                        verbose_name="account type",
                    ),
                ),
                (
                    "is_margin",
                    models.BooleanField(
                        default=False,
                        help_text="All assets on this ledger account are margin assets.",
                        verbose_name="is margin",
                    ),
                ),
                (
                    "is_sales",
                    models.BooleanField(
                        default=False,
                        help_text="Ledger account is used for selling assets.",
                        verbose_name="is sales",
                    ),
                ),
                (
                    "is_purchase",
                    models.BooleanField(
                        default=False,
                        help_text="Ledger account is used for purchasing assets.",
                        verbose_name="is purchase",
                    ),
                ),
                (
                    "is_assets_inventory",
                    models.BooleanField(
                        default=False,
                        help_text="Ledger account is used as inventory ledger account.",
                        verbose_name="is assets inventory",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounting.ledgeraccount",
                        verbose_name="parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "ledger account",
                "verbose_name_plural": "ledger accounts",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, unique=True, verbose_name="Moneybird ID"
                    ),
                ),
                (
                    "_synced_with_moneybird",
                    models.BooleanField(
                        default=False,
                        help_text="Latest changes have been pushed to Moneybird.",
                        verbose_name="Synced with Moneybird",
                    ),
                ),
                (
                    "_delete_from_moneybird",
                    models.BooleanField(
                        default=False,
                        help_text="Delete this object from Moneybird when syncing.",
                        verbose_name="To be deleted from Moneybird",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="title"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "identifier",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="identifier"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="price"
                    ),
                ),
                (
                    "frequency",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="frequency"
                    ),
                ),
                (
                    "frequency_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("day", "daily"),
                            ("week", "weekly"),
                            ("month", "monthly"),
                            ("quarter", "quarterly"),
                            ("year", "yearly"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="frequency type",
                    ),
                ),
                (
                    "ledger_account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.ledgeraccount",
                        verbose_name="ledger account",
                    ),
                ),
            ],
            options={
                "verbose_name": "product",
                "verbose_name_plural": "products",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, unique=True, verbose_name="Moneybird ID"
                    ),
                ),
                (
                    "_synced_with_moneybird",
                    models.BooleanField(
                        default=False,
                        help_text="Latest changes have been pushed to Moneybird.",
                        verbose_name="Synced with Moneybird",
                    ),
                ),
                (
                    "_delete_from_moneybird",
                    models.BooleanField(
                        default=False,
                        help_text="Delete this object from Moneybird when syncing.",
                        verbose_name="To be deleted from Moneybird",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "project",
                "verbose_name_plural": "projects",
            },
        ),
        migrations.CreateModel(
            name="RecurringSalesInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, unique=True, verbose_name="Moneybird ID"
                    ),
                ),
                (
                    "_synced_with_moneybird",
                    models.BooleanField(
                        default=False,
                        help_text="Latest changes have been pushed to Moneybird.",
                        verbose_name="Synced with Moneybird",
                    ),
                ),
                (
                    "_delete_from_moneybird",
                    models.BooleanField(
                        default=False,
                        help_text="Delete this object from Moneybird when syncing.",
                        verbose_name="To be deleted from Moneybird",
                    ),
                ),
                (
                    "moneybird_version",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Moneybird version"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="reference"
                    ),
                ),
                (
                    "frequency_type",
                    models.CharField(
                        choices=[
                            ("day", "day"),
                            ("week", "week"),
                            ("month", "month"),
                            ("quarter", "quarter"),
                            ("year", "year"),
                        ],
                        max_length=10,
                        verbose_name="frequency type",
                    ),
                ),
                (
                    "frequency",
                    models.PositiveSmallIntegerField(verbose_name="frequency"),
                ),
                (
                    "first_due_interval",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="first due interval"
                    ),
                ),
                (
                    "auto_send",
                    models.BooleanField(default=True, verbose_name="auto send"),
                ),
                ("start_date", models.DateField(null=True, verbose_name="start date")),
                (
                    "invoice_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="invoice date"
                    ),
                ),
                ("last_date", models.DateField(null=True, verbose_name="last date")),
                (
                    "discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="discount",
                    ),
                ),
                (
                    "prices_are_incl_tax",
                    models.BooleanField(
                        default=True, verbose_name="prices are incl. tax"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=19,
                        null=True,
                        verbose_name="total price",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurring_sales_invoices",
                        to="accounting.contact",
                        verbose_name="contact",
                    ),
                ),
            ],
            options={
                "verbose_name": "recurring sales invoice",
                "verbose_name_plural": "recurring sales invoices",
                "ordering": ("-start_date",),
            },
        ),
        migrations.CreateModel(
            name="TaxRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, unique=True, verbose_name="Moneybird ID"
                    ),
                ),
                (
                    "_synced_with_moneybird",
                    models.BooleanField(
                        default=False,
                        help_text="Latest changes have been pushed to Moneybird.",
                        verbose_name="Synced with Moneybird",
                    ),
                ),
                (
                    "_delete_from_moneybird",
                    models.BooleanField(
                        default=False,
                        help_text="Delete this object from Moneybird when syncing.",
                        verbose_name="To be deleted from Moneybird",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("sales_invoice", "sales invoice"),
                            ("purchase_invoice", "purchase invoice"),
                            ("general_journal_document", "general journal document"),
                        ],
                        default="sales_invoice",
                        max_length=24,
                        verbose_name="type",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "tax rate",
                "verbose_name_plural": "tax rates",
            },
        ),
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, unique=True, verbose_name="Moneybird ID"
                    ),
                ),
                (
                    "_synced_with_moneybird",
                    models.BooleanField(
                        default=False,
                        help_text="Latest changes have been pushed to Moneybird.",
                        verbose_name="Synced with Moneybird",
                    ),
                ),
                (
                    "_delete_from_moneybird",
                    models.BooleanField(
                        default=False,
                        help_text="Delete this object from Moneybird when syncing.",
                        verbose_name="To be deleted from Moneybird",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("InvoiceWorkflow", "invoice"),
                            ("EstimateWorkflow", "estimate"),
                        ],
                        default="InvoiceWorkflow",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "is_rental",
                    models.BooleanField(default=False, verbose_name="is rental"),
                ),
                ("is_loan", models.BooleanField(default=False, verbose_name="is loan")),
                (
                    "is_direct_debit",
                    models.BooleanField(default=False, verbose_name="is direct debit"),
                ),
            ],
            options={
                "verbose_name": "workflow",
                "verbose_name_plural": "workflows",
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, unique=True, verbose_name="Moneybird ID"
                    ),
                ),
                (
                    "_synced_with_moneybird",
                    models.BooleanField(
                        default=False,
                        help_text="Latest changes have been pushed to Moneybird.",
                        verbose_name="Synced with Moneybird",
                    ),
                ),
                (
                    "_delete_from_moneybird",
                    models.BooleanField(
                        default=False,
                        help_text="Delete this object from Moneybird when syncing.",
                        verbose_name="To be deleted from Moneybird",
                    ),
                ),
                ("start_date", models.DateField(null=True, verbose_name="start date")),
                ("end_date", models.DateField(null=True, verbose_name="end date")),
                (
                    "cancelled_at",
                    models.DateField(null=True, verbose_name="cancelled at"),
                ),
                (
                    "reference",
                    models.CharField(max_length=255, verbose_name="reference"),
                ),
                (
                    "frequency",
                    models.PositiveSmallIntegerField(
                        blank=True, default=1, null=True, verbose_name="frequency"
                    ),
                ),
                (
                    "frequency_type",
                    models.CharField(
                        choices=[
                            ("day", "day"),
                            ("week", "week"),
                            ("month", "month"),
                            ("quarter", "quarter"),
                            ("year", "year"),
                        ],
                        max_length=10,
                        verbose_name="frequency type",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscriptions",
                        to="accounting.contact",
                        verbose_name="contact",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscription",
                        to="accounting.product",
                        verbose_name="product",
                    ),
                ),
                (
                    "recurring_sales_invoice",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscriptions",
                        to="accounting.recurringsalesinvoice",
                        verbose_name="recurring sales invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "subscription",
                "verbose_name_plural": "subscriptions",
                "ordering": ("-start_date",),
            },
        ),
        migrations.CreateModel(
            name="SalesInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, unique=True, verbose_name="Moneybird ID"
                    ),
                ),
                (
                    "_synced_with_moneybird",
                    models.BooleanField(
                        default=False,
                        help_text="Latest changes have been pushed to Moneybird.",
                        verbose_name="Synced with Moneybird",
                    ),
                ),
                (
                    "_delete_from_moneybird",
                    models.BooleanField(
                        default=False,
                        help_text="Delete this object from Moneybird when syncing.",
                        verbose_name="To be deleted from Moneybird",
                    ),
                ),
                (
                    "moneybird_version",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Moneybird version"
                    ),
                ),
                (
                    "invoice_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="invoice id"
                    ),
                ),
                (
                    "draft_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="draft id"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=19,
                        null=True,
                        verbose_name="total price",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("open", "open"),
                            ("scheduled", "scheduled"),
                            ("pending_payment", "pending payment"),
                            ("reminded", "reminded"),
                            ("late", "late"),
                            ("paid", "paid"),
                            ("uncollectible", "uncollectible"),
                        ],
                        default="draft",
                        max_length=30,
                        verbose_name="state",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True, null=True, verbose_name="invoice date"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="due date"),
                ),
                (
                    "payment_conditions",
                    models.TextField(
                        blank=True, null=True, verbose_name="payment conditions"
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        max_length=255, null=True, verbose_name="payment reference"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="reference"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="discount",
                    ),
                ),
                ("paused", models.BooleanField(default=False, verbose_name="paused")),
                ("paid_at", models.DateField(null=True, verbose_name="paid at")),
                ("sent_at", models.DateField(null=True, verbose_name="sent at")),
                (
                    "public_view_code",
                    models.CharField(
                        max_length=10, null=True, verbose_name="public view code"
                    ),
                ),
                (
                    "total_paid",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="total paid",
                    ),
                ),
                (
                    "total_unpaid",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="total unpaid",
                    ),
                ),
                (
                    "url",
                    models.URLField(max_length=2048, null=True, verbose_name="url"),
                ),
                (
                    "payment_url",
                    models.URLField(
                        max_length=2048, null=True, verbose_name="payment url"
                    ),
                ),
                (
                    "prices_are_incl_tax",
                    models.BooleanField(
                        default=True, verbose_name="prices are incl. tax"
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_invoices",
                        to="accounting.contact",
                        verbose_name="contact",
                    ),
                ),
                (
                    "document_style",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.documentstyle",
                        verbose_name="document style",
                    ),
                ),
                (
                    "original_sales_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.salesinvoice",
                        verbose_name="original sales invoice",
                    ),
                ),
                (
                    "recurring_sales_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.recurringsalesinvoice",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"active": True, "type": "InvoiceWorkflow"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.workflow",
                        verbose_name="workflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "sales invoice",
                "verbose_name_plural": "sales invoices",
                "ordering": ("-draft_id", "-date", "-invoice_id"),
            },
        ),
        migrations.CreateModel(
            name="RecurringSalesInvoiceDocumentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, unique=True, verbose_name="Moneybird ID"
                    ),
                ),
                (
                    "_synced_with_moneybird",
                    models.BooleanField(
                        default=False,
                        help_text="Latest changes have been pushed to Moneybird.",
                        verbose_name="Synced with Moneybird",
                    ),
                ),
                (
                    "_delete_from_moneybird",
                    models.BooleanField(
                        default=False,
                        help_text="Delete this object from Moneybird when syncing.",
                        verbose_name="To be deleted from Moneybird",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=19,
                        null=True,
                        verbose_name="total amount",
                    ),
                ),
                (
                    "amount",
                    models.CharField(
                        blank=True,
                        default="1 x",
                        max_length=255,
                        null=True,
                        verbose_name="amount",
                    ),
                ),
                (
                    "amount_decimal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=19,
                        null=True,
                        verbose_name="amount (decimal)",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=19, verbose_name="price"
                    ),
                ),
                (
                    "row_order",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="row order"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_lines",
                        to="accounting.recurringsalesinvoice",
                        verbose_name="document",
                    ),
                ),
                (
                    "ledger_account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.ledgeraccount",
                        verbose_name="ledger account",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.product",
                        verbose_name="product",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.project",
                        verbose_name="project",
                    ),
                ),
                (
                    "tax_rate",
                    models.ForeignKey(
                        limit_choices_to={"active": True, "type": "sales_invoice"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.taxrate",
                        verbose_name="tax rate",
                    ),
                ),
            ],
            options={
                "verbose_name": "recurring sales invoice document line",
                "verbose_name_plural": "recurring sales invoice document lines",
                "ordering": ("-document__start_date", "row_order"),
            },
        ),
        migrations.AddField(
            model_name="recurringsalesinvoice",
            name="workflow",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"active": True, "type": "InvoiceWorkflow"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.workflow",
                verbose_name="workflow",
            ),
        ),
        migrations.CreateModel(
            name="PurchaseDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, unique=True, verbose_name="Moneybird ID"
                    ),
                ),
                (
                    "_synced_with_moneybird",
                    models.BooleanField(
                        default=False,
                        help_text="Latest changes have been pushed to Moneybird.",
                        verbose_name="Synced with Moneybird",
                    ),
                ),
                (
                    "_delete_from_moneybird",
                    models.BooleanField(
                        default=False,
                        help_text="Delete this object from Moneybird when syncing.",
                        verbose_name="To be deleted from Moneybird",
                    ),
                ),
                (
                    "moneybird_version",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Moneybird version"
                    ),
                ),
                (
                    "document_kind",
                    models.CharField(
                        choices=[("INK", "purchase invoice"), ("BON", "receipt")],
                        max_length=3,
                        verbose_name="document kind",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=19,
                        null=True,
                        verbose_name="total price",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("new", "new"),
                            ("open", "open"),
                            ("scheduled", "scheduled"),
                            ("pending_payment", "pending payment"),
                            ("late", "late"),
                            ("paid", "paid"),
                        ],
                        default="open",
                        max_length=30,
                        verbose_name="state",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="date")),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="due date"),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=255, null=True, verbose_name="reference"
                    ),
                ),
                ("paid_at", models.DateField(null=True, verbose_name="paid at")),
                (
                    "prices_are_incl_tax",
                    models.BooleanField(
                        default=True, verbose_name="prices are incl. tax"
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_documents",
                        to="accounting.contact",
                        verbose_name="contact",
                    ),
                ),
            ],
            options={
                "verbose_name": "purchase document",
                "verbose_name_plural": "purchase documents",
                "ordering": ("-date", "pk"),
            },
        ),
        migrations.AddField(
            model_name="product",
            name="tax_rate",
            field=models.ForeignKey(
                limit_choices_to={"active": True, "type": "sales_invoice"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.taxrate",
                verbose_name="tax rate",
            ),
        ),
        migrations.CreateModel(
            name="JournalDocumentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, unique=True, verbose_name="Moneybird ID"
                    ),
                ),
                (
                    "_synced_with_moneybird",
                    models.BooleanField(
                        default=False,
                        help_text="Latest changes have been pushed to Moneybird.",
                        verbose_name="Synced with Moneybird",
                    ),
                ),
                (
                    "_delete_from_moneybird",
                    models.BooleanField(
                        default=False,
                        help_text="Delete this object from Moneybird when syncing.",
                        verbose_name="To be deleted from Moneybird",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=19,
                        null=True,
                        verbose_name="total amount",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.contact",
                        verbose_name="contact",
                    ),
                ),
                (
                    "ledger_account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.ledgeraccount",
                        verbose_name="ledger account",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.project",
                        verbose_name="project",
                    ),
                ),
            ],
            options={
                "verbose_name": "journal document line",
                "verbose_name_plural": "journal document lines",
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="EstimateDocumentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneybird_id",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, unique=True, verbose_name="Moneybird ID"
                    ),
                ),
                (
                    "_synced_with_moneybird",
                    models.BooleanField(
                        default=False,
                        help_text="Latest changes have been pushed to Moneybird.",
                        verbose_name="Synced with Moneybird",
                    ),
                ),
                (
                    "_delete_from_moneybird",
                    models.BooleanField(
                        default=False,
                        help_text="Delete this object from Moneybird when syncing.",
                        verbose_name="To be deleted from Moneybird",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=19,
                        null=True,
                        verbose_name="total amount",
                    ),
                ),
                (
                    "amount",
                    models.CharField(
                        blank=True,
                        default="1 x",
                        max_length=255,
                        null=True,
                        verbose_name="amount",
                    ),
                ),
                (
                    "amount_decimal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=19,
                        null=True,
                        verbose_name="amount (decimal)",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=19, verbose_name="price"
                    ),
                ),
                (
                    "row_order",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="row order"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_lines",
                        to="accounting.estimate",
                        verbose_name="document",
                    ),
                ),
                (
                    "ledger_account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.ledgeraccount",
                        verbose_name="ledger account",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.product",
                        verbose_name="product",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.project",
                        verbose_name="project",
                    ),
                ),
                (
                    "tax_rate",
                    models.ForeignKey(
                        limit_choices_to={"active": True, "type": "sales_invoice"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.taxrate",
                        verbose_name="tax rate",
                    ),
                ),
            ],
            options={
                "verbose_name": "estimate document line",
                "verbose_name_plural": "estimate document lines",
                "ordering": ("-document__estimate_date", "row_order"),
            },
        ),
        migrations.AddField(
            model_name="estimate",
            name="workflow",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"active": True, "type": "EstimateWorkflow"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.workflow",
                verbose_name="workflow",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="estimate_workflow",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"active": True, "type": "EstimateWorkflow"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="estimate_workflow_contacts",
                to="accounting.workflow",
                verbose_name="default estimate workflow",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="invoice_workflow",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"active": True, "type": "InvoiceWorkflow"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_workflow_contacts",
                to="accounting.workflow",
                verbose_name="default invoice workflow",
            ),
        ),
        migrations.CreateModel(
            name="SalesInvoiceDocumentLine",
            fields=[
                (
                    "journaldocumentline_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="accounting.journaldocumentline",
                    ),
                ),
                (
                    "amount",
                    models.CharField(
                        blank=True,
                        default="1 x",
                        max_length=255,
                        null=True,
                        verbose_name="amount",
                    ),
                ),
                (
                    "amount_decimal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=19,
                        null=True,
                        verbose_name="amount (decimal)",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=19, verbose_name="price"
                    ),
                ),
                (
                    "row_order",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="row order"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_lines",
                        to="accounting.salesinvoice",
                        verbose_name="document",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.product",
                        verbose_name="product",
                    ),
                ),
                (
                    "tax_rate",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.taxrate",
                        verbose_name="tax rate",
                    ),
                ),
            ],
            options={
                "verbose_name": "sales invoice document line",
                "verbose_name_plural": "sales invoice document lines",
                "ordering": ("-document__date", "row_order"),
            },
            bases=("accounting.journaldocumentline",),
        ),
        migrations.CreateModel(
            name="PurchaseDocumentLine",
            fields=[
                (
                    "journaldocumentline_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="accounting.journaldocumentline",
                    ),
                ),
                (
                    "amount",
                    models.CharField(
                        blank=True,
                        default="1 x",
                        max_length=255,
                        null=True,
                        verbose_name="amount",
                    ),
                ),
                (
                    "amount_decimal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=19,
                        null=True,
                        verbose_name="amount (decimal)",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=19, verbose_name="price"
                    ),
                ),
                (
                    "row_order",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="row order"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_lines",
                        to="accounting.purchasedocument",
                        verbose_name="document",
                    ),
                ),
                (
                    "tax_rate",
                    models.ForeignKey(
                        limit_choices_to={"active": True, "type": "purchase_invoice"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.taxrate",
                        verbose_name="tax rate",
                    ),
                ),
            ],
            options={
                "verbose_name": "purchase document line",
                "verbose_name_plural": "purchase document lines",
                "ordering": ("-document__date", "row_order"),
            },
            bases=("accounting.journaldocumentline",),
        ),
        migrations.CreateModel(
            name="GeneralJournalDocumentLine",
            fields=[
                (
                    "journaldocumentline_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="accounting.journaldocumentline",
                    ),
                ),
                (
                    "debit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=19,
                        null=True,
                        verbose_name="debit",
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=19,
                        null=True,
                        verbose_name="credit",
                    ),
                ),
                (
                    "row_order",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="row order"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_lines",
                        to="accounting.generaljournaldocument",
                        verbose_name="document",
                    ),
                ),
            ],
            options={
                "verbose_name": "general journal document line",
                "verbose_name_plural": "general journal document lines",
                "ordering": ("-document__date", "row_order"),
            },
            bases=("accounting.journaldocumentline",),
        ),
    ]
