# Generated by Django 4.0.6 on 2022-07-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0007_alter_project_options_alter_taxrate_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"verbose_name": "Project", "verbose_name_plural": "Projects"},
        ),
        migrations.AlterModelOptions(
            name="taxrate",
            options={"verbose_name": "Tax rate", "verbose_name_plural": "Tax rates"},
        ),
        migrations.AlterField(
            model_name="contact",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="To be deleted from Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Latest changes have been pushed to Moneybird.",
                verbose_name="Synced with Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="documentstyle",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="To be deleted from Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="documentstyle",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Latest changes have been pushed to Moneybird.",
                verbose_name="Synced with Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="To be deleted from Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Latest changes have been pushed to Moneybird.",
                verbose_name="Synced with Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="estimatedocumentline",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="To be deleted from Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="estimatedocumentline",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Latest changes have been pushed to Moneybird.",
                verbose_name="Synced with Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="generaljournaldocument",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="To be deleted from Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="generaljournaldocument",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Latest changes have been pushed to Moneybird.",
                verbose_name="Synced with Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="journaldocumentline",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="To be deleted from Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="journaldocumentline",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Latest changes have been pushed to Moneybird.",
                verbose_name="Synced with Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="ledgeraccount",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="To be deleted from Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="ledgeraccount",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Latest changes have been pushed to Moneybird.",
                verbose_name="Synced with Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="To be deleted from Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Latest changes have been pushed to Moneybird.",
                verbose_name="Synced with Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="To be deleted from Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Latest changes have been pushed to Moneybird.",
                verbose_name="Synced with Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="purchasedocument",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="To be deleted from Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="purchasedocument",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Latest changes have been pushed to Moneybird.",
                verbose_name="Synced with Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoice",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="To be deleted from Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoice",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Latest changes have been pushed to Moneybird.",
                verbose_name="Synced with Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoicedocumentline",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="To be deleted from Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoicedocumentline",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Latest changes have been pushed to Moneybird.",
                verbose_name="Synced with Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="To be deleted from Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Latest changes have been pushed to Moneybird.",
                verbose_name="Synced with Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="To be deleted from Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Latest changes have been pushed to Moneybird.",
                verbose_name="Synced with Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="taxrate",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="To be deleted from Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="taxrate",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Latest changes have been pushed to Moneybird.",
                verbose_name="Synced with Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="To be deleted from Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Latest changes have been pushed to Moneybird.",
                verbose_name="Synced with Moneybird",
            ),
        ),
    ]
