# Generated by Django 4.0.6 on 2022-07-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_alter_contact_attention_alter_contact_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='chamber_of_commerce',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
