# Generated by Django 4.0.6 on 2022-07-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0010_alter_contact_chamber_of_commerce"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="tax_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="zip_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
