# Generated by Django 4.0.6 on 2022-07-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0011_alter_contact_tax_number_alter_contact_zip_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="sales_invoices_url",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="url",
            field=models.URLField(max_length=2048, null=True, verbose_name="url"),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="payment_url",
            field=models.URLField(
                max_length=2048, null=True, verbose_name="payment url"
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="url",
            field=models.URLField(max_length=2048, null=True, verbose_name="url"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="reference",
            field=models.CharField(max_length=255, verbose_name="Reference"),
        ),
    ]
