# Generated by Django 4.0.6 on 2022-07-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounting",
            "0012_alter_contact_sales_invoices_url_alter_estimate_url_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="estimatedocumentline",
            name="amount",
            field=models.CharField(
                blank=True,
                default="1 x",
                max_length=255,
                null=True,
                verbose_name="Amount",
            ),
        ),
        migrations.AlterField(
            model_name="purchasedocumentline",
            name="amount",
            field=models.CharField(
                blank=True,
                default="1 x",
                max_length=255,
                null=True,
                verbose_name="Amount",
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoicedocumentline",
            name="amount",
            field=models.CharField(
                blank=True,
                default="1 x",
                max_length=255,
                null=True,
                verbose_name="Amount",
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoicedocumentline",
            name="amount",
            field=models.CharField(
                blank=True,
                default="1 x",
                max_length=255,
                null=True,
                verbose_name="Amount",
            ),
        ),
    ]
