# Generated by Django 4.0.6 on 2022-07-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0014_workflow_is_direct_debit_workflow_is_loan_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estimate",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "draft"),
                    ("open", "open"),
                    ("late", "late"),
                    ("accepted", "accepted"),
                    ("rejected", "rejected"),
                    ("billed", "billed"),
                    ("archived", "archived"),
                    ("scheduled", "scheduled"),
                ],
                default="draft",
                max_length=10,
                verbose_name="State",
            ),
        ),
    ]
