# Generated by Django 4.0.6 on 2022-08-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0015_alter_estimate_state"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="journaldocumentline",
            options={
                "base_manager_name": "objects",
                "verbose_name": "Journal document line",
                "verbose_name_plural": "Journal document lines",
            },
        ),
        migrations.AlterField(
            model_name="purchasedocument",
            name="document_kind",
            field=models.CharField(
                choices=[("INK", "Purchase invoice"), ("BON", "Receipt")],
                max_length=3,
                verbose_name="document kind",
            ),
        ),
        migrations.AlterField(
            model_name="purchasedocument",
            name="state",
            field=models.CharField(
                choices=[
                    ("new", "new"),
                    ("open", "open"),
                    ("scheduled", "scheduled"),
                    ("pending_payment", "pending payment"),
                    ("late", "late"),
                    ("paid", "paid"),
                ],
                default="open",
                max_length=30,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "draft"),
                    ("open", "open"),
                    ("scheduled", "scheduled"),
                    ("pending_payment", "pending payment"),
                    ("reminded", "reminded"),
                    ("late", "late"),
                    ("paid", "paid"),
                    ("uncollectible", "uncollectible"),
                ],
                default="draft",
                max_length=30,
                verbose_name="state",
            ),
        ),
    ]
