# Generated by Django 4.0.6 on 2022-08-05 10:44

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import localflavor.generic.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0017_alter_estimate_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={
                "ordering": ["company_name", "last_name", "first_name"],
                "verbose_name": "contact",
                "verbose_name_plural": "contacten",
            },
        ),
        migrations.AlterModelOptions(
            name="documentstyle",
            options={
                "verbose_name": "documentstijl",
                "verbose_name_plural": "documentstijlen",
            },
        ),
        migrations.AlterModelOptions(
            name="estimate",
            options={
                "ordering": ("-draft_id", "-estimate_date", "-estimate_id"),
                "verbose_name": "offerte",
                "verbose_name_plural": "offertes",
            },
        ),
        migrations.AlterModelOptions(
            name="estimatedocumentline",
            options={
                "ordering": ("-document__estimate_date", "row_order"),
                "verbose_name": "offerte-documentregel",
                "verbose_name_plural": "offerte-documentregels",
            },
        ),
        migrations.AlterModelOptions(
            name="generaljournaldocument",
            options={
                "ordering": ["-date", "-moneybird_id"],
                "verbose_name": "memoriaalboeking",
                "verbose_name_plural": "memoriaalboekingen",
            },
        ),
        migrations.AlterModelOptions(
            name="generaljournaldocumentline",
            options={
                "ordering": ("-document__date", "row_order"),
                "verbose_name": "memoriaalboekregel",
                "verbose_name_plural": "memoriaalboekregels",
            },
        ),
        migrations.AlterModelOptions(
            name="journaldocumentline",
            options={
                "base_manager_name": "objects",
                "verbose_name": "boekregel",
                "verbose_name_plural": "boekregels",
            },
        ),
        migrations.AlterModelOptions(
            name="ledgeraccount",
            options={
                "verbose_name": "boekrekening",
                "verbose_name_plural": "boekrekeningen",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "product", "verbose_name_plural": "producten"},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"verbose_name": "project", "verbose_name_plural": "projecten"},
        ),
        migrations.AlterModelOptions(
            name="purchasedocument",
            options={
                "ordering": ("-date", "pk"),
                "verbose_name": "inkoopdocument",
                "verbose_name_plural": "inkoopdocumenten",
            },
        ),
        migrations.AlterModelOptions(
            name="purchasedocumentline",
            options={
                "ordering": ("-document__date", "row_order"),
                "verbose_name": "inkoopdocumentregel",
                "verbose_name_plural": "inkoopdocumentregels",
            },
        ),
        migrations.AlterModelOptions(
            name="recurringsalesinvoice",
            options={
                "ordering": ("-start_date",),
                "verbose_name": "periodieke factuur",
                "verbose_name_plural": "periodieke facturen",
            },
        ),
        migrations.AlterModelOptions(
            name="recurringsalesinvoicedocumentline",
            options={
                "ordering": ("-document__start_date", "row_order"),
                "verbose_name": "periodieke factuurregel",
                "verbose_name_plural": "periodieke factuurregels",
            },
        ),
        migrations.AlterModelOptions(
            name="salesinvoice",
            options={
                "ordering": ("-draft_id", "-date", "-invoice_id"),
                "verbose_name": "factuur",
                "verbose_name_plural": "facturen",
            },
        ),
        migrations.AlterModelOptions(
            name="salesinvoicedocumentline",
            options={
                "ordering": ("-document__date", "row_order"),
                "verbose_name": "factuurregel",
                "verbose_name_plural": "factuurregels",
            },
        ),
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "ordering": ("-start_date",),
                "verbose_name": "abonnement",
                "verbose_name_plural": "abonnementen",
            },
        ),
        migrations.AlterModelOptions(
            name="taxrate",
            options={
                "verbose_name": "btw-tarief",
                "verbose_name_plural": "btw-tarieven",
            },
        ),
        migrations.AlterModelOptions(
            name="workflow",
            options={"verbose_name": "workflow", "verbose_name_plural": "workflows"},
        ),
        migrations.RemoveField(
            model_name="generaljournaldocumentline",
            name="contact",
        ),
        migrations.AddField(
            model_name="journaldocumentline",
            name="contact",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.contact",
                verbose_name="contact",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Verwijder dit object van Moneybird bij synchronisatie.",
                verbose_name="Te verwijderen van Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Laatste veranderingen zijn naar Moneybird gepusht.",
                verbose_name="Gesynchroniseerd met MoneyBird",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="address_1",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="adresregel 1"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="address_2",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="adresregel 2"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="attention",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="tenaamstelling"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="bank_account",
            field=localflavor.generic.models.IBANField(
                blank=True,
                include_countries=(
                    "AT",
                    "BE",
                    "BG",
                    "CH",
                    "CY",
                    "CZ",
                    "DE",
                    "DK",
                    "EE",
                    "ES",
                    "FI",
                    "FR",
                    "GB",
                    "GI",
                    "GR",
                    "HR",
                    "HU",
                    "IE",
                    "IS",
                    "IT",
                    "LI",
                    "LT",
                    "LU",
                    "LV",
                    "MC",
                    "MT",
                    "NL",
                    "NO",
                    "PL",
                    "PT",
                    "RO",
                    "SE",
                    "SI",
                    "SK",
                    "SM",
                ),
                max_length=34,
                null=True,
                use_nordea_extensions=False,
                verbose_name="bankrekening",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="chamber_of_commerce",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Kamer van Koophandel",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="city",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="stad"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="company_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="bedrijfsnaam"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="country",
            field=django_countries.fields.CountryField(
                default="NL", max_length=2, verbose_name="land"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="customer_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="klantnummer"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="e-mail"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email_ubl",
            field=models.BooleanField(default=False, verbose_name="e-mail ubl"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="estimate_workflow",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"active": True, "type": "EstimateWorkflow"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="estimate_workflow_contacts",
                to="accounting.workflow",
                verbose_name="standaard offerte workflow",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="invoice_workflow",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"active": True, "type": "InvoiceWorkflow"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_workflow_contacts",
                to="accounting.workflow",
                verbose_name="standaard factuur workflow",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="moneybird_version",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="Moneybird versie"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="telefoonnummer"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="sales_invoices_url",
            field=models.URLField(
                blank=True, max_length=2048, null=True, verbose_name="facturen url"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="send_estimates_to_attention",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="verstuur offertes aan (naam)",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="send_estimates_to_email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="verstuur facturen aan (e-mail)",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="send_invoices_to_attention",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="verstuur facturen aan (naam)",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="send_invoices_to_email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="verstuur facturen aan (e-mail)",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="sepa_active",
            field=models.BooleanField(default=False, verbose_name="SEPA actief"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="sepa_bic",
            field=localflavor.generic.models.BICField(
                blank=True, max_length=11, null=True, verbose_name="SEPA BIC"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="sepa_iban",
            field=localflavor.generic.models.IBANField(
                blank=True,
                include_countries=(
                    "AT",
                    "BE",
                    "BG",
                    "CH",
                    "CY",
                    "CZ",
                    "DE",
                    "DK",
                    "EE",
                    "ES",
                    "FI",
                    "FR",
                    "GB",
                    "GI",
                    "GR",
                    "HR",
                    "HU",
                    "IE",
                    "IS",
                    "IT",
                    "LI",
                    "LT",
                    "LU",
                    "LV",
                    "MC",
                    "MT",
                    "NL",
                    "NO",
                    "PL",
                    "PT",
                    "RO",
                    "SE",
                    "SI",
                    "SK",
                    "SM",
                ),
                max_length=34,
                null=True,
                use_nordea_extensions=False,
                verbose_name="SEPA IBAN",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="sepa_iban_account_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="SEPA IBAN tenaamstelling",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="sepa_mandate_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="SEPA mandaatdatum"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="sepa_mandate_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="SEPA mandaatnummer"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="sepa_sequence_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RCUR", "Periodiek"),
                    ("FRST", "Eerste"),
                    ("FNAL", "Laatste"),
                    ("OOFF", "Eenmalig"),
                ],
                max_length=4,
                null=True,
                verbose_name="SEPA sequencetype",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="tax_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="btw-nummer"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="tax_number_valid",
            field=models.BooleanField(default=False, verbose_name="btw-nummer valide"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="zip_code",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="postcode"
            ),
        ),
        migrations.AlterField(
            model_name="documentstyle",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Verwijder dit object van Moneybird bij synchronisatie.",
                verbose_name="Te verwijderen van Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="documentstyle",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Laatste veranderingen zijn naar Moneybird gepusht.",
                verbose_name="Gesynchroniseerd met MoneyBird",
            ),
        ),
        migrations.AlterField(
            model_name="documentstyle",
            name="default",
            field=models.BooleanField(default=True, verbose_name="standaard"),
        ),
        migrations.AlterField(
            model_name="documentstyle",
            name="name",
            field=models.CharField(max_length=100, verbose_name="naam"),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Verwijder dit object van Moneybird bij synchronisatie.",
                verbose_name="Te verwijderen van Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Laatste veranderingen zijn naar Moneybird gepusht.",
                verbose_name="Gesynchroniseerd met MoneyBird",
            ),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="accepted_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="geaccepteerd op"
            ),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="archived_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="gearchiveerd op"
            ),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="contact",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="estimates",
                to="accounting.contact",
                verbose_name="contact",
            ),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                verbose_name="korting",
            ),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="document_style",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.documentstyle",
                verbose_name="documentstijl",
            ),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="draft_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="conceptnummer"
            ),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="due_date",
            field=models.DateField(blank=True, null=True, verbose_name="verloopdatum"),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="estimate_date",
            field=models.DateField(blank=True, null=True, verbose_name="offertedatum"),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="estimate_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="offertenummer"
            ),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="moneybird_version",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="Moneybird versie"
            ),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="original_estimate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.estimate",
                verbose_name="originele offerte",
            ),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="post_text",
            field=models.TextField(
                blank=True, null=True, verbose_name="tekst achteraf"
            ),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="pre_text",
            field=models.TextField(blank=True, null=True, verbose_name="tekst vooraf"),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="prices_are_incl_tax",
            field=models.BooleanField(
                default=True, verbose_name="bedragen zijn incl. btw"
            ),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="public_view_code",
            field=models.CharField(
                max_length=10, null=True, verbose_name="bekijk online code"
            ),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="reference",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="referentie"
            ),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="rejected_at",
            field=models.DateField(blank=True, null=True, verbose_name="afgewezen op"),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="sent_at",
            field=models.DateField(blank=True, null=True, verbose_name="verstuurd op"),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "concept"),
                    ("open", "openstaand"),
                    ("late", "verlopen"),
                    ("accepted", "geaccepteerd"),
                    ("rejected", "afgewezen"),
                    ("billed", "gefactureerd"),
                    ("archived", "gearchiveerd"),
                    ("scheduled", "ingepland"),
                ],
                default="draft",
                max_length=10,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=19, null=True, verbose_name="totaalprijs"
            ),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="workflow",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"active": True, "type": "EstimateWorkflow"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.workflow",
                verbose_name="workflow",
            ),
        ),
        migrations.AlterField(
            model_name="estimatedocumentline",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Verwijder dit object van Moneybird bij synchronisatie.",
                verbose_name="Te verwijderen van Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="estimatedocumentline",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Laatste veranderingen zijn naar Moneybird gepusht.",
                verbose_name="Gesynchroniseerd met MoneyBird",
            ),
        ),
        migrations.AlterField(
            model_name="estimatedocumentline",
            name="amount",
            field=models.CharField(
                blank=True,
                default="1 x",
                max_length=255,
                null=True,
                verbose_name="aantal",
            ),
        ),
        migrations.AlterField(
            model_name="estimatedocumentline",
            name="amount_decimal",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=19,
                null=True,
                verbose_name="aantal (decimaal)",
            ),
        ),
        migrations.AlterField(
            model_name="estimatedocumentline",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="beschrijving"),
        ),
        migrations.AlterField(
            model_name="estimatedocumentline",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_lines",
                to="accounting.estimate",
                verbose_name="document",
            ),
        ),
        migrations.AlterField(
            model_name="estimatedocumentline",
            name="ledger_account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.ledgeraccount",
                verbose_name="boekrekening",
            ),
        ),
        migrations.AlterField(
            model_name="estimatedocumentline",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=19, verbose_name="prijs"
            ),
        ),
        migrations.AlterField(
            model_name="estimatedocumentline",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.product",
                verbose_name="product",
            ),
        ),
        migrations.AlterField(
            model_name="estimatedocumentline",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.project",
                verbose_name="project",
            ),
        ),
        migrations.AlterField(
            model_name="estimatedocumentline",
            name="row_order",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="rijvolgorde"
            ),
        ),
        migrations.AlterField(
            model_name="estimatedocumentline",
            name="tax_rate",
            field=models.ForeignKey(
                limit_choices_to={"active": True, "type": "sales_invoice"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.taxrate",
                verbose_name="btw-tarief",
            ),
        ),
        migrations.AlterField(
            model_name="estimatedocumentline",
            name="total_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=19,
                null=True,
                verbose_name="totaalbedrag",
            ),
        ),
        migrations.AlterField(
            model_name="generaljournaldocument",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Verwijder dit object van Moneybird bij synchronisatie.",
                verbose_name="Te verwijderen van Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="generaljournaldocument",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Laatste veranderingen zijn naar Moneybird gepusht.",
                verbose_name="Gesynchroniseerd met MoneyBird",
            ),
        ),
        migrations.AlterField(
            model_name="generaljournaldocument",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="datum"),
        ),
        migrations.AlterField(
            model_name="generaljournaldocument",
            name="moneybird_version",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="Moneybird versie"
            ),
        ),
        migrations.AlterField(
            model_name="generaljournaldocument",
            name="reference",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="referentie"
            ),
        ),
        migrations.AlterField(
            model_name="generaljournaldocumentline",
            name="credit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=19,
                null=True,
                verbose_name="credit",
            ),
        ),
        migrations.AlterField(
            model_name="generaljournaldocumentline",
            name="debit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=19,
                null=True,
                verbose_name="debet",
            ),
        ),
        migrations.AlterField(
            model_name="generaljournaldocumentline",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_lines",
                to="accounting.generaljournaldocument",
                verbose_name="document",
            ),
        ),
        migrations.AlterField(
            model_name="generaljournaldocumentline",
            name="row_order",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="rijvolgorde"
            ),
        ),
        migrations.AlterField(
            model_name="journaldocumentline",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Verwijder dit object van Moneybird bij synchronisatie.",
                verbose_name="Te verwijderen van Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="journaldocumentline",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Laatste veranderingen zijn naar Moneybird gepusht.",
                verbose_name="Gesynchroniseerd met MoneyBird",
            ),
        ),
        migrations.AlterField(
            model_name="journaldocumentline",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="beschrijving"),
        ),
        migrations.AlterField(
            model_name="journaldocumentline",
            name="ledger_account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.ledgeraccount",
                verbose_name="boekrekening",
            ),
        ),
        migrations.AlterField(
            model_name="journaldocumentline",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.project",
                verbose_name="project",
            ),
        ),
        migrations.AlterField(
            model_name="journaldocumentline",
            name="total_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=19,
                null=True,
                verbose_name="totaalbedrag",
            ),
        ),
        migrations.AlterField(
            model_name="ledgeraccount",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Verwijder dit object van Moneybird bij synchronisatie.",
                verbose_name="Te verwijderen van Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="ledgeraccount",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Laatste veranderingen zijn naar Moneybird gepusht.",
                verbose_name="Gesynchroniseerd met MoneyBird",
            ),
        ),
        migrations.AlterField(
            model_name="ledgeraccount",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("non_current_assets", "passiva"),
                    ("current_assets", "activa"),
                    ("equity", "eigen vermogen"),
                    ("provisions", "voorzieningen"),
                    ("non_current_liabilities", "langlopend vreemd vermogen"),
                    ("current_liabilities", "kortlopend vreemd vermogen"),
                    ("revenue", "omzet"),
                    ("direct_costs", "directe kosten"),
                    ("expenses", "kosten"),
                    ("other_income_expenses", "overige kosten"),
                ],
                max_length=100,
                verbose_name="rekeningtype",
            ),
        ),
        migrations.AlterField(
            model_name="ledgeraccount",
            name="is_margin",
            field=models.BooleanField(
                default=False,
                help_text="Alle eigendommen op deze boekrekening zijn margegoederen.",
                verbose_name="is marge",
            ),
        ),
        migrations.AlterField(
            model_name="ledgeraccount",
            name="is_purchase",
            field=models.BooleanField(
                default=False,
                help_text="Boekrekening wordt gebruikt voor de inkoop van eigendommen.",
                verbose_name="is aankoop",
            ),
        ),
        migrations.AlterField(
            model_name="ledgeraccount",
            name="is_sales",
            field=models.BooleanField(
                default=False,
                help_text="Boekrekening wordt gebruikt voor de verkoop van eigendommen.",
                verbose_name="is verkoop",
            ),
        ),
        migrations.AlterField(
            model_name="ledgeraccount",
            name="name",
            field=models.CharField(max_length=100, verbose_name="naam"),
        ),
        migrations.AlterField(
            model_name="ledgeraccount",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounting.ledgeraccount",
                verbose_name="hoofdrekening",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Verwijder dit object van Moneybird bij synchronisatie.",
                verbose_name="Te verwijderen van Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Laatste veranderingen zijn naar Moneybird gepusht.",
                verbose_name="Gesynchroniseerd met MoneyBird",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="beschrijving"),
        ),
        migrations.AlterField(
            model_name="product",
            name="frequency",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="frequentie"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="frequency_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("day", "iedere dag"),
                    ("week", "iedere week"),
                    ("month", "iedere maand"),
                    ("quarter", "ieder kwartaal"),
                    ("year", "ieder jaar"),
                ],
                max_length=10,
                null=True,
                verbose_name="frequentietype",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="identifier",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="identificatienummer",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="ledger_account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.ledgeraccount",
                verbose_name="boekrekening",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="prijs"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="tax_rate",
            field=models.ForeignKey(
                limit_choices_to={"active": True, "type": "sales_invoice"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.taxrate",
                verbose_name="btw-tarief",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="titel"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Verwijder dit object van Moneybird bij synchronisatie.",
                verbose_name="Te verwijderen van Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Laatste veranderingen zijn naar Moneybird gepusht.",
                verbose_name="Gesynchroniseerd met MoneyBird",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="active",
            field=models.BooleanField(default=True, verbose_name="actief"),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=255, verbose_name="naam"),
        ),
        migrations.AlterField(
            model_name="purchasedocument",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Verwijder dit object van Moneybird bij synchronisatie.",
                verbose_name="Te verwijderen van Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="purchasedocument",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Laatste veranderingen zijn naar Moneybird gepusht.",
                verbose_name="Gesynchroniseerd met MoneyBird",
            ),
        ),
        migrations.AlterField(
            model_name="purchasedocument",
            name="contact",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_documents",
                to="accounting.contact",
                verbose_name="contact",
            ),
        ),
        migrations.AlterField(
            model_name="purchasedocument",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="datum"),
        ),
        migrations.AlterField(
            model_name="purchasedocument",
            name="document_kind",
            field=models.CharField(
                choices=[("INK", "inkoopfactuur"), ("BON", "bonnetje")],
                max_length=3,
                verbose_name="soort document",
            ),
        ),
        migrations.AlterField(
            model_name="purchasedocument",
            name="due_date",
            field=models.DateField(blank=True, null=True, verbose_name="verloopdatum"),
        ),
        migrations.AlterField(
            model_name="purchasedocument",
            name="moneybird_version",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="Moneybird versie"
            ),
        ),
        migrations.AlterField(
            model_name="purchasedocument",
            name="paid_at",
            field=models.DateField(null=True, verbose_name="betaald op"),
        ),
        migrations.AlterField(
            model_name="purchasedocument",
            name="prices_are_incl_tax",
            field=models.BooleanField(
                default=True, verbose_name="bedragen zijn incl. btw"
            ),
        ),
        migrations.AlterField(
            model_name="purchasedocument",
            name="reference",
            field=models.CharField(
                max_length=255, null=True, verbose_name="referentie"
            ),
        ),
        migrations.AlterField(
            model_name="purchasedocument",
            name="state",
            field=models.CharField(
                choices=[
                    ("new", "nieuw"),
                    ("open", "openstaand"),
                    ("scheduled", "ingepland"),
                    ("pending_payment", "in betaling"),
                    ("late", "verlopen"),
                    ("paid", "betaald"),
                ],
                default="open",
                max_length=30,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="purchasedocument",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=19, null=True, verbose_name="totaalprijs"
            ),
        ),
        migrations.AlterField(
            model_name="purchasedocumentline",
            name="amount",
            field=models.CharField(
                blank=True,
                default="1 x",
                max_length=255,
                null=True,
                verbose_name="aantal",
            ),
        ),
        migrations.AlterField(
            model_name="purchasedocumentline",
            name="amount_decimal",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=19,
                null=True,
                verbose_name="aantal (decimaal)",
            ),
        ),
        migrations.AlterField(
            model_name="purchasedocumentline",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_lines",
                to="accounting.purchasedocument",
                verbose_name="document",
            ),
        ),
        migrations.AlterField(
            model_name="purchasedocumentline",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=19, verbose_name="prijs"
            ),
        ),
        migrations.AlterField(
            model_name="purchasedocumentline",
            name="row_order",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="rijvolgorde"
            ),
        ),
        migrations.AlterField(
            model_name="purchasedocumentline",
            name="tax_rate",
            field=models.ForeignKey(
                limit_choices_to={"active": True, "type": "purchase_invoice"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.taxrate",
                verbose_name="btw-tarief",
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoice",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Verwijder dit object van Moneybird bij synchronisatie.",
                verbose_name="Te verwijderen van Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoice",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Laatste veranderingen zijn naar Moneybird gepusht.",
                verbose_name="Gesynchroniseerd met MoneyBird",
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoice",
            name="active",
            field=models.BooleanField(default=True, verbose_name="actief"),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoice",
            name="auto_send",
            field=models.BooleanField(
                default=True, verbose_name="automatisch versturen"
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoice",
            name="contact",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recurring_sales_invoices",
                to="accounting.contact",
                verbose_name="contact",
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoice",
            name="discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                verbose_name="korting",
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoice",
            name="first_due_interval",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="eerste verloop interval"
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoice",
            name="frequency",
            field=models.PositiveSmallIntegerField(verbose_name="frequentie"),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoice",
            name="frequency_type",
            field=models.CharField(
                choices=[
                    ("day", "dag"),
                    ("week", "week"),
                    ("month", "maand"),
                    ("quarter", "kwartaal"),
                    ("year", "jaar"),
                ],
                max_length=10,
                verbose_name="frequentietype",
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoice",
            name="invoice_date",
            field=models.DateField(blank=True, null=True, verbose_name="factuurdatum"),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoice",
            name="last_date",
            field=models.DateField(null=True, verbose_name="laatste datum"),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoice",
            name="moneybird_version",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="Moneybird versie"
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoice",
            name="prices_are_incl_tax",
            field=models.BooleanField(
                default=True, verbose_name="bedragen zijn incl. btw"
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoice",
            name="reference",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="referentie"
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoice",
            name="start_date",
            field=models.DateField(null=True, verbose_name="startdatum"),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoice",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=19, null=True, verbose_name="totaalprijs"
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoice",
            name="workflow",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"active": True, "type": "InvoiceWorkflow"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.workflow",
                verbose_name="workflow",
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoicedocumentline",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Verwijder dit object van Moneybird bij synchronisatie.",
                verbose_name="Te verwijderen van Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoicedocumentline",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Laatste veranderingen zijn naar Moneybird gepusht.",
                verbose_name="Gesynchroniseerd met MoneyBird",
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoicedocumentline",
            name="amount",
            field=models.CharField(
                blank=True,
                default="1 x",
                max_length=255,
                null=True,
                verbose_name="aantal",
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoicedocumentline",
            name="amount_decimal",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=19,
                null=True,
                verbose_name="aantal (decimaal)",
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoicedocumentline",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="beschrijving"),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoicedocumentline",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_lines",
                to="accounting.recurringsalesinvoice",
                verbose_name="document",
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoicedocumentline",
            name="ledger_account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.ledgeraccount",
                verbose_name="boekrekening",
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoicedocumentline",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=19, verbose_name="prijs"
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoicedocumentline",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.product",
                verbose_name="product",
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoicedocumentline",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.project",
                verbose_name="project",
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoicedocumentline",
            name="row_order",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="rijvolgorde"
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoicedocumentline",
            name="tax_rate",
            field=models.ForeignKey(
                limit_choices_to={"active": True, "type": "sales_invoice"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.taxrate",
                verbose_name="btw-tarief",
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoicedocumentline",
            name="total_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=19,
                null=True,
                verbose_name="totaalbedrag",
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Verwijder dit object van Moneybird bij synchronisatie.",
                verbose_name="Te verwijderen van Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Laatste veranderingen zijn naar Moneybird gepusht.",
                verbose_name="Gesynchroniseerd met MoneyBird",
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="contact",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_invoices",
                to="accounting.contact",
                verbose_name="contact",
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="factuurdatum"),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                verbose_name="korting",
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="document_style",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.documentstyle",
                verbose_name="documentstijl",
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="draft_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="conceptnummer"
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="due_date",
            field=models.DateField(blank=True, null=True, verbose_name="verloopdatum"),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="invoice_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="factuurnummer"
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="moneybird_version",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="Moneybird versie"
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="original_sales_invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.salesinvoice",
                verbose_name="originele factuur",
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="paid_at",
            field=models.DateField(null=True, verbose_name="betaald op"),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="paused",
            field=models.BooleanField(default=False, verbose_name="gepauzeerd"),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="payment_conditions",
            field=models.TextField(
                blank=True, null=True, verbose_name="betaalvoorwaarden"
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="payment_reference",
            field=models.CharField(
                max_length=255, null=True, verbose_name="betalingskenmerk"
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="payment_url",
            field=models.URLField(
                max_length=2048, null=True, verbose_name="betaallink"
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="prices_are_incl_tax",
            field=models.BooleanField(
                default=True, verbose_name="bedragen zijn incl. btw"
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="public_view_code",
            field=models.CharField(
                max_length=10, null=True, verbose_name="bekijk online code"
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="reference",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="referentie"
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="sent_at",
            field=models.DateField(null=True, verbose_name="verstuurd op"),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "concept"),
                    ("open", "openstaand"),
                    ("scheduled", "ingepland"),
                    ("pending_payment", "in betaling"),
                    ("reminded", "herinnerd"),
                    ("late", "verlopen"),
                    ("paid", "betaald"),
                    ("uncollectible", "oninbaar"),
                ],
                default="draft",
                max_length=30,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="total_paid",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="totaal betaald",
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=19, null=True, verbose_name="totaalprijs"
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="total_unpaid",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="totaal onbetaald",
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="workflow",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"active": True, "type": "InvoiceWorkflow"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.workflow",
                verbose_name="workflow",
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoicedocumentline",
            name="amount",
            field=models.CharField(
                blank=True,
                default="1 x",
                max_length=255,
                null=True,
                verbose_name="aantal",
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoicedocumentline",
            name="amount_decimal",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=19,
                null=True,
                verbose_name="aantal (decimaal)",
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoicedocumentline",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_lines",
                to="accounting.salesinvoice",
                verbose_name="document",
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoicedocumentline",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=19, verbose_name="prijs"
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoicedocumentline",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.product",
                verbose_name="product",
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoicedocumentline",
            name="row_order",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="rijvolgorde"
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoicedocumentline",
            name="tax_rate",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.taxrate",
                verbose_name="btw-tarief",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Verwijder dit object van Moneybird bij synchronisatie.",
                verbose_name="Te verwijderen van Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Laatste veranderingen zijn naar Moneybird gepusht.",
                verbose_name="Gesynchroniseerd met MoneyBird",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="cancelled_at",
            field=models.DateField(null=True, verbose_name="geannuleerd op"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="contact",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscriptions",
                to="accounting.contact",
                verbose_name="contact",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="end_date",
            field=models.DateField(null=True, verbose_name="einddatum"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="frequency",
            field=models.PositiveSmallIntegerField(
                blank=True, default=1, null=True, verbose_name="frequentie"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="frequency_type",
            field=models.CharField(
                choices=[
                    ("day", "dag"),
                    ("week", "week"),
                    ("month", "maand"),
                    ("quarter", "kwartaal"),
                    ("year", "jaar"),
                ],
                max_length=10,
                verbose_name="frequentietype",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscription",
                to="accounting.product",
                verbose_name="product",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="recurring_sales_invoice",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscriptions",
                to="accounting.recurringsalesinvoice",
                verbose_name="periodieke factuur",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="reference",
            field=models.CharField(max_length=255, verbose_name="referentie"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="start_date",
            field=models.DateField(null=True, verbose_name="startdatum"),
        ),
        migrations.AlterField(
            model_name="taxrate",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Verwijder dit object van Moneybird bij synchronisatie.",
                verbose_name="Te verwijderen van Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="taxrate",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Laatste veranderingen zijn naar Moneybird gepusht.",
                verbose_name="Gesynchroniseerd met MoneyBird",
            ),
        ),
        migrations.AlterField(
            model_name="taxrate",
            name="active",
            field=models.BooleanField(default=True, verbose_name="actief"),
        ),
        migrations.AlterField(
            model_name="taxrate",
            name="name",
            field=models.CharField(max_length=100, verbose_name="naam"),
        ),
        migrations.AlterField(
            model_name="taxrate",
            name="type",
            field=models.CharField(
                choices=[
                    ("sales_invoice", "factuur"),
                    ("purchase_invoice", "inkoopfactuur"),
                    ("general_journal_document", "memoriaalboeking"),
                ],
                default="sales_invoice",
                max_length=24,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Verwijder dit object van Moneybird bij synchronisatie.",
                verbose_name="Te verwijderen van Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Laatste veranderingen zijn naar Moneybird gepusht.",
                verbose_name="Gesynchroniseerd met MoneyBird",
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="active",
            field=models.BooleanField(default=True, verbose_name="actief"),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="is_direct_debit",
            field=models.BooleanField(default=False, verbose_name="is incasso"),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="is_loan",
            field=models.BooleanField(default=False, verbose_name="is leen"),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="is_rental",
            field=models.BooleanField(default=False, verbose_name="is verhuur"),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="name",
            field=models.CharField(max_length=100, verbose_name="naam"),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="type",
            field=models.CharField(
                choices=[
                    ("InvoiceWorkflow", "factuur"),
                    ("EstimateWorkflow", "offerte"),
                ],
                default="InvoiceWorkflow",
                max_length=20,
                verbose_name="type",
            ),
        ),
    ]
