# Generated by Django 4.1 on 2022-08-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounting",
            "0018_alter_contact_options_alter_documentstyle_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="ledgeraccount",
            name="is_assets_inventory",
            field=models.BooleanField(
                default=False,
                help_text="Ledger account is used as inventory ledger account.",
                verbose_name="is assets inventory",
            ),
        ),
    ]
