# Generated by Django 4.1.2 on 2022-10-10 12:00

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import localflavor.generic.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0019_ledgeraccount_is_assets_inventory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={
                "ordering": ["company_name", "last_name", "first_name"],
                "verbose_name": "contact",
                "verbose_name_plural": "contacts",
            },
        ),
        migrations.AlterModelOptions(
            name="documentstyle",
            options={
                "verbose_name": "document style",
                "verbose_name_plural": "document styles",
            },
        ),
        migrations.AlterModelOptions(
            name="estimate",
            options={
                "ordering": ("-draft_id", "-estimate_date", "-estimate_id"),
                "verbose_name": "estimate",
                "verbose_name_plural": "estimates",
            },
        ),
        migrations.AlterModelOptions(
            name="estimatedocumentline",
            options={
                "ordering": ("-document__estimate_date", "row_order"),
                "verbose_name": "estimate document line",
                "verbose_name_plural": "estimate document lines",
            },
        ),
        migrations.AlterModelOptions(
            name="generaljournaldocument",
            options={
                "ordering": ["-date", "-moneybird_id"],
                "verbose_name": "general journal document",
                "verbose_name_plural": "general journal documents",
            },
        ),
        migrations.AlterModelOptions(
            name="generaljournaldocumentline",
            options={
                "ordering": ("-document__date", "row_order"),
                "verbose_name": "general journal document line",
                "verbose_name_plural": "general journal document lines",
            },
        ),
        migrations.AlterModelOptions(
            name="journaldocumentline",
            options={
                "base_manager_name": "objects",
                "verbose_name": "journal document line",
                "verbose_name_plural": "journal document lines",
            },
        ),
        migrations.AlterModelOptions(
            name="ledgeraccount",
            options={
                "verbose_name": "ledger account",
                "verbose_name_plural": "ledger accounts",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "product", "verbose_name_plural": "products"},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"verbose_name": "project", "verbose_name_plural": "projects"},
        ),
        migrations.AlterModelOptions(
            name="purchasedocument",
            options={
                "ordering": ("-date", "pk"),
                "verbose_name": "purchase document",
                "verbose_name_plural": "purchase documents",
            },
        ),
        migrations.AlterModelOptions(
            name="purchasedocumentline",
            options={
                "ordering": ("-document__date", "row_order"),
                "verbose_name": "purchase document line",
                "verbose_name_plural": "purchase document lines",
            },
        ),
        migrations.AlterModelOptions(
            name="recurringsalesinvoice",
            options={
                "ordering": ("-start_date",),
                "verbose_name": "recurring sales invoice",
                "verbose_name_plural": "recurring sales invoices",
            },
        ),
        migrations.AlterModelOptions(
            name="recurringsalesinvoicedocumentline",
            options={
                "ordering": ("-document__start_date", "row_order"),
                "verbose_name": "recurring sales invoice document line",
                "verbose_name_plural": "recurring sales invoice document lines",
            },
        ),
        migrations.AlterModelOptions(
            name="salesinvoice",
            options={
                "ordering": ("-draft_id", "-date", "-invoice_id"),
                "verbose_name": "sales invoice",
                "verbose_name_plural": "sales invoices",
            },
        ),
        migrations.AlterModelOptions(
            name="salesinvoicedocumentline",
            options={
                "ordering": ("-document__date", "row_order"),
                "verbose_name": "sales invoice document line",
                "verbose_name_plural": "sales invoice document lines",
            },
        ),
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "ordering": ("-start_date",),
                "verbose_name": "subscription",
                "verbose_name_plural": "subscriptions",
            },
        ),
        migrations.AlterModelOptions(
            name="taxrate",
            options={"verbose_name": "tax rate", "verbose_name_plural": "tax rates"},
        ),
        migrations.AlterField(
            model_name="contact",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="To be deleted from Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Latest changes have been pushed to Moneybird.",
                verbose_name="Synced with Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="address_1",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="address 1"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="address_2",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="address 2"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="attention",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="attention"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="bank_account",
            field=localflavor.generic.models.IBANField(
                blank=True,
                include_countries=(
                    "AT",
                    "BE",
                    "BG",
                    "CH",
                    "CY",
                    "CZ",
                    "DE",
                    "DK",
                    "EE",
                    "ES",
                    "FI",
                    "FR",
                    "GB",
                    "GI",
                    "GR",
                    "HR",
                    "HU",
                    "IE",
                    "IS",
                    "IT",
                    "LI",
                    "LT",
                    "LU",
                    "LV",
                    "MC",
                    "MT",
                    "NL",
                    "NO",
                    "PL",
                    "PT",
                    "RO",
                    "SE",
                    "SI",
                    "SK",
                    "SM",
                ),
                max_length=34,
                null=True,
                use_nordea_extensions=False,
                verbose_name="bank account",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="chamber_of_commerce",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="chamber of commerce"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="city",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="city"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="company_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="company name"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="country",
            field=django_countries.fields.CountryField(
                default="NL", max_length=2, verbose_name="country"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="customer_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="customer id"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="email"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email_ubl",
            field=models.BooleanField(default=False, verbose_name="email ubl"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="estimate_workflow",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"active": True, "type": "EstimateWorkflow"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="estimate_workflow_contacts",
                to="accounting.workflow",
                verbose_name="default estimate workflow",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="invoice_workflow",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"active": True, "type": "InvoiceWorkflow"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_workflow_contacts",
                to="accounting.workflow",
                verbose_name="default invoice workflow",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="last name"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="moneybird_version",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="Moneybird version"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="phone"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="sales_invoices_url",
            field=models.URLField(
                blank=True,
                max_length=2048,
                null=True,
                verbose_name="sales invoices url",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="send_estimates_to_attention",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="send estimates to (attention)",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="send_estimates_to_email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="send estimates to (email)",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="send_invoices_to_attention",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="send invoices to (attention)",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="send_invoices_to_email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="send invoices to (email)",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="sepa_active",
            field=models.BooleanField(default=False, verbose_name="SEPA active"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="sepa_iban_account_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="SEPA IBAN account name",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="sepa_mandate_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="SEPA mandate date"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="sepa_mandate_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="SEPA mandate id"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="sepa_sequence_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RCUR", "Recurring"),
                    ("FRST", "First"),
                    ("FNAL", "Final"),
                    ("OOFF", "One-off"),
                ],
                max_length=4,
                null=True,
                verbose_name="SEPA sequence type",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="tax_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="tax number"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="tax_number_valid",
            field=models.BooleanField(default=False, verbose_name="tax number valid"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="zip_code",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="zip code"
            ),
        ),
        migrations.AlterField(
            model_name="documentstyle",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="To be deleted from Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="documentstyle",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Latest changes have been pushed to Moneybird.",
                verbose_name="Synced with Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="documentstyle",
            name="default",
            field=models.BooleanField(default=True, verbose_name="default"),
        ),
        migrations.AlterField(
            model_name="documentstyle",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="To be deleted from Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Latest changes have been pushed to Moneybird.",
                verbose_name="Synced with Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="accepted_at",
            field=models.DateField(blank=True, null=True, verbose_name="accepted at"),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="archived_at",
            field=models.DateField(blank=True, null=True, verbose_name="archived at"),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                verbose_name="discount",
            ),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="document_style",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.documentstyle",
                verbose_name="document style",
            ),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="draft_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="draft id"
            ),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="due_date",
            field=models.DateField(blank=True, null=True, verbose_name="due date"),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="estimate_date",
            field=models.DateField(blank=True, null=True, verbose_name="estimate date"),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="estimate_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="estimate id"
            ),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="moneybird_version",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="Moneybird version"
            ),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="original_estimate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.estimate",
                verbose_name="original estimate",
            ),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="post_text",
            field=models.TextField(blank=True, null=True, verbose_name="post text"),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="pre_text",
            field=models.TextField(blank=True, null=True, verbose_name="pre text"),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="prices_are_incl_tax",
            field=models.BooleanField(
                default=True, verbose_name="prices are incl. tax"
            ),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="public_view_code",
            field=models.CharField(
                max_length=10, null=True, verbose_name="public view code"
            ),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="reference",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="reference"
            ),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="rejected_at",
            field=models.DateField(blank=True, null=True, verbose_name="rejected at"),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="sent_at",
            field=models.DateField(blank=True, null=True, verbose_name="sent at"),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "draft"),
                    ("open", "open"),
                    ("late", "late"),
                    ("accepted", "accepted"),
                    ("rejected", "rejected"),
                    ("billed", "billed"),
                    ("archived", "archived"),
                    ("scheduled", "scheduled"),
                ],
                default="draft",
                max_length=10,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=19, null=True, verbose_name="total price"
            ),
        ),
        migrations.AlterField(
            model_name="estimatedocumentline",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="To be deleted from Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="estimatedocumentline",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Latest changes have been pushed to Moneybird.",
                verbose_name="Synced with Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="estimatedocumentline",
            name="amount",
            field=models.CharField(
                blank=True,
                default="1 x",
                max_length=255,
                null=True,
                verbose_name="amount",
            ),
        ),
        migrations.AlterField(
            model_name="estimatedocumentline",
            name="amount_decimal",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=19,
                null=True,
                verbose_name="amount (decimal)",
            ),
        ),
        migrations.AlterField(
            model_name="estimatedocumentline",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="estimatedocumentline",
            name="ledger_account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.ledgeraccount",
                verbose_name="ledger account",
            ),
        ),
        migrations.AlterField(
            model_name="estimatedocumentline",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=19, verbose_name="price"
            ),
        ),
        migrations.AlterField(
            model_name="estimatedocumentline",
            name="row_order",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="row order"
            ),
        ),
        migrations.AlterField(
            model_name="estimatedocumentline",
            name="tax_rate",
            field=models.ForeignKey(
                limit_choices_to={"active": True, "type": "sales_invoice"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.taxrate",
                verbose_name="tax rate",
            ),
        ),
        migrations.AlterField(
            model_name="estimatedocumentline",
            name="total_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=19,
                null=True,
                verbose_name="total amount",
            ),
        ),
        migrations.AlterField(
            model_name="generaljournaldocument",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="To be deleted from Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="generaljournaldocument",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Latest changes have been pushed to Moneybird.",
                verbose_name="Synced with Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="generaljournaldocument",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="date"),
        ),
        migrations.AlterField(
            model_name="generaljournaldocument",
            name="moneybird_version",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="Moneybird version"
            ),
        ),
        migrations.AlterField(
            model_name="generaljournaldocument",
            name="reference",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="reference"
            ),
        ),
        migrations.AlterField(
            model_name="generaljournaldocumentline",
            name="debit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=19,
                null=True,
                verbose_name="debit",
            ),
        ),
        migrations.AlterField(
            model_name="generaljournaldocumentline",
            name="row_order",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="row order"
            ),
        ),
        migrations.AlterField(
            model_name="journaldocumentline",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="To be deleted from Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="journaldocumentline",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Latest changes have been pushed to Moneybird.",
                verbose_name="Synced with Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="journaldocumentline",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="journaldocumentline",
            name="ledger_account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.ledgeraccount",
                verbose_name="ledger account",
            ),
        ),
        migrations.AlterField(
            model_name="journaldocumentline",
            name="total_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=19,
                null=True,
                verbose_name="total amount",
            ),
        ),
        migrations.AlterField(
            model_name="ledgeraccount",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="To be deleted from Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="ledgeraccount",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Latest changes have been pushed to Moneybird.",
                verbose_name="Synced with Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="ledgeraccount",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("non_current_assets", "non current assets"),
                    ("current_assets", "current assets"),
                    ("equity", "equity"),
                    ("provisions", "provisions"),
                    ("non_current_liabilities", "non current liabilities"),
                    ("current_liabilities", "current liabilities"),
                    ("revenue", "revenue"),
                    ("direct_costs", "direct costs"),
                    ("expenses", "expenses"),
                    ("other_income_expenses", "other income expenses"),
                ],
                max_length=100,
                verbose_name="account type",
            ),
        ),
        migrations.AlterField(
            model_name="ledgeraccount",
            name="is_margin",
            field=models.BooleanField(
                default=False,
                help_text="All assets on this ledger account are margin assets.",
                verbose_name="is margin",
            ),
        ),
        migrations.AlterField(
            model_name="ledgeraccount",
            name="is_purchase",
            field=models.BooleanField(
                default=False,
                help_text="Ledger account is used for purchasing assets.",
                verbose_name="is purchase",
            ),
        ),
        migrations.AlterField(
            model_name="ledgeraccount",
            name="is_sales",
            field=models.BooleanField(
                default=False,
                help_text="Ledger account is used for selling assets.",
                verbose_name="is sales",
            ),
        ),
        migrations.AlterField(
            model_name="ledgeraccount",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="ledgeraccount",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounting.ledgeraccount",
                verbose_name="parent",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="To be deleted from Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Latest changes have been pushed to Moneybird.",
                verbose_name="Synced with Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="frequency",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="frequency"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="frequency_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("day", "daily"),
                    ("week", "weekly"),
                    ("month", "monthly"),
                    ("quarter", "quarterly"),
                    ("year", "yearly"),
                ],
                max_length=10,
                null=True,
                verbose_name="frequency type",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="identifier",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="identifier"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="ledger_account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.ledgeraccount",
                verbose_name="ledger account",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="price"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="tax_rate",
            field=models.ForeignKey(
                limit_choices_to={"active": True, "type": "sales_invoice"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.taxrate",
                verbose_name="tax rate",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="To be deleted from Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Latest changes have been pushed to Moneybird.",
                verbose_name="Synced with Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=255, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="purchasedocument",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="To be deleted from Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="purchasedocument",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Latest changes have been pushed to Moneybird.",
                verbose_name="Synced with Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="purchasedocument",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="date"),
        ),
        migrations.AlterField(
            model_name="purchasedocument",
            name="document_kind",
            field=models.CharField(
                choices=[("INK", "purchase invoice"), ("BON", "receipt")],
                max_length=3,
                verbose_name="document kind",
            ),
        ),
        migrations.AlterField(
            model_name="purchasedocument",
            name="due_date",
            field=models.DateField(blank=True, null=True, verbose_name="due date"),
        ),
        migrations.AlterField(
            model_name="purchasedocument",
            name="moneybird_version",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="Moneybird version"
            ),
        ),
        migrations.AlterField(
            model_name="purchasedocument",
            name="paid_at",
            field=models.DateField(null=True, verbose_name="paid at"),
        ),
        migrations.AlterField(
            model_name="purchasedocument",
            name="prices_are_incl_tax",
            field=models.BooleanField(
                default=True, verbose_name="prices are incl. tax"
            ),
        ),
        migrations.AlterField(
            model_name="purchasedocument",
            name="reference",
            field=models.CharField(max_length=255, null=True, verbose_name="reference"),
        ),
        migrations.AlterField(
            model_name="purchasedocument",
            name="state",
            field=models.CharField(
                choices=[
                    ("new", "new"),
                    ("open", "open"),
                    ("scheduled", "scheduled"),
                    ("pending_payment", "pending payment"),
                    ("late", "late"),
                    ("paid", "paid"),
                ],
                default="open",
                max_length=30,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="purchasedocument",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=19, null=True, verbose_name="total price"
            ),
        ),
        migrations.AlterField(
            model_name="purchasedocumentline",
            name="amount",
            field=models.CharField(
                blank=True,
                default="1 x",
                max_length=255,
                null=True,
                verbose_name="amount",
            ),
        ),
        migrations.AlterField(
            model_name="purchasedocumentline",
            name="amount_decimal",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=19,
                null=True,
                verbose_name="amount (decimal)",
            ),
        ),
        migrations.AlterField(
            model_name="purchasedocumentline",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=19, verbose_name="price"
            ),
        ),
        migrations.AlterField(
            model_name="purchasedocumentline",
            name="row_order",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="row order"
            ),
        ),
        migrations.AlterField(
            model_name="purchasedocumentline",
            name="tax_rate",
            field=models.ForeignKey(
                limit_choices_to={"active": True, "type": "purchase_invoice"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.taxrate",
                verbose_name="tax rate",
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoice",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="To be deleted from Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoice",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Latest changes have been pushed to Moneybird.",
                verbose_name="Synced with Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoice",
            name="active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoice",
            name="auto_send",
            field=models.BooleanField(default=True, verbose_name="auto send"),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoice",
            name="discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                verbose_name="discount",
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoice",
            name="first_due_interval",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="first due interval"
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoice",
            name="frequency",
            field=models.PositiveSmallIntegerField(verbose_name="frequency"),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoice",
            name="frequency_type",
            field=models.CharField(
                choices=[
                    ("day", "day"),
                    ("week", "week"),
                    ("month", "month"),
                    ("quarter", "quarter"),
                    ("year", "year"),
                ],
                max_length=10,
                verbose_name="frequency type",
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoice",
            name="invoice_date",
            field=models.DateField(blank=True, null=True, verbose_name="invoice date"),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoice",
            name="last_date",
            field=models.DateField(null=True, verbose_name="last date"),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoice",
            name="moneybird_version",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="Moneybird version"
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoice",
            name="prices_are_incl_tax",
            field=models.BooleanField(
                default=True, verbose_name="prices are incl. tax"
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoice",
            name="reference",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="reference"
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoice",
            name="start_date",
            field=models.DateField(null=True, verbose_name="start date"),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoice",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=19, null=True, verbose_name="total price"
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoicedocumentline",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="To be deleted from Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoicedocumentline",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Latest changes have been pushed to Moneybird.",
                verbose_name="Synced with Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoicedocumentline",
            name="amount",
            field=models.CharField(
                blank=True,
                default="1 x",
                max_length=255,
                null=True,
                verbose_name="amount",
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoicedocumentline",
            name="amount_decimal",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=19,
                null=True,
                verbose_name="amount (decimal)",
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoicedocumentline",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoicedocumentline",
            name="ledger_account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.ledgeraccount",
                verbose_name="ledger account",
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoicedocumentline",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=19, verbose_name="price"
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoicedocumentline",
            name="row_order",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="row order"
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoicedocumentline",
            name="tax_rate",
            field=models.ForeignKey(
                limit_choices_to={"active": True, "type": "sales_invoice"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.taxrate",
                verbose_name="tax rate",
            ),
        ),
        migrations.AlterField(
            model_name="recurringsalesinvoicedocumentline",
            name="total_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=19,
                null=True,
                verbose_name="total amount",
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="To be deleted from Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Latest changes have been pushed to Moneybird.",
                verbose_name="Synced with Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="invoice date"),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                verbose_name="discount",
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="document_style",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.documentstyle",
                verbose_name="document style",
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="draft_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="draft id"
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="due_date",
            field=models.DateField(blank=True, null=True, verbose_name="due date"),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="invoice_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="invoice id"
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="moneybird_version",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="Moneybird version"
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="original_sales_invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.salesinvoice",
                verbose_name="original sales invoice",
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="paid_at",
            field=models.DateField(null=True, verbose_name="paid at"),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="paused",
            field=models.BooleanField(default=False, verbose_name="paused"),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="payment_conditions",
            field=models.TextField(
                blank=True, null=True, verbose_name="payment conditions"
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="payment_reference",
            field=models.CharField(
                max_length=255, null=True, verbose_name="payment reference"
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="payment_url",
            field=models.URLField(
                max_length=2048, null=True, verbose_name="payment url"
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="prices_are_incl_tax",
            field=models.BooleanField(
                default=True, verbose_name="prices are incl. tax"
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="public_view_code",
            field=models.CharField(
                max_length=10, null=True, verbose_name="public view code"
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="reference",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="reference"
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="sent_at",
            field=models.DateField(null=True, verbose_name="sent at"),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "draft"),
                    ("open", "open"),
                    ("scheduled", "scheduled"),
                    ("pending_payment", "pending payment"),
                    ("reminded", "reminded"),
                    ("late", "late"),
                    ("paid", "paid"),
                    ("uncollectible", "uncollectible"),
                ],
                default="draft",
                max_length=30,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="total_paid",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, null=True, verbose_name="total paid"
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=19, null=True, verbose_name="total price"
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="total_unpaid",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, null=True, verbose_name="total unpaid"
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoicedocumentline",
            name="amount",
            field=models.CharField(
                blank=True,
                default="1 x",
                max_length=255,
                null=True,
                verbose_name="amount",
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoicedocumentline",
            name="amount_decimal",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=19,
                null=True,
                verbose_name="amount (decimal)",
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoicedocumentline",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=19, verbose_name="price"
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoicedocumentline",
            name="row_order",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="row order"
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoicedocumentline",
            name="tax_rate",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.taxrate",
                verbose_name="tax rate",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="To be deleted from Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Latest changes have been pushed to Moneybird.",
                verbose_name="Synced with Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="cancelled_at",
            field=models.DateField(null=True, verbose_name="cancelled at"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="end_date",
            field=models.DateField(null=True, verbose_name="end date"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="frequency",
            field=models.PositiveSmallIntegerField(
                blank=True, default=1, null=True, verbose_name="frequency"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="frequency_type",
            field=models.CharField(
                choices=[
                    ("day", "day"),
                    ("week", "week"),
                    ("month", "month"),
                    ("quarter", "quarter"),
                    ("year", "year"),
                ],
                max_length=10,
                verbose_name="frequency type",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="recurring_sales_invoice",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscriptions",
                to="accounting.recurringsalesinvoice",
                verbose_name="recurring sales invoice",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="reference",
            field=models.CharField(max_length=255, verbose_name="reference"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="start_date",
            field=models.DateField(null=True, verbose_name="start date"),
        ),
        migrations.AlterField(
            model_name="taxrate",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="To be deleted from Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="taxrate",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Latest changes have been pushed to Moneybird.",
                verbose_name="Synced with Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="taxrate",
            name="active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
        migrations.AlterField(
            model_name="taxrate",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="taxrate",
            name="type",
            field=models.CharField(
                choices=[
                    ("sales_invoice", "sales invoice"),
                    ("purchase_invoice", "purchase invoice"),
                    ("general_journal_document", "general journal document"),
                ],
                default="sales_invoice",
                max_length=24,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="_delete_from_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Delete this object from Moneybird when syncing.",
                verbose_name="To be deleted from Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="_synced_with_moneybird",
            field=models.BooleanField(
                default=False,
                help_text="Latest changes have been pushed to Moneybird.",
                verbose_name="Synced with Moneybird",
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="is_direct_debit",
            field=models.BooleanField(default=False, verbose_name="is direct debit"),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="is_loan",
            field=models.BooleanField(default=False, verbose_name="is loan"),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="is_rental",
            field=models.BooleanField(default=False, verbose_name="is rental"),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="type",
            field=models.CharField(
                choices=[
                    ("InvoiceWorkflow", "invoice"),
                    ("EstimateWorkflow", "estimate"),
                ],
                default="InvoiceWorkflow",
                max_length=20,
                verbose_name="type",
            ),
        ),
    ]
