# Generated by Django 4.1.6 on 2023-02-20 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounting",
            "0020_alter_contact_options_alter_documentstyle_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="journaldocumentline",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.contact",
                verbose_name="contact",
            ),
        ),
    ]
