# Generated by Django 3.0.8 on 2020-07-24 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moneybird', '0001_initial'),
        ('asset_events', '0001_initial'),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAmortization',
            fields=[
                ('singlestatuschangingevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='asset_events.SingleStatusChangingEvent')),
            ],
            options={
                'verbose_name': 'amortization',
                'verbose_name_plural': 'amortizations',
            },
            bases=('asset_events.singlestatuschangingevent',),
        ),
        migrations.CreateModel(
            name='AssetMaintenanceReturn',
            fields=[
                ('singlestatuschangingevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='asset_events.SingleStatusChangingEvent')),
            ],
            options={
                'verbose_name': 'maintenance return',
                'verbose_name_plural': 'maintenance returns',
            },
            bases=('asset_events.singlestatuschangingevent',),
        ),
        migrations.CreateModel(
            name='AssetReview',
            fields=[
                ('singlestatuschangingevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='asset_events.SingleStatusChangingEvent')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
            },
            bases=('asset_events.singlestatuschangingevent',),
        ),
        migrations.CreateModel(
            name='MaintenanceAsset',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assets.asset',),
        ),
        migrations.CreateModel(
            name='UnderReviewAsset',
            fields=[
            ],
            options={
                'verbose_name': 'asset under review',
                'verbose_name_plural': 'assets under review',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assets.asset',),
        ),
        migrations.CreateModel(
            name='MaintenanceProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('contact', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='moneybird.Contact')),
            ],
            options={
                'verbose_name': 'maintenance provider',
                'verbose_name_plural': 'maintenance providers',
            },
        ),
        migrations.CreateModel(
            name='AssetMaintenanceTicket',
            fields=[
                ('singlestatuschangingevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='asset_events.SingleStatusChangingEvent')),
                ('maintenance_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maintenance.MaintenanceProvider')),
            ],
            options={
                'verbose_name': 'maintenance ticket',
                'verbose_name_plural': 'maintenance tickets',
            },
            bases=('asset_events.singlestatuschangingevent',),
        ),
    ]
