# Generated by Django 4.1.7 on 2023-05-03 09:49

from django.db import migrations, models
import django.db.models.deletion
import scantags.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanTag",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=scantags.models.generate_new_id,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        validators=[scantags.models.validate_iso7064_mod_37_36],
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scantags",
                        to="inventory.asset",
                        verbose_name="Asset",
                    ),
                ),
            ],
            options={
                "verbose_name": "scan tag",
                "verbose_name_plural": "scan tags",
            },
        ),
    ]
