# Generated by Django 4.1 on 2022-08-17 13:23

from django.db import migrations, models
import django.db.models.deletion
import scantags.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0006_alter_asset_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanTag",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        validators=[scantags.models.validate_iso7064_mod_37_36],
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scantags",
                        to="inventory.asset",
                        verbose_name="Asset",
                    ),
                ),
            ],
        ),
    ]
