# Generated by Django 4.1 on 2022-08-17 14:36

from django.db import migrations, models
import scantags.models


class Migration(migrations.Migration):

    dependencies = [
        ("scantags", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scantag",
            options={"verbose_name": "scan tag", "verbose_name_plural": "scan tags"},
        ),
        migrations.AlterField(
            model_name="scantag",
            name="id",
            field=models.CharField(
                default=scantags.models.generate_new_id,
                max_length=255,
                primary_key=True,
                serialize=False,
                validators=[scantags.models.validate_iso7064_mod_37_36],
                verbose_name="ID",
            ),
        ),
    ]
