# Generated by Django 3.0.8 on 2020-07-27 14:55

import asset_media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='media',
            field=models.FileField(upload_to=asset_media.models.get_upload_path),
        ),
    ]
