# Generated by Django 3.0.8 on 2020-07-27 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_events', '0002_auto_20200724_2322'),
        ('media', '0002_auto_20200727_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaset',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asset_events.Event'),
        ),
    ]
