# Generated by Django 3.0.8 on 2020-07-24 20:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.TextField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.Asset')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_asset_events.event_set+', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
            },
        ),
        migrations.CreateModel(
            name='SingleStatusChangingEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='asset_events.Event')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
            bases=('asset_events.event', models.Model),
        ),
        migrations.CreateModel(
            name='MultiAssetEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_asset_events.multiassetevent_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetDisappearance',
            fields=[
                ('singlestatuschangingevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='asset_events.SingleStatusChangingEvent')),
            ],
            options={
                'verbose_name': 'disappearance',
                'verbose_name_plural': 'disappearances',
            },
            bases=('asset_events.singlestatuschangingevent',),
        ),
        migrations.CreateModel(
            name='AssetReturnFromUnknown',
            fields=[
                ('singlestatuschangingevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='asset_events.SingleStatusChangingEvent')),
                ('new_status', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Placeholder reserved'), (2, 'To be delivered'), (3, 'Under review'), (4, 'Maintenance (in house)'), (5, 'Maintenance (external)'), (6, 'Available'), (7, 'Issued (unprocessed)'), (8, 'Issued (rental)'), (9, 'Issued (loan)'), (10, 'Amortized'), (11, 'Sold')])),
            ],
            options={
                'verbose_name': 'return from unknown',
                'verbose_name_plural': 'returns from unknown',
            },
            bases=('asset_events.singlestatuschangingevent',),
        ),
    ]
