# Generated by Django 3.0.8 on 2020-07-24 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_location'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('asset_events', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssetReturnFromUnknown',
            new_name='MiscellaneousAssetEvent',
        ),
        migrations.AlterModelOptions(
            name='miscellaneousassetevent',
            options={'verbose_name': 'miscellaneous event', 'verbose_name_plural': 'miscellaneous events'},
        ),
        migrations.DeleteModel(
            name='AssetDisappearance',
        ),
    ]
