# Generated by Django 3.0.8 on 2020-08-07 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moneybird', '0001_initial'),
        ('assets', '0001_initial'),
        ('asset_events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetDelivery',
            fields=[
                ('multiassetevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='asset_events.MultiAssetEvent')),
            ],
            options={
                'verbose_name': 'delivery',
                'verbose_name_plural': 'deliveries',
            },
            bases=('asset_events.multiassetevent',),
        ),
        migrations.CreateModel(
            name='AssetPurchase',
            fields=[
                ('multiassetevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='asset_events.MultiAssetEvent')),
            ],
            options={
                'verbose_name': 'purchase',
                'verbose_name_plural': 'purchases',
            },
            bases=('asset_events.multiassetevent',),
        ),
        migrations.CreateModel(
            name='PlaceholderAsset',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assets.asset',),
        ),
        migrations.CreateModel(
            name='ToBeDeliveredAsset',
            fields=[
            ],
            options={
                'verbose_name': 'asset to be delivered',
                'verbose_name_plural': 'assets to be delivered',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assets.asset',),
        ),
        migrations.CreateModel(
            name='SingleAssetPurchase',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='asset_events.Event')),
                ('already_delivered', models.BooleanField(default=False)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.AssetPurchase')),
            ],
            options={
                'verbose_name': 'asset purchase',
                'verbose_name_plural': 'asset purchases',
            },
            bases=('asset_events.event',),
        ),
        migrations.CreateModel(
            name='SingleAssetDelivery',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='asset_events.Event')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.AssetDelivery')),
            ],
            options={
                'verbose_name': 'asset delivery',
                'verbose_name_plural': 'asset deliveries',
            },
            bases=('asset_events.event',),
        ),
        migrations.AddField(
            model_name='assetpurchase',
            name='assets',
            field=models.ManyToManyField(through='purchases.SingleAssetPurchase', to='assets.Asset'),
        ),
        migrations.AddField(
            model_name='assetpurchase',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='moneybird.Contact'),
        ),
        migrations.AddField(
            model_name='assetdelivery',
            name='assets',
            field=models.ManyToManyField(through='purchases.SingleAssetDelivery', to='assets.Asset'),
        ),
    ]
