# Generated by Django 3.0.8 on 2020-07-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybird', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='payment_conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
