# Generated by Django 3.0.8 on 2020-07-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybird', '0002_auto_20200704_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='payment_conditions',
            field=models.TextField(blank=True, help_text='Supports Moneybird tags in the form of {document.field}.', null=True),
        ),
    ]
