# Generated by Django 3.0.8 on 2020-07-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybird', '0003_auto_20200704_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='sales_invoices_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='state',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('open', 'Open'), ('scheduled', 'Scheduled'), ('pending_payment', 'Pending payment'), ('late', 'Late'), ('reminded', 'Reminded'), ('paid', 'Paid'), ('uncollectible', 'Uncollectible')], max_length=100, null=True),
        ),
    ]
