# Generated by Django 3.0.8 on 2020-07-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybird', '0004_auto_20200704_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoice',
            name='sales_invoices_url',
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='payment_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='invoice_date',
            field=models.DateField(blank=True, help_text='Will be set automatically when invoice is sent.', null=True),
        ),
    ]
