# Generated by Django 3.0.8 on 2020-07-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybird', '0005_auto_20200704_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='prices_are_incl_tax',
            field=models.BooleanField(default=True, verbose_name='display prices incl. tax'),
        ),
    ]
