# Generated by Django 3.0.8 on 2020-07-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybird', '0007_auto_20200704_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='paid_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='sent_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
