# Generated by Django 3.0.8 on 2020-07-04 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moneybird', '0008_auto_20200704_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='original_sales_invoice_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moneybird.SalesInvoice'),
        ),
    ]
