# Generated by Django 3.0.8 on 2020-07-04 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneybird', '0009_salesinvoice_original_sales_invoice_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesinvoice',
            old_name='original_sales_invoice_id',
            new_name='original_sales_invoice',
        ),
    ]
