# Generated by Django 3.0.8 on 2020-07-04 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moneybird', '0010_auto_20200704_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDetailItem',
            fields=[
                ('id', models.CharField(help_text='This is the primary key of this object, both for this application and in Moneybird.', max_length=20, primary_key=True, serialize=False)),
                ('tax_rate_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ledger_account_id', models.CharField(blank=True, max_length=100, null=True)),
                ('project_id', models.CharField(blank=True, max_length=100, null=True)),
                ('product_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.CharField(blank=True, max_length=10, null=True)),
                ('amount_decimal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('period', models.CharField(blank=True, max_length=100, null=True)),
                ('row_order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_price_excl_tax_with_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price_excl_tax_with_discount_base', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='details', to='moneybird.SalesInvoice')),
            ],
            options={
                'verbose_name': 'invoice detail item',
                'verbose_name_plural': 'invoice detail items',
            },
        ),
    ]
