# Generated by Django 3.0.8 on 2020-07-04 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moneybird', '0011_invoicedetailitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetailitem',
            name='version',
            field=models.IntegerField(blank=True, help_text='This is the Moneybird version of the currently stored data and is used when looking for changes efficiently.', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='invoicedetailitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='moneybird.SalesInvoice'),
        ),
    ]
