# Generated by Django 3.0.8 on 2020-07-04 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneybird', '0012_auto_20200704_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedetailitem',
            name='version',
        ),
    ]
