# Generated by Django 3.0.8 on 2020-07-05 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moneybird', '0013_remove_invoicedetailitem_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetailitem',
            name='invoice',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='moneybird.SalesInvoice'),
        ),
    ]
