# Generated by Django 3.0.8 on 2020-07-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybird', '0014_auto_20200705_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.CharField(editable=False, help_text='This is the primary key of this object, both for this application and in Moneybird.', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoicedetailitem',
            name='id',
            field=models.CharField(editable=False, help_text='This is the primary key of this object, both for this application and in Moneybird.', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='id',
            field=models.CharField(editable=False, help_text='This is the primary key of this object, both for this application and in Moneybird.', max_length=20, primary_key=True, serialize=False),
        ),
    ]
