# Generated by Django 3.2.9 on 2021-12-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
