# Generated by Django 3.0.8 on 2020-07-24 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetLocationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'location group',
                'verbose_name_plural': 'location groups',
            },
        ),
        migrations.AddField(
            model_name='assetlocation',
            name='location_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='assets.AssetLocationGroup'),
            preserve_default=False,
        ),
    ]
