# Generated by Django 4.0.2 on 2022-03-07 12:25
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="invoice",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="receipt",
        ),
        migrations.AlterField(
            model_name="asset",
            name="purchasing_value",
            field=models.FloatField(verbose_name="Purchasing value"),
        ),
        migrations.AlterField(
            model_name="assetstate",
            name="closet",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Closet"
            ),
        ),
        migrations.AlterField(
            model_name="assetstate",
            name="external",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="External"
            ),
        ),
        migrations.AlterField(
            model_name="assetstate",
            name="room",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Room"
            ),
        ),
    ]
