# Generated by Django 3.0.8 on 2020-08-07 21:07

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20200807_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcategory',
            name='name_singular',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(re.compile('^[-\\w]+\\Z'), 'Enter a valid “slug” consisting of Unicode letters, numbers, underscores, or hyphens.', 'invalid')]),
        ),
    ]
