# Generated by Django 3.0.5 on 2020-06-29 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20200629_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Placeholder reserved'), (2, 'To be delivered'), (3, 'Under review'), (4, 'Maintenance (in house)'), (5, 'Maintenance (external)'), (6, 'Available'), (7, 'Issued (unprocessed)'), (8, 'Issued (rental)'), (9, 'Issued (loan)'), (10, 'Amortized'), (11, 'Sold')], default=0),
        ),
        migrations.CreateModel(
            name='AssetLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('event_date', models.DateTimeField()),
                ('type', models.IntegerField(choices=[(0, 'Rental start')])),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.Asset')),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'events',
            },
        ),
    ]
