# Generated by Django 4.0.3 on 2022-04-20 15:10
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_id", models.CharField(max_length=200, verbose_name="Old ID")),
                ("asset_type", models.CharField(max_length=200, verbose_name="Type")),
                ("size", models.CharField(max_length=200, verbose_name="Size")),
                (
                    "collection",
                    models.CharField(max_length=200, verbose_name="Collection"),
                ),
                ("listing_price", models.FloatField(verbose_name="Listing price")),
                ("stock_price", models.FloatField(verbose_name="Stock price")),
                (
                    "purchasing_value",
                    models.FloatField(verbose_name="Purchasing value"),
                ),
                ("margin", models.BooleanField(verbose_name="Margin")),
                (
                    "remarks",
                    models.TextField(
                        blank=True, max_length=1000, null=True, verbose_name="Remarks"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssetState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("purchased", "purchased"),
                            ("under_review", "under_review"),
                            ("ready", "ready"),
                            ("outgoing", "outgoing"),
                            ("rented", "rented"),
                            ("lent", "lent"),
                            ("under_repair_internal", "under_repair_internal"),
                            ("under_repair_external", "under_repair_external"),
                            ("sold", "sold"),
                            ("amortized", "amortized"),
                        ],
                        max_length=100,
                        verbose_name="State",
                    ),
                ),
                (
                    "room",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="Room"
                    ),
                ),
                (
                    "closet",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="Closet"
                    ),
                ),
                (
                    "external",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="External"
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.asset",
                        verbose_name="Asset",
                    ),
                ),
            ],
        ),
    ]
