# Generated by Django 4.0.4 on 2022-06-09 15:08
import django.db.models.deletion
import inventory.models
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    replaces = [
        ("inventory", "0001_initial"),
        ("inventory", "0002_remove_asset_old_id_alter_asset_id"),
        ("inventory", "0003_collection_remove_asset_margin_asset_mb_state_and_more"),
        ("inventory", "0004_alter_asset_mb_state_alter_asset_local_state"),
        ("inventory", "0005_rename_mb_state_asset_moneybird_state"),
        ("inventory", "0006_attachment"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Collection Name"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=200,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_type", models.CharField(max_length=200, verbose_name="Type")),
                ("size", models.CharField(max_length=200, verbose_name="Size")),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.collection",
                        verbose_name="Collection",
                    ),
                ),
                ("listing_price", models.FloatField(verbose_name="Listing price")),
                ("stock_price", models.FloatField(verbose_name="Stock price")),
                (
                    "purchasing_value",
                    models.FloatField(verbose_name="Purchasing value"),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True, max_length=1000, null=True, verbose_name="Remarks"
                    ),
                ),
                (
                    "moneybird_state",
                    models.CharField(
                        choices=[
                            ("Unknown", "Onbekend"),
                            ("N/A", "N/A"),
                            ("Purchased", "Purchased"),
                            ("Sold", "Sold"),
                            ("Sold (incomplete)", "Sold (incomplete)"),
                            ("Sold (error)", "Sold (error)"),
                            ("Rented", "Rented"),
                            ("Rented (error)", "Rented (error)"),
                            ("Loaned", "Loaned"),
                            ("Amortized", "Amortized"),
                        ],
                        default="Unknown",
                        max_length=40,
                        verbose_name="Moneybird State",
                    ),
                ),
                (
                    "estimates",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Huurovereenkomst", "Huurovereenkomst"),
                            ("Leenovereenkomst", "Leenovereenkomst"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "local_state",
                    models.CharField(
                        choices=[
                            ("Unknown", "Onbekend"),
                            ("N/A", "N/A"),
                            ("Purchased", "Purchased"),
                            ("Sold", "Sold"),
                            ("Sold (incomplete)", "Sold (incomplete)"),
                            ("Sold (error)", "Sold (error)"),
                            ("Rented", "Rented"),
                            ("Rented (error)", "Rented (error)"),
                            ("Loaned", "Loaned"),
                            ("Amortized", "Amortized"),
                        ],
                        default="Unknown",
                        max_length=40,
                        verbose_name="Local State",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        upload_to=inventory.models.attachments_directory_path
                    ),
                ),
                ("upload_date", models.DateField(auto_now_add=True)),
                (
                    "remarks",
                    models.TextField(
                        blank=True, max_length=1000, verbose_name="Remarks"
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.asset",
                        verbose_name="Asset",
                    ),
                ),
            ],
        ),
    ]
