# Generated by Django 4.0.3 on 2022-04-11 11:55
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="asset",
            options={},
        ),
        migrations.AlterModelOptions(
            name="assetstate",
            options={},
        ),
        migrations.RemoveField(
            model_name="asset",
            name="invoice",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="receipt",
        ),
        migrations.AlterField(
            model_name="asset",
            name="purchasing_value",
            field=models.FloatField(verbose_name="Purchasing value"),
        ),
        migrations.AlterField(
            model_name="assetstate",
            name="closet",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Closet"
            ),
        ),
        migrations.AlterField(
            model_name="assetstate",
            name="external",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="External"
            ),
        ),
        migrations.AlterField(
            model_name="assetstate",
            name="room",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Room"
            ),
        ),
        migrations.AlterField(
            model_name="assetstate",
            name="state",
            field=models.CharField(
                choices=[
                    ("purchased", "purchased"),
                    ("under_review", "under_review"),
                    ("ready", "ready"),
                    ("outgoing", "outgoing"),
                    ("rented", "rented"),
                    ("lent", "lent"),
                    ("under_repair_internal", "under_repair_internal"),
                    ("under_repair_external", "under_repair_external"),
                    ("sold", "sold"),
                    ("amortized", "amortized"),
                ],
                max_length=100,
                verbose_name="State",
            ),
        ),
    ]
