# Generated by Django 4.0.4 on 2022-06-13 10:02
import django.db.models.deletion
import inventory.models.attachment
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_squashed_0006_attachment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attachment",
            options={"verbose_name": "Bijlage"},
        ),
        migrations.AlterModelOptions(
            name="collection",
            options={"verbose_name": "Collectie"},
        ),
        migrations.AlterField(
            model_name="asset",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.collection",
                verbose_name="Collectie",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="estimates",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Huurovereenkomst", "Huurovereenkomst"),
                    ("Leenovereenkomst", "Leenovereenkomst"),
                ],
                max_length=16,
                null=True,
                verbose_name="Estimates",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="listing_price",
            field=models.FloatField(verbose_name="Vraagprijs"),
        ),
        migrations.AlterField(
            model_name="asset",
            name="local_state",
            field=models.CharField(
                choices=[
                    ("Unknown", "Onbekend"),
                    ("N/A", "n.v.t."),
                    ("Purchased", "Gekocht"),
                    ("Sold", "Verkocht"),
                    ("Sold (incomplete)", "Verkocht (incompleet)"),
                    ("Sold (error)", "Verkocht (error)"),
                    ("Rented", "Verhuurd"),
                    ("Rented (error)", "Verhuurd (error)"),
                    ("Loaned", "Uitgeleend"),
                    ("Amortized", "Afgeschreven"),
                ],
                default="Unknown",
                max_length=40,
                verbose_name="Lokale status",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="moneybird_state",
            field=models.CharField(
                choices=[
                    ("Unknown", "Onbekend"),
                    ("N/A", "n.v.t."),
                    ("Purchased", "Gekocht"),
                    ("Sold", "Verkocht"),
                    ("Sold (incomplete)", "Verkocht (incompleet)"),
                    ("Sold (error)", "Verkocht (error)"),
                    ("Rented", "Verhuurd"),
                    ("Rented (error)", "Verhuurd (error)"),
                    ("Loaned", "Uitgeleend"),
                    ("Amortized", "Afgeschreven"),
                ],
                default="Unknown",
                max_length=40,
                verbose_name="MoneyBird-status",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="purchasing_value",
            field=models.FloatField(verbose_name="Inkoopwaarde"),
        ),
        migrations.AlterField(
            model_name="asset",
            name="remarks",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="Opmerkingen"
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="size",
            field=models.CharField(max_length=200, verbose_name="Formaat"),
        ),
        migrations.AlterField(
            model_name="asset",
            name="stock_price",
            field=models.FloatField(verbose_name="Koers"),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="attachment",
            field=models.FileField(
                upload_to=inventory.models.attachment.attachments_directory_path,
                verbose_name="Bijlage",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="remarks",
            field=models.TextField(
                blank=True, max_length=1000, verbose_name="Opmerkingen"
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="upload_date",
            field=models.DateField(auto_now_add=True, verbose_name="Uploaddatum"),
        ),
        migrations.AlterField(
            model_name="collection",
            name="name",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="Collectienaam"
            ),
        ),
    ]
