# Generated by Django 4.0.2 on 2022-03-14 12:26
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_remove_asset_invoice_remove_asset_receipt_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="asset",
            options={},
        ),
        migrations.AlterModelOptions(
            name="assetstate",
            options={},
        ),
        migrations.AlterField(
            model_name="assetstate",
            name="state",
            field=models.CharField(
                choices=[
                    ("purchased", "purchased"),
                    ("under_review", "under_review"),
                    ("ready", "ready"),
                    ("outgoing", "outgoing"),
                    ("rented", "rented"),
                    ("lent", "lent"),
                    ("under_repair_internal", "under_repair_internal"),
                    ("under_repair_external", "under_repair_external"),
                    ("sold", "sold"),
                    ("amortized", "amortized"),
                ],
                max_length=100,
                verbose_name="State",
            ),
        ),
    ]
