# Generated by Django 4.0.4 on 2022-06-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0002_alter_attachment_options_alter_collection_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="commerce",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
