# Generated by Django 4.0.4 on 2022-04-25 13:26
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_remove_asset_old_id_alter_asset_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Collection Name", unique=True
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="asset",
            name="margin",
        ),
        migrations.AddField(
            model_name="asset",
            name="MB_state",
            field=models.CharField(
                choices=[
                    ("Unknown", "Unknown"),
                    ("N/A", "N/A"),
                    ("Purchased", "Purchased"),
                    ("Sold", "Sold"),
                    ("Sold (incomplete)", "Sold (incomplete)"),
                    ("Sold (error)", "Sold (error)"),
                    ("Rented", "Rented"),
                    ("Rented (error)", "Rented (error)"),
                    ("Loaned", "Loaned"),
                    ("Amortize", "Amortize"),
                ],
                default="Unknown",
                max_length=40,
                verbose_name="Moneybird State",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="estimates",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Huurovereenkomst", "Huurovereenkomst"),
                    ("Leenovereenkomst", "Leenovereenkomst"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="ledger",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Voorraad marge", "Voorraad marge"),
                    ("Voorraad niet-marge", "Voorraad niet-marge"),
                    (
                        "Voorraadwaarde bij verkoop marge",
                        "Voorraadwaarde bij verkoop marge",
                    ),
                    (
                        "Voorraadwaarde bij verkoop niet-marge",
                        "Voorraadwaarde bij verkoop niet-marge",
                    ),
                    ("Verkoop marge", "Verkoop marge"),
                    ("Verkoop niet-marge", "Verkoop niet-marge"),
                    (
                        "Directe afschrijving bij aankoop",
                        "Directe afschrijving bij aankoop",
                    ),
                    ("Afschrijvingen", "Afschrijvingen"),
                    ("Borgen", "Borgen"),
                ],
                max_length=40,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="local_state",
            field=models.CharField(
                choices=[
                    ("Unknown", "Unknown"),
                    ("N/A", "N/A"),
                    ("Purchased", "Purchased"),
                    ("Sold", "Sold"),
                    ("Sold (incomplete)", "Sold (incomplete)"),
                    ("Sold (error)", "Sold (error)"),
                    ("Rented", "Rented"),
                    ("Rented (error)", "Rented (error)"),
                    ("Loaned", "Loaned"),
                    ("Amortize", "Amortize"),
                ],
                default="Unknown",
                max_length=40,
                verbose_name="Local State",
            ),
        ),
        migrations.DeleteModel(
            name="AssetState",
        ),
        migrations.AlterField(
            model_name="asset",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.collection",
                verbose_name="Collection",
            ),
        ),
    ]
