# Generated by Django 4.0.4 on 2022-05-09 10:31
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_collection_remove_asset_margin_asset_mb_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="MB_state",
            field=models.CharField(
                choices=[
                    ("Unknown", "Onbekend"),
                    ("N/A", "N/A"),
                    ("Purchased", "Purchased"),
                    ("Sold", "Sold"),
                    ("Sold (incomplete)", "Sold (incomplete)"),
                    ("Sold (error)", "Sold (error)"),
                    ("Rented", "Rented"),
                    ("Rented (error)", "Rented (error)"),
                    ("Loaned", "Loaned"),
                    ("Amortized", "Amortized"),
                ],
                default="Unknown",
                max_length=40,
                verbose_name="Moneybird State",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="local_state",
            field=models.CharField(
                choices=[
                    ("Unknown", "Onbekend"),
                    ("N/A", "N/A"),
                    ("Purchased", "Purchased"),
                    ("Sold", "Sold"),
                    ("Sold (incomplete)", "Sold (incomplete)"),
                    ("Sold (error)", "Sold (error)"),
                    ("Rented", "Rented"),
                    ("Rented (error)", "Rented (error)"),
                    ("Loaned", "Loaned"),
                    ("Amortized", "Amortized"),
                ],
                default="Unknown",
                max_length=40,
                verbose_name="Local State",
            ),
        ),
    ]
