# Generated by Django 4.0.6 on 2022-07-09 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_assetcategory_assetlocationgroup_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="moneybird_state",
        ),
    ]
