# Generated by Django 4.0.4 on 2022-05-27 13:11
import django.db.models.deletion
import inventory.models
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_rename_mb_state_asset_moneybird_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        upload_to=inventory.models.attachments_directory_path
                    ),
                ),
                ("upload_date", models.DateField(auto_now_add=True)),
                (
                    "remarks",
                    models.TextField(
                        blank=True, max_length=1000, verbose_name="Remarks"
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.asset",
                        verbose_name="Asset",
                    ),
                ),
            ],
        ),
    ]
