# Generated by Django 4.0.6 on 2022-07-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_remove_asset_purchasing_value_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="local_state",
        ),
        migrations.AddField(
            model_name="asset",
            name="local_status",
            field=models.CharField(
                choices=[
                    ("unknown", "Onbekend"),
                    ("placeholder", "Placeholder"),
                    ("to_be_delivered", "To be delivered"),
                    ("under_review", "Under review"),
                    ("maintenance_in_house", "Maintenance in house"),
                    ("maintenance_external", "Maintenance external"),
                    ("available", "Available"),
                    ("issued_unprocessed", "Issued unprocessed"),
                    ("issued_rent", "Issued rent"),
                    ("issued_loan", "Issued loan"),
                    ("amortized", "Afgeschreven"),
                    ("sold", "Verkocht"),
                ],
                default="Unknown",
                max_length=40,
                verbose_name="Local status",
            ),
        ),
    ]
