# Generated by Django 4.0.6 on 2022-07-14 08:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_remove_asset_local_state_asset_local_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="asset",
            options={
                "ordering": ["created_at", "id"],
                "verbose_name": "asset",
                "verbose_name_plural": "assets",
            },
        ),
        migrations.AddField(
            model_name="asset",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
