# Generated by Django 4.0.6 on 2022-07-14 08:51

from django.db import migrations, models
import django.db.models.deletion
import inventory.models.attachment


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_alter_asset_options_asset_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.collection",
                verbose_name="Collection",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="listing_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Listing price",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="local_status",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("placeholder", "Placeholder"),
                    ("to_be_delivered", "To be delivered"),
                    ("under_review", "Under review"),
                    ("maintenance_in_house", "Maintenance in house"),
                    ("maintenance_external", "Maintenance external"),
                    ("available", "Available"),
                    ("issued_unprocessed", "Issued unprocessed"),
                    ("issued_rent", "Issued rent"),
                    ("issued_loan", "Issued loan"),
                    ("amortized", "Amortized"),
                    ("sold", "Sold"),
                ],
                default="Unknown",
                max_length=40,
                verbose_name="Local status",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="remarks",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="Remarks"
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="attachment",
            field=models.FileField(
                upload_to=inventory.models.attachment.attachments_directory_path,
                verbose_name="Attachment",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="remarks",
            field=models.TextField(blank=True, max_length=1000, verbose_name="Remarks"),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="upload_date",
            field=models.DateField(auto_now_add=True, verbose_name="Upload date"),
        ),
        migrations.AlterField(
            model_name="collection",
            name="name",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="Collection Name"
            ),
        ),
    ]
