# Generated by Django 4.0.6 on 2022-07-25 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0027_remove_estimatedocumentline_asset_and_more"),
        ("inventory", "0009_alter_asset_collection_alter_asset_listing_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetOnJournalDocumentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.AddField(
            model_name="asset",
            name="estimates",
            field=models.ManyToManyField(to="accounting.estimatedocumentline"),
        ),
        migrations.AddField(
            model_name="asset",
            name="journal_document_lines",
            field=models.ManyToManyField(
                through="inventory.AssetOnJournalDocumentLine",
                to="accounting.journaldocumentline",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="recurring_sales_invoice_lines",
            field=models.ManyToManyField(
                to="accounting.recurringsalesinvoicedocumentline"
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="subscriptions",
            field=models.ManyToManyField(to="accounting.subscription"),
        ),
        migrations.AddField(
            model_name="assetonjournaldocumentline",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.asset"
            ),
        ),
        migrations.AddField(
            model_name="assetonjournaldocumentline",
            name="document_line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="accounting.journaldocumentline",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assetonjournaldocumentline",
            unique_together={("asset", "document_line")},
        ),
    ]
