# Generated by Django 4.0.6 on 2022-07-25 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0027_remove_estimatedocumentline_asset_and_more"),
        ("inventory", "0010_assetonjournaldocumentline_asset_estimates_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetonjournaldocumentline",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journal_document_line_assets",
                to="inventory.asset",
            ),
        ),
        migrations.AlterField(
            model_name="assetonjournaldocumentline",
            name="document_line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assets",
                to="accounting.journaldocumentline",
            ),
        ),
    ]
