# Generated by Django 4.0.6 on 2022-07-25 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_alter_assetonjournaldocumentline_asset_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assetonjournaldocumentline",
            name="value",
        ),
    ]
