# Generated by Django 4.0.6 on 2022-07-25 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0027_remove_estimatedocumentline_asset_and_more"),
        ("inventory", "0012_remove_assetonjournaldocumentline_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetOnEstimateDocumentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="AssetOnRecurringSalesInvoiceDocumentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name="asset",
            name="estimates",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="recurring_sales_invoice_lines",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="subscriptions",
        ),
        migrations.AddField(
            model_name="asset",
            name="estimate_document_lines",
            field=models.ManyToManyField(
                through="inventory.AssetOnEstimateDocumentLine",
                to="accounting.estimatedocumentline",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="recurring_sales_invoice_document_lines",
            field=models.ManyToManyField(
                through="inventory.AssetOnRecurringSalesInvoiceDocumentLine",
                to="accounting.recurringsalesinvoicedocumentline",
            ),
        ),
        migrations.AddField(
            model_name="assetonjournaldocumentline",
            name="value",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assetonrecurringsalesinvoicedocumentline",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recurring_sales_invoice_document_line_assets",
                to="inventory.asset",
            ),
        ),
        migrations.AddField(
            model_name="assetonrecurringsalesinvoicedocumentline",
            name="document_line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assets",
                to="accounting.recurringsalesinvoicedocumentline",
            ),
        ),
        migrations.AddField(
            model_name="assetonestimatedocumentline",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="estimate_document_line_assets",
                to="inventory.asset",
            ),
        ),
        migrations.AddField(
            model_name="assetonestimatedocumentline",
            name="document_line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assets",
                to="accounting.estimatedocumentline",
            ),
        ),
        migrations.CreateModel(
            name="AssetSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_subscriptions",
                        to="inventory.asset",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="accounting.subscription",
                    ),
                ),
            ],
            options={
                "unique_together": {("asset", "subscription")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="assetonrecurringsalesinvoicedocumentline",
            unique_together={("asset", "document_line")},
        ),
        migrations.AlterUniqueTogether(
            name="assetonestimatedocumentline",
            unique_together={("asset", "document_line")},
        ),
    ]
