# Generated by Django 3.0.5 on 2020-06-29 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0004_auto_20200629_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Asset')),
            ],
            options={
                'verbose_name': 'media set',
                'verbose_name_plural': 'media sets',
            },
        ),
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.ImageField(upload_to='')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.MediaSet')),
            ],
            options={
                'verbose_name': 'media item',
                'verbose_name_plural': 'media items',
            },
        ),
    ]
