# Generated by Django 3.0.5 on 2020-06-29 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediaset',
            old_name='remark',
            new_name='remarks',
        ),
    ]
