# Generated by Django 4.1.7 on 2023-05-03 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("new_customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewRentalCustomer",
            fields=[
                (
                    "newcustomer_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="new_customers.newcustomer",
                    ),
                ),
                (
                    "wants_reduced_liability",
                    models.BooleanField(
                        default=True, verbose_name="wants reduced liability"
                    ),
                ),
                (
                    "affiliate_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="affiliate name",
                    ),
                ),
                (
                    "instrument_numbers",
                    models.TextField(blank=True, verbose_name="instrument numbers"),
                ),
                (
                    "rental_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="rental price",
                    ),
                ),
                (
                    "date_received",
                    models.DateField(
                        blank=True, null=True, verbose_name="date received"
                    ),
                ),
            ],
            options={
                "verbose_name": "new rental customer",
                "verbose_name_plural": "new rental customers",
            },
            bases=("new_customers.newcustomer",),
        ),
    ]
