# Generated by Django 4.1.6 on 2023-02-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("new_rental_customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newrentalcustomer",
            name="date_received",
            field=models.DateField(blank=True, null=True, verbose_name="date received"),
        ),
    ]
