# Generated by Django 4.1.2 on 2022-10-05 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0019_ledgeraccount_is_assets_inventory"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegisteredRentalCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "wants_sepa_mandate",
                    models.BooleanField(
                        default=True, verbose_name="Wants SEPA mandate"
                    ),
                ),
                (
                    "sepa_mandate_sent",
                    models.BooleanField(
                        default=False, verbose_name="SEPA mandate request was sent"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "processed",
                    models.BooleanField(default=False, verbose_name="Processed"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="processed at"
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.contact",
                        verbose_name="contact",
                    ),
                ),
            ],
            options={
                "verbose_name": "registered rental customer",
                "verbose_name_plural": "registered rental customers",
            },
        ),
    ]
