# Generated by Django 4.1.2 on 2022-10-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental_customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registeredrentalcustomer",
            name="affiliate_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="affiliate name"
            ),
        ),
        migrations.AddField(
            model_name="registeredrentalcustomer",
            name="asset_numbers",
            field=models.TextField(blank=True, verbose_name="notes"),
        ),
        migrations.AddField(
            model_name="registeredrentalcustomer",
            name="wants_reduced_liability",
            field=models.BooleanField(
                default=True, verbose_name="Wants reduced liability"
            ),
        ),
    ]
