# Generated by Django 4.1.2 on 2022-10-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental_customers", "0002_registeredrentalcustomer_affiliate_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registeredrentalcustomer",
            name="asset_numbers",
        ),
        migrations.AddField(
            model_name="registeredrentalcustomer",
            name="instrument_numbers",
            field=models.TextField(blank=True, verbose_name="instrument numbers"),
        ),
    ]
