# Generated by Django 4.1.2 on 2022-10-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_alter_asset_options_and_more"),
        (
            "rental_customers",
            "0003_remove_registeredrentalcustomer_asset_numbers_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="registeredrentalcustomer",
            name="assets",
            field=models.ManyToManyField(to="inventory.asset", verbose_name="assets"),
        ),
        migrations.AddField(
            model_name="registeredrentalcustomer",
            name="rental_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="rental price",
            ),
        ),
    ]
