# Generated by Django 4.1.2 on 2022-10-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_alter_asset_options_and_more"),
        ("rental_customers", "0004_registeredrentalcustomer_assets_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registeredrentalcustomer",
            name="assets",
            field=models.ManyToManyField(
                blank=True, to="inventory.asset", verbose_name="assets"
            ),
        ),
    ]
