# Generated by Django 4.1.7 on 2023-05-03 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounting", "0001_initial"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "code_defined",
                    models.BooleanField(default=False, verbose_name="code defined"),
                ),
            ],
            options={
                "verbose_name": "ticket type",
                "verbose_name_plural": "ticket types",
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("closed", models.BooleanField(default=False, verbose_name="closed")),
                (
                    "date_closed",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="closed at"
                    ),
                ),
                (
                    "date_due",
                    models.DateField(blank=True, null=True, verbose_name="date due"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "assets",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tickets",
                        to="inventory.asset",
                        verbose_name="assets",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets_assigned",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="assigned to",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="accounting.contact",
                        verbose_name="contact",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "estimates",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tickets",
                        to="accounting.estimate",
                        verbose_name="estimate",
                    ),
                ),
                (
                    "sales_invoices",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tickets",
                        to="accounting.salesinvoice",
                        verbose_name="sales invoices",
                    ),
                ),
                (
                    "ticket_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tickets.tickettype",
                        verbose_name="ticket type",
                    ),
                ),
            ],
            options={
                "verbose_name": "ticket",
                "verbose_name_plural": "tickets",
            },
        ),
    ]
