# Generated by Django 4.1.6 on 2023-02-20 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="title",
        ),
    ]
