# Generated by Django 6.0.3 on 2026-04-12 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="estimates",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="sales_invoices",
        ),
    ]
